import type { SeedFragrance } from '../types';

/**
 * Group C real fragrances (roster #35-50).
 *
 * PROVENANCE WARNING: this file was written in a research session where web search was exhausted
 * and the egress proxy blocked every house, retailer, press and Wikidata host. Nothing here was
 * read from a live page. Facts come from editor knowledge, every source is typed 'editorial' with
 * url null and confidence <= 0.6, and each one says so. Verify against the house pages before
 * publishing.
 */

type Src = NonNullable<SeedFragrance['sources']>[number];

const OFFLINE = 'No web access in research session (search budget exhausted, house and retailer hosts blocked by egress proxy).';

const src = (
  field: Src['field'],
  publisher: string,
  confidence: number,
  note: string,
): Src => ({ field, type: 'editorial', publisher, url: null, confidence, note: `${OFFLINE} ${note}` });

export const FRAGRANCES_C: SeedFragrance[] = [
  // 35 ------------------------------------------------------------------------------------------
  {
    slug: 'layton',
    name: 'Layton',
    brand: 'parfums-de-marly',
    concentration: 'edp',
    releaseYear: 2016,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: ['hamid-merati-kashani'],
    style: 'Spiced vanilla apple',
    summary:
      'Crisp apple and lavender up top, then a warm cardamom and vanilla middle that settles into soft, peppery woods.',
    bestFor: 'Cool evenings, dates, crowd-pleasing wear',
    sources: [
      src('identity', 'Parfums de Marly', 0.6, 'Name, year and concentration from editor knowledge; verify on parfums-de-marly.com.'),
      src('notes', 'Parfums de Marly', 0.5, 'Pyramid as the house is understood to list it; "pepper" mapped to black-pepper.'),
      src('perfumers', 'Parfums de Marly', 0.5, 'Commonly credited perfumer; not confirmed against a primary page.'),
      src('price', 'Authorised retailers', 0.4, 'Approximate 2025 US price for 125 ml.'),
    ],
    bottleDescription:
      'A heavy rectangular clear glass bottle with the house horse crest in gold on the front, a gold collar and a dark cap.',
    editorial:
      'Layton is the Parfums de Marly scent most people try first, and it is easy to see why: apple and lavender make it bright, cardamom and vanilla make it warm, and the woods stop it going sugary. It is loud for the first few hours. If you like the idea of a fougère but find the old barbershop ones too dry, this is the friendlier version.',
    notes: {
      top: ['green-apple', 'lavender', 'bergamot', 'mandarin'],
      heart: ['geranium', 'violet', 'jasmine'],
      base: ['vanilla', 'cardamom', 'sandalwood', 'black-pepper', 'guaiac-wood', 'patchouli'],
    },
    priceBand: 'luxury',
    priceUsd: 350,
    sizeMl: 125,
    character: {
      opening: { fresh: 0.6, fruity: 0.5, green: 0.2, spicy: 0.3, sweet: 0.3 },
      heart: { spicy: 0.5, floral: 0.3, sweet: 0.5, warm: 0.5, woody: 0.3 },
      drydown: { sweet: 0.5, warm: 0.6, woody: 0.5, creamy: 0.3, spicy: 0.3 },
    },
    phases: { heartAtMin: 20, drydownAtMin: 150 },
    community: {
      tier: 'large',
      rating: 8.4,
      divisiveness: 0.25,
      scent: 8.6,
      performance: 8.3,
      value: 6.0,
      originality: 7.4,
      longevityHrs: 9,
      projection: 4,
      projectionLater: 3,
      seasons: { spring: 0.45, summer: 0.15, autumn: 0.9, winter: 0.8 },
      time: { day: 0.5, night: 0.85 },
      weather: { hot: 0.1, mild: 0.7, cold: 0.85, rain: 0.5, humid: 0.15 },
      occasions: { office: 0.4, school: 0.35, date: 0.85, formal: 0.6, casual: 0.6, nightlife: 0.8, special: 0.65, outdoors: 0.3 },
      perceived: {
        'green-apple': 0.7,
        vanilla: 0.75,
        cardamom: 0.6,
        lavender: 0.55,
        'black-pepper': 0.3,
        sandalwood: 0.35,
        geranium: 0.2,
        'tonka-bean': 0.25,
        mint: 0.2,
        patchouli: 0.12,
      },
      strongestByPhase: {
        opening: ['green-apple', 'lavender', 'mint'],
        heart: ['cardamom', 'geranium', 'vanilla'],
        drydown: ['vanilla', 'sandalwood', 'tonka-bean'],
      },
    },
    bottle: {
      body: 'block',
      width: 1.0,
      height: 1.15,
      depth: 0.85,
      glass: 'clear',
      liquid: '#E8DDB5',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'black',
      capWidth: 0.9,
      capHeight: 0.9,
      collar: 'gold',
      label: 'plate',
      labelColor: '#B8975A',
      labelInk: '#2A2A2A',
    },
    accent: '#8A6E4B',
  },

  // 36 ------------------------------------------------------------------------------------------
  {
    slug: 'portrait-of-a-lady',
    name: 'Portrait of a Lady',
    brand: 'frederic-malle',
    concentration: 'edp',
    releaseYear: 2010,
    status: 'current',
    marketedFor: 'feminine',
    perfumers: ['dominique-ropion'],
    style: 'Dark rose and patchouli',
    summary:
      'A huge, dark rose with berries and clove, set on patchouli and smoky incense. Wine-red at first, drying to resin and soft sandalwood.',
    bestFor: 'Winter evenings, nights you want to be noticed',
    sources: [
      src('identity', 'Frédéric Malle', 0.6, 'Name, year and concentration from editor knowledge; verify on fredericmalle.com.'),
      src('notes', 'Frédéric Malle', 0.5, 'Listed as flat because the house describes key materials rather than a strict pyramid; list from editor knowledge.'),
      src('perfumers', 'Frédéric Malle', 0.6, 'Malle credits the perfumer on the label; perfumer credit is widely known but not re-checked.'),
      src('price', 'Authorised retailers', 0.4, 'Approximate 2025 US price for 100 ml.'),
    ],
    bottleDescription:
      'A tall, plain rectangular clear glass bottle with a black cap and a cream label edged in red that names both the scent and the perfumer.',
    editorial:
      'Dominique Ropion built Portrait of a Lady around an unusually large dose of rose and an equally serious amount of patchouli, and it shows. The opening is jammy and spiced, the heart is all rose, and the base turns smoky and resinous for hours. It is marketed to women but plenty of men wear it, and one spray is often enough.',
    notes: {
      flat: ['rose', 'blackcurrant', 'raspberry', 'cinnamon', 'clove', 'patchouli', 'incense', 'sandalwood', 'benzoin', 'musk', 'amber'],
    },
    priceBand: 'luxury',
    priceUsd: 455,
    sizeMl: 100,
    character: {
      opening: { floral: 0.7, fruity: 0.5, spicy: 0.5, sweet: 0.3 },
      heart: { floral: 0.8, earthy: 0.5, spicy: 0.3, warm: 0.4, smoky: 0.2 },
      drydown: { earthy: 0.6, woody: 0.5, smoky: 0.4, warm: 0.6, floral: 0.3 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 120 },
    community: {
      tier: 'large',
      rating: 8.6,
      divisiveness: 0.3,
      scent: 8.9,
      performance: 9.0,
      value: 5.5,
      originality: 8.2,
      longevityHrs: 12,
      projection: 4,
      projectionLater: 3,
      seasons: { spring: 0.3, summer: 0.1, autumn: 0.9, winter: 0.85 },
      time: { day: 0.4, night: 0.9 },
      weather: { hot: 0.05, mild: 0.6, cold: 0.9, rain: 0.55, humid: 0.1 },
      occasions: { office: 0.25, school: 0.1, date: 0.7, formal: 0.8, casual: 0.3, nightlife: 0.7, special: 0.8, outdoors: 0.15 },
      perceived: {
        rose: 0.95,
        patchouli: 0.75,
        incense: 0.55,
        raspberry: 0.45,
        clove: 0.35,
        blackcurrant: 0.3,
        sandalwood: 0.3,
        benzoin: 0.25,
        cinnamon: 0.2,
        boozy: 0.2,
        musk: 0.1,
      },
      strongestByPhase: {
        opening: ['rose', 'raspberry', 'clove'],
        heart: ['rose', 'patchouli', 'incense'],
        drydown: ['patchouli', 'incense', 'sandalwood', 'benzoin'],
      },
    },
    bottle: {
      body: 'tall',
      width: 0.9,
      height: 1.15,
      depth: 0.85,
      glass: 'clear',
      liquid: '#8C4A32',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'black',
      capWidth: 0.95,
      capHeight: 1.0,
      collar: 'none',
      label: 'paper',
      labelColor: '#F3EEE3',
      labelInk: '#A8402F',
    },
    accent: '#7A3B3F',
  },

  // 37 ------------------------------------------------------------------------------------------
  {
    slug: 'chergui',
    name: 'Chergui',
    brand: 'serge-lutens',
    concentration: 'edp',
    releaseYear: 2001,
    status: 'current',
    marketedFor: 'shared',
    perfumers: ['christopher-sheldrake'],
    style: 'Honeyed tobacco and hay',
    summary:
      'Sweet tobacco leaf and honey with dry hay and a thread of incense, drying down to soft, powdery musk and sandalwood.',
    bestFor: 'Cold days, slow weekends, reading by a lamp',
    sources: [
      src('identity', 'Serge Lutens', 0.55, 'First released in 2001 as a Palais Royal exclusive, later sold more widely as an EDP; dates from editor knowledge.'),
      src('notes', 'Serge Lutens', 0.5, 'House lists notes without a pyramid; list from editor knowledge.'),
      src('perfumers', 'Serge Lutens', 0.55, 'Lutens does not always print perfumer credits; Sheldrake attribution is widely reported.'),
      src('price', 'Authorised retailers', 0.4, 'Approximate 2025 US price for 50 ml.'),
    ],
    bottleDescription:
      'A plain, slim rectangular clear glass bottle with a squared black cap and simple black printed lettering.',
    editorial:
      'Named after a hot desert wind, Chergui is one of the Serge Lutens scents that wins over people who usually find the house too strange. The tobacco here is the cured-leaf, slightly sweet kind rather than smoke, and honey and hay give it a golden, sunny feel. Over the evening it softens into a powdery, gently resinous skin scent that lasts much longer than you expect.',
    notes: {
      flat: ['tobacco', 'honey', 'hay', 'incense', 'rose', 'iris', 'musk', 'sandalwood'],
    },
    priceBand: 'premium',
    priceUsd: 175,
    sizeMl: 50,
    character: {
      opening: { sweet: 0.6, warm: 0.6, earthy: 0.3, smoky: 0.3, spicy: 0.2 },
      heart: { sweet: 0.5, warm: 0.7, floral: 0.2, powdery: 0.3, earthy: 0.3, smoky: 0.3 },
      drydown: { warm: 0.6, powdery: 0.5, woody: 0.4, creamy: 0.3, sweet: 0.3 },
    },
    phases: { heartAtMin: 20, drydownAtMin: 180 },
    community: {
      tier: 'medium',
      rating: 8.3,
      divisiveness: 0.3,
      scent: 8.6,
      performance: 8.2,
      value: 6.8,
      originality: 8.3,
      longevityHrs: 10,
      projection: 3,
      projectionLater: 2,
      seasons: { spring: 0.2, summer: 0.05, autumn: 0.9, winter: 0.9 },
      time: { day: 0.5, night: 0.8 },
      weather: { hot: 0.05, mild: 0.55, cold: 0.95, rain: 0.6, humid: 0.05 },
      occasions: { office: 0.4, school: 0.2, date: 0.6, formal: 0.5, casual: 0.6, nightlife: 0.5, special: 0.5, outdoors: 0.2 },
      perceived: {
        tobacco: 0.85,
        honey: 0.8,
        hay: 0.6,
        incense: 0.4,
        powdery: 0.35,
        musk: 0.3,
        'tonka-bean': 0.3,
        sandalwood: 0.25,
        iris: 0.2,
        animalic: 0.15,
        rose: 0.1,
      },
      strongestByPhase: {
        opening: ['honey', 'tobacco', 'hay'],
        heart: ['tobacco', 'honey', 'incense'],
        drydown: ['powdery', 'musk', 'sandalwood', 'tonka-bean'],
      },
    },
    bottle: {
      body: 'tall',
      width: 0.85,
      height: 1.1,
      depth: 0.7,
      glass: 'clear',
      liquid: '#B5772E',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'black',
      capWidth: 0.9,
      capHeight: 0.8,
      collar: 'none',
      label: 'printed',
      labelInk: '#1A1A1A',
    },
    accent: '#9A6A35',
  },

  // 38 ------------------------------------------------------------------------------------------
  {
    slug: 'un-jardin-sur-le-nil',
    name: 'Un Jardin sur le Nil',
    brand: 'hermes',
    concentration: 'edt',
    releaseYear: 2005,
    status: 'current',
    marketedFor: 'shared',
    perfumers: ['jean-claude-ellena'],
    style: 'Green mango and citrus',
    summary:
      'Tart green mango and grapefruit over a watery lotus and soft woods. Juicy, green and quiet, with a faint incense-like dryness at the end.',
    bestFor: 'Hot days, the office, easy everyday wear',
    sources: [
      src('identity', 'Hermès', 0.6, 'Name, year and concentration from editor knowledge; verify on hermes.com.'),
      src('notes', 'Hermès', 0.4, 'Hermès describes a handful of key notes (green mango, lotus, sycamore) rather than a pyramid; grapefruit added from widely repeated descriptions. Low confidence.'),
      src('perfumers', 'Hermès', 0.6, 'Created by the then in-house perfumer; widely documented but not re-checked.'),
      src('price', 'Authorised retailers', 0.4, 'Approximate 2025 US price for 100 ml.'),
    ],
    bottleDescription:
      'A softly rounded rectangular glass bottle with a pale green tint and a smooth green-grey stopper-style cap.',
    editorial:
      'Jean-Claude Ellena made this one after a trip to Aswan, and it is a clear example of his light-handed style: a few materials and lots of air. The green mango is sour and leafy rather than tropical, which keeps it from feeling like a fruit cocktail. It doesn\'t project much and fades to a woody whisper within a few hours, which is either the charm or the problem depending on what you want.',
    notes: {
      flat: ['grapefruit', 'green-mango', 'lotus', 'sycamore'],
    },
    priceBand: 'premium',
    priceUsd: 165,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.8, green: 0.7, fruity: 0.6 },
      heart: { green: 0.6, fresh: 0.5, floral: 0.3, fruity: 0.4, clean: 0.3 },
      drydown: { woody: 0.5, green: 0.3, clean: 0.3, smoky: 0.2, earthy: 0.2 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 90 },
    community: {
      tier: 'large',
      rating: 8.0,
      divisiveness: 0.25,
      scent: 8.4,
      performance: 6.0,
      value: 7.0,
      originality: 8.0,
      longevityHrs: 5,
      projection: 3,
      projectionLater: 2,
      seasons: { spring: 0.85, summer: 0.9, autumn: 0.3, winter: 0.1 },
      time: { day: 0.95, night: 0.3 },
      weather: { hot: 0.85, mild: 0.8, cold: 0.15, rain: 0.4, humid: 0.75 },
      occasions: { office: 0.8, school: 0.6, date: 0.3, formal: 0.3, casual: 0.8, nightlife: 0.15, special: 0.2, outdoors: 0.7 },
      perceived: {
        'green-mango': 0.8,
        grapefruit: 0.55,
        lotus: 0.35,
        'tomato-leaf': 0.25,
        incense: 0.25,
        musk: 0.25,
        mineral: 0.2,
        sycamore: 0.15,
      },
      strongestByPhase: {
        opening: ['green-mango', 'grapefruit'],
        heart: ['green-mango', 'lotus', 'tomato-leaf'],
        drydown: ['incense', 'musk', 'sycamore'],
      },
    },
    bottle: {
      body: 'flask',
      width: 1.0,
      height: 1.0,
      depth: 0.8,
      glass: 'tinted',
      glassTint: '#C9D9B5',
      liquid: '#D7E3B8',
      fill: 0.85,
      cap: 'pebble',
      capMaterial: 'resin',
      capColor: '#7E9A6E',
      collar: 'none',
      label: 'printed',
      labelInk: '#3A4A33',
    },
    accent: '#7E9A6E',
  },

  // 39 ------------------------------------------------------------------------------------------
  {
    slug: 'molecule-01',
    name: 'Molecule 01',
    brand: 'escentric-molecules',
    concentration: 'edt',
    releaseYear: 2006,
    status: 'current',
    marketedFor: 'shared',
    perfumers: ['geza-schoen'],
    style: 'Single-molecule woods',
    summary:
      'Pure Iso E Super: a soft, velvety cedar-like woodiness with a faint peppery glow. Some barely smell it on themselves while others notice it all day.',
    bestFor: 'Every day, layering, people who dislike perfume',
    sources: [
      src('identity', 'Escentric Molecules', 0.6, 'Name, year and concentration from editor knowledge; verify on escentric.com.'),
      src('notes', 'Escentric Molecules', 0.6, 'The house presents it as a single aroma chemical, Iso E Super, in alcohol.'),
      src('perfumers', 'Escentric Molecules', 0.6, 'Created by the brand founder; widely documented but not re-checked.'),
      src('price', 'Authorised retailers', 0.4, 'Approximate 2025 US price for 100 ml.'),
    ],
    bottleDescription:
      'A tall, slim clear glass cylinder with the name printed in black and a plain cap.',
    editorial:
      'Molecule 01 is one aroma chemical in alcohol, nothing more. Iso E Super is usually a supporting player in hundreds of fragrances, and on its own it smells of warm pencil shavings, dry cedar and clean skin. Because noses tire of it quickly, many wearers lose track of it within minutes while people around them keep noticing it.',
    notes: { flat: ['iso-e-super'] },
    priceBand: 'premium',
    priceUsd: 160,
    sizeMl: 100,
    character: {
      opening: { woody: 0.7, clean: 0.3, warm: 0.3, spicy: 0.1 },
      heart: { woody: 0.7, clean: 0.3, warm: 0.3, creamy: 0.2 },
      drydown: { woody: 0.6, warm: 0.3, clean: 0.3, creamy: 0.2 },
    },
    phases: { heartAtMin: 10, drydownAtMin: 60 },
    community: {
      tier: 'large',
      rating: 7.4,
      divisiveness: 0.55,
      scent: 7.5,
      performance: 6.0,
      value: 7.5,
      originality: 8.5,
      longevityHrs: 7,
      projection: 2,
      projectionLater: 2,
      seasons: { spring: 0.7, summer: 0.6, autumn: 0.7, winter: 0.55 },
      time: { day: 0.85, night: 0.6 },
      weather: { hot: 0.5, mild: 0.85, cold: 0.6, rain: 0.55, humid: 0.45 },
      occasions: { office: 0.85, school: 0.7, date: 0.55, formal: 0.45, casual: 0.85, nightlife: 0.4, special: 0.35, outdoors: 0.5 },
      perceived: {
        'iso-e-super': 0.7,
        cedarwood: 0.55,
        musk: 0.3,
        'black-pepper': 0.2,
        mineral: 0.2,
        ink: 0.15,
        violet: 0.1,
      },
      strongestByPhase: {
        opening: ['iso-e-super', 'cedarwood', 'black-pepper'],
        heart: ['iso-e-super', 'cedarwood', 'musk'],
        drydown: ['iso-e-super', 'musk', 'mineral'],
      },
    },
    bottle: {
      body: 'cylinder',
      width: 0.8,
      height: 1.2,
      glass: 'clear',
      liquid: '#F1EEE4',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'black',
      capWidth: 1.0,
      capHeight: 0.9,
      collar: 'none',
      label: 'printed',
      labelInk: '#1E1E1E',
    },
    accent: '#8C8577',
  },

  // 40 ------------------------------------------------------------------------------------------
  {
    slug: 'not-a-perfume',
    name: 'Not a Perfume',
    brand: 'juliette-has-a-gun',
    concentration: 'edp',
    releaseYear: 2010,
    status: 'current',
    marketedFor: 'shared',
    perfumers: ['romano-ricci'],
    style: 'Single-molecule ambroxan',
    summary:
      'Just ambroxan: a clean, faintly salty, skin-like warmth with a woody hum. Quiet up close, but it drifts out around you for hours.',
    bestFor: 'Daily wear, sensitive noses, layering',
    sources: [
      src('identity', 'Juliette Has a Gun', 0.6, 'Name, year and concentration from editor knowledge; verify on juliettehasagun.com.'),
      src('notes', 'Juliette Has a Gun', 0.6, 'The house presents it as a single material, Cetalox (an ambroxan), mapped to ambroxan.'),
      src('perfumers', 'Juliette Has a Gun', 0.5, 'Credited to the brand founder; not re-checked.'),
      src('price', 'Authorised retailers', 0.4, 'Approximate 2025 US price for 100 ml.'),
    ],
    bottleDescription:
      'A clear rectangular glass bottle with the name printed on the front and a tall silver-toned cap.',
    editorial:
      'Romano Ricci built Not a Perfume around a single material, Cetalox (a brand of ambroxan), and the house markets it as free of the common listed allergens, which is why it gets recommended to people who react to most fragrance. It smells like warm, clean skin with a mineral, woody edge. Like Molecule 01, it is easy to stop noticing on yourself.',
    notes: { flat: ['ambroxan'] },
    priceBand: 'premium',
    priceUsd: 140,
    sizeMl: 100,
    character: {
      opening: { clean: 0.5, woody: 0.5, warm: 0.4, fresh: 0.2 },
      heart: { clean: 0.5, woody: 0.4, warm: 0.5, fresh: 0.1 },
      drydown: { warm: 0.5, woody: 0.4, clean: 0.4, creamy: 0.2 },
    },
    phases: { heartAtMin: 10, drydownAtMin: 60 },
    community: {
      tier: 'medium',
      rating: 7.3,
      divisiveness: 0.5,
      scent: 7.3,
      performance: 6.8,
      value: 7.0,
      originality: 7.5,
      longevityHrs: 8,
      projection: 2,
      projectionLater: 2,
      seasons: { spring: 0.7, summer: 0.55, autumn: 0.7, winter: 0.55 },
      time: { day: 0.85, night: 0.6 },
      weather: { hot: 0.5, mild: 0.85, cold: 0.6, rain: 0.55, humid: 0.45 },
      occasions: { office: 0.85, school: 0.7, date: 0.55, formal: 0.4, casual: 0.85, nightlife: 0.4, special: 0.3, outdoors: 0.5 },
      perceived: {
        ambroxan: 0.75,
        musk: 0.4,
        mineral: 0.35,
        'sea-salt': 0.3,
        ambergris: 0.3,
        laundry: 0.2,
        cedarwood: 0.15,
      },
      strongestByPhase: {
        opening: ['ambroxan', 'mineral'],
        heart: ['ambroxan', 'musk', 'ambergris'],
        drydown: ['ambroxan', 'musk', 'sea-salt'],
      },
    },
    bottle: {
      body: 'block',
      width: 0.9,
      height: 1.1,
      depth: 0.8,
      glass: 'clear',
      liquid: '#F3F0E6',
      fill: 0.85,
      cap: 'faceted',
      capMaterial: 'silver',
      capWidth: 0.8,
      capHeight: 1.2,
      collar: 'silver',
      label: 'printed',
      labelInk: '#1A1A1A',
    },
    accent: '#A69C8A',
  },

  // 41 ------------------------------------------------------------------------------------------
  {
    slug: 'naxos',
    name: 'Naxos',
    brand: 'xerjoff',
    concentration: 'edp',
    releaseYear: 2015,
    status: 'current',
    marketedFor: 'shared',
    perfumers: [],
    style: 'Honey tobacco lavender',
    summary:
      'Bright lavender and citrus over a thick honey and cinnamon heart, settling into sweet tobacco and tonka. Rich, golden and very long-lasting.',
    bestFor: 'Autumn and winter evenings, special nights',
    sources: [
      src('identity', 'Xerjoff', 0.55, 'Part of the 1861 collection; name, year and concentration from editor knowledge.'),
      src('notes', 'Xerjoff', 0.5, 'Pyramid from editor knowledge; "jasmine sambac" mapped to jasmine.'),
      src('perfumers', 'Xerjoff', 0.3, 'Xerjoff does not prominently credit perfumers and no credit could be verified, so none is listed.'),
      src('price', 'Authorised retailers', 0.4, 'Approximate 2025 US price for 100 ml.'),
    ],
    bottleDescription:
      'A heavy clear glass bottle from the 1861 range with a gold-toned cap and gold detailing on the front.',
    editorial:
      'Naxos takes the lavender of a classic fougère and pours honey over it. The first half hour is aromatic and almost bright, then cinnamon, honey and tobacco take over and stay for most of the day. It is sweet but not sticky, and it is usually the first Xerjoff people get recommended.',
    notes: {
      top: ['lavender', 'bergamot', 'lemon'],
      heart: ['honey', 'cinnamon', 'cashmeran', 'jasmine'],
      base: ['tobacco', 'tonka-bean', 'vanilla'],
    },
    priceBand: 'luxury',
    priceUsd: 295,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.5, sweet: 0.4, spicy: 0.3, warm: 0.3, floral: 0.2 },
      heart: { sweet: 0.7, warm: 0.6, spicy: 0.4, smoky: 0.2, floral: 0.2 },
      drydown: { sweet: 0.6, warm: 0.7, smoky: 0.3, woody: 0.3, creamy: 0.3 },
    },
    phases: { heartAtMin: 25, drydownAtMin: 150 },
    community: {
      tier: 'large',
      rating: 8.6,
      divisiveness: 0.2,
      scent: 8.8,
      performance: 8.5,
      value: 6.3,
      originality: 7.8,
      longevityHrs: 10,
      projection: 3,
      projectionLater: 3,
      seasons: { spring: 0.3, summer: 0.05, autumn: 0.9, winter: 0.9 },
      time: { day: 0.45, night: 0.85 },
      weather: { hot: 0.05, mild: 0.55, cold: 0.95, rain: 0.55, humid: 0.05 },
      occasions: { office: 0.35, school: 0.2, date: 0.75, formal: 0.65, casual: 0.5, nightlife: 0.65, special: 0.75, outdoors: 0.2 },
      perceived: {
        honey: 0.85,
        tobacco: 0.7,
        lavender: 0.6,
        cinnamon: 0.45,
        'tonka-bean': 0.45,
        vanilla: 0.4,
        bergamot: 0.2,
        boozy: 0.2,
        caramel: 0.2,
        jasmine: 0.08,
      },
      strongestByPhase: {
        opening: ['lavender', 'bergamot', 'honey'],
        heart: ['honey', 'cinnamon', 'tobacco'],
        drydown: ['tobacco', 'tonka-bean', 'vanilla'],
      },
    },
    bottle: {
      body: 'cylinder',
      width: 1.0,
      height: 1.05,
      glass: 'clear',
      liquid: '#C98F3A',
      fill: 0.85,
      cap: 'disc',
      capMaterial: 'gold',
      capWidth: 1.2,
      capHeight: 0.8,
      collar: 'gold',
      label: 'plate',
      labelColor: '#C2A15B',
      labelInk: '#3A2A12',
    },
    accent: '#B07D3A',
  },

  // 42 ------------------------------------------------------------------------------------------
  {
    slug: 'love-dont-be-shy',
    name: "Love, Don't Be Shy",
    brand: 'kilian',
    concentration: 'edp',
    releaseYear: 2007,
    status: 'current',
    marketedFor: 'shared',
    perfumers: ['calice-becker'],
    style: 'Orange blossom marshmallow',
    summary:
      'Orange blossom and neroli whipped into a soft marshmallow and vanilla base. Sweet and fluffy, with a bit of musky warmth underneath.',
    bestFor: 'Dates, cosy evenings, sweet-floral fans',
    sources: [
      src('identity', 'Kilian Paris', 0.55, 'Name and capitalisation as the house styles it; year and concentration from editor knowledge.'),
      src('notes', 'Kilian Paris', 0.4, 'The house highlights neroli, orange blossom and marshmallow; the fuller pyramid here is from editor knowledge and may not match the current listing.'),
      src('perfumers', 'Kilian Paris', 0.55, 'Widely reported credit; not re-checked.'),
      src('price', 'Authorised retailers', 0.4, 'Approximate 2025 US price for 50 ml.'),
    ],
    bottleDescription:
      'A heavy rectangular refillable glass bottle in pale tones with a squared metal cap and the name engraved on a plaque.',
    editorial:
      'Love, Don\'t Be Shy was one of the first Kilian launches, built by Calice Becker around orange blossom and a marshmallow accord. It is openly sugary, but the neroli and a musky, slightly animal base keep it from smelling like a sweet shop. Expect a sweet trail that lasts all evening.',
    notes: {
      top: ['bergamot', 'neroli', 'pink-pepper', 'coriander'],
      heart: ['orange-blossom', 'iris', 'jasmine', 'rose', 'honeysuckle'],
      base: ['marshmallow', 'vanilla', 'caramel', 'labdanum', 'musk'],
    },
    priceBand: 'luxury',
    priceUsd: 295,
    sizeMl: 50,
    character: {
      opening: { floral: 0.6, fresh: 0.4, sweet: 0.5, spicy: 0.1 },
      heart: { floral: 0.7, sweet: 0.7, creamy: 0.3, powdery: 0.2 },
      drydown: { sweet: 0.8, creamy: 0.5, warm: 0.5, powdery: 0.3, floral: 0.3 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 150 },
    community: {
      tier: 'medium',
      rating: 8.2,
      divisiveness: 0.35,
      scent: 8.4,
      performance: 8.2,
      value: 5.5,
      originality: 7.6,
      longevityHrs: 10,
      projection: 3,
      projectionLater: 3,
      seasons: { spring: 0.55, summer: 0.2, autumn: 0.7, winter: 0.75 },
      time: { day: 0.55, night: 0.8 },
      weather: { hot: 0.1, mild: 0.7, cold: 0.8, rain: 0.5, humid: 0.15 },
      occasions: { office: 0.35, school: 0.3, date: 0.85, formal: 0.5, casual: 0.55, nightlife: 0.65, special: 0.7, outdoors: 0.2 },
      perceived: {
        'orange-blossom': 0.85,
        marshmallow: 0.75,
        vanilla: 0.6,
        neroli: 0.4,
        musk: 0.35,
        caramel: 0.3,
        powdery: 0.25,
        animalic: 0.15,
        honeysuckle: 0.1,
      },
      strongestByPhase: {
        opening: ['neroli', 'orange-blossom'],
        heart: ['orange-blossom', 'marshmallow'],
        drydown: ['marshmallow', 'vanilla', 'musk', 'caramel'],
      },
    },
    bottle: {
      body: 'block',
      width: 0.95,
      height: 1.05,
      depth: 0.8,
      glass: 'frosted',
      glassTint: '#EFE6DA',
      liquid: '#F1D9B8',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'silver',
      capWidth: 1.0,
      capHeight: 0.8,
      collar: 'silver',
      label: 'plate',
      labelColor: '#C9C9C9',
      labelInk: '#2A2A2A',
    },
    accent: '#C98E6B',
  },

  // 43 ------------------------------------------------------------------------------------------
  {
    slug: 'khamrah',
    name: 'Khamrah',
    brand: 'lattafa',
    concentration: 'edp',
    releaseYear: 2022,
    status: 'current',
    marketedFor: 'shared',
    perfumers: [],
    style: 'Boozy date and spice gourmand',
    summary:
      'Cinnamon and nutmeg over sticky dates and praline, sinking into a dense vanilla, tonka and resin base. Sweet, boozy and very warm.',
    bestFor: 'Cold nights, sweet-scent lovers, small budgets',
    sources: [
      src('identity', 'Lattafa', 0.55, 'Name, year and concentration from editor knowledge; verify on lattafa.com.'),
      src('notes', 'Lattafa', 0.4, 'Abridged pyramid from editor knowledge; the house listing may include further notes.'),
      src('perfumers', 'Lattafa', 0.3, 'No perfumer credit published by the house that could be checked; none listed.'),
      src('price', 'Authorised retailers', 0.4, 'Approximate 2025 US price for 100 ml.'),
    ],
    bottleDescription:
      'A squared dark amber-brown glass bottle with a faceted gold cap and gold detailing.',
    editorial:
      'Khamrah became one of the breakout budget fragrances of the early 2020s, and it is often compared with Kilian\'s Angels\' Share. The opening is a warm spice-cabinet blast, the heart is dates and praline, and the base is a thick vanilla and benzoin that lasts well into the next day. It is easy to overspray: two sprays is plenty.',
    notes: {
      top: ['cinnamon', 'nutmeg', 'bergamot'],
      heart: ['date', 'praline', 'tuberose'],
      base: ['vanilla', 'tonka-bean', 'amberwood', 'myrrh', 'benzoin', 'akigalawood'],
    },
    priceBand: 'budget',
    priceUsd: 40,
    sizeMl: 100,
    character: {
      opening: { spicy: 0.7, sweet: 0.6, warm: 0.6, fruity: 0.3 },
      heart: { sweet: 0.8, warm: 0.7, fruity: 0.4, spicy: 0.4, floral: 0.2 },
      drydown: { sweet: 0.7, warm: 0.8, creamy: 0.4, woody: 0.3, smoky: 0.2 },
    },
    phases: { heartAtMin: 20, drydownAtMin: 150 },
    community: {
      tier: 'large',
      rating: 8.1,
      divisiveness: 0.3,
      scent: 8.3,
      performance: 8.6,
      value: 9.5,
      originality: 6.0,
      longevityHrs: 11,
      projection: 4,
      projectionLater: 3,
      seasons: { spring: 0.15, summer: 0.05, autumn: 0.85, winter: 0.95 },
      time: { day: 0.35, night: 0.9 },
      weather: { hot: 0.05, mild: 0.5, cold: 0.95, rain: 0.55, humid: 0.05 },
      occasions: { office: 0.25, school: 0.2, date: 0.75, formal: 0.45, casual: 0.5, nightlife: 0.75, special: 0.6, outdoors: 0.15 },
      perceived: {
        cinnamon: 0.8,
        vanilla: 0.7,
        date: 0.65,
        boozy: 0.55,
        praline: 0.5,
        'tonka-bean': 0.4,
        nutmeg: 0.3,
        benzoin: 0.3,
        caramel: 0.3,
        rum: 0.25,
        tuberose: 0.08,
      },
      strongestByPhase: {
        opening: ['cinnamon', 'boozy', 'nutmeg'],
        heart: ['date', 'praline', 'cinnamon'],
        drydown: ['vanilla', 'tonka-bean', 'benzoin'],
      },
    },
    bottle: {
      body: 'block',
      width: 1.0,
      height: 1.1,
      depth: 0.8,
      glass: 'smoked',
      glassTint: '#4A2A1A',
      liquid: '#7A3E1E',
      fill: 0.85,
      cap: 'faceted',
      capMaterial: 'gold',
      capWidth: 1.0,
      capHeight: 1.1,
      collar: 'gold',
      label: 'printed',
      labelInk: '#C9A55A',
    },
    accent: '#7A4A2A',
  },

  // 44 ------------------------------------------------------------------------------------------
  {
    slug: 'club-de-nuit-intense-man',
    name: 'Club de Nuit Intense Man',
    brand: 'armaf',
    concentration: 'edt',
    releaseYear: 2015,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: [],
    style: 'Smoky fruity chypre',
    summary:
      'A sharp, fizzy lemon and pineapple opening with smoky birch underneath, drying to musk and a dry, ambery woodiness.',
    bestFor: 'Nights out, cooler days, budget signature',
    sources: [
      src('identity', 'Armaf', 0.55, 'Name, year and concentration (EDT; a separate Parfum version exists) from editor knowledge.'),
      src('notes', 'Armaf', 0.45, 'Pyramid from editor knowledge; "apple" mapped to green-apple.'),
      src('perfumers', 'Armaf', 0.3, 'No perfumer credit published by the house that could be checked; none listed.'),
      src('price', 'Authorised retailers', 0.4, 'Approximate 2025 US price for 105 ml.'),
    ],
    bottleDescription:
      'A tall black glass bottle with angled, faceted shoulders, a silver collar and a silver cap.',
    editorial:
      'Club de Nuit Intense Man is the fragrance that made Armaf famous, mostly because it is often compared with Creed Aventus at a small fraction of the price. The opening is loud, sharp lemon with a smoky edge, which some people find harsh for the first fifteen minutes. Once it settles, the smoky pineapple and musk are well made and very long-lasting.',
    notes: {
      top: ['lemon', 'pineapple', 'bergamot', 'blackcurrant', 'green-apple'],
      heart: ['birch', 'jasmine', 'rose'],
      base: ['musk', 'ambergris', 'patchouli', 'vanilla'],
    },
    priceBand: 'budget',
    priceUsd: 40,
    sizeMl: 105,
    character: {
      opening: { fresh: 0.7, fruity: 0.6, smoky: 0.4, sweet: 0.2 },
      heart: { fruity: 0.5, smoky: 0.5, woody: 0.4, floral: 0.2, fresh: 0.3 },
      drydown: { woody: 0.5, smoky: 0.4, warm: 0.3, clean: 0.3, earthy: 0.3 },
    },
    phases: { heartAtMin: 20, drydownAtMin: 120 },
    community: {
      tier: 'large',
      rating: 7.9,
      divisiveness: 0.35,
      scent: 7.8,
      performance: 8.8,
      value: 9.5,
      originality: 5.8,
      longevityHrs: 10,
      projection: 4,
      projectionLater: 3,
      seasons: { spring: 0.6, summer: 0.4, autumn: 0.75, winter: 0.55 },
      time: { day: 0.55, night: 0.8 },
      weather: { hot: 0.3, mild: 0.8, cold: 0.6, rain: 0.5, humid: 0.3 },
      occasions: { office: 0.4, school: 0.35, date: 0.7, formal: 0.5, casual: 0.6, nightlife: 0.8, special: 0.5, outdoors: 0.4 },
      perceived: {
        lemon: 0.75,
        pineapple: 0.65,
        birch: 0.6,
        musk: 0.4,
        blackcurrant: 0.3,
        ambergris: 0.3,
        fizzy: 0.3,
        metallic: 0.25,
        oakmoss: 0.15,
        patchouli: 0.15,
      },
      strongestByPhase: {
        opening: ['lemon', 'fizzy', 'pineapple'],
        heart: ['pineapple', 'birch', 'blackcurrant'],
        drydown: ['birch', 'musk', 'ambergris'],
      },
    },
    bottle: {
      body: 'tall',
      width: 0.9,
      height: 1.2,
      depth: 0.8,
      glass: 'smoked',
      glassTint: '#141414',
      liquid: '#2A2A2A',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'silver',
      capWidth: 0.9,
      capHeight: 1.2,
      collar: 'silver',
      label: 'printed',
      labelInk: '#C8C8C8',
    },
    accent: '#4A5058',
  },

  // 45 ------------------------------------------------------------------------------------------
  {
    slug: 'hawas',
    name: 'Hawas for Him',
    brand: 'rasasi',
    concentration: 'edp',
    releaseYear: 2015,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: [],
    style: 'Sweet fruity aquatic',
    summary:
      'Juicy apple and plum over a cool aquatic note with cinnamon and cardamom, drying down to a sweet, ambery musk.',
    bestFor: 'Summer nights, humid weather, casual outings',
    sources: [
      src('identity', 'Rasasi', 0.55, 'Name, year and concentration from editor knowledge; verify on rasasi.com.'),
      src('notes', 'Rasasi', 0.45, 'Pyramid from editor knowledge; "apple" mapped to green-apple, "aquatic notes" to marine-notes.'),
      src('perfumers', 'Rasasi', 0.3, 'No perfumer credit published by the house that could be checked; none listed.'),
      src('price', 'Authorised retailers', 0.4, 'Approximate 2025 US price for 100 ml.'),
    ],
    bottleDescription:
      'A rounded, pebble-like blue glass bottle that deepens in colour toward the base, with a silver cap.',
    editorial:
      'Hawas is a sweet aquatic, which sounds contradictory until you smell it: cool marine notes and apple up front, a candied plum and spice heart, and a long, sweet, musky trail. It projects strongly for the money and gets worn a lot in hot climates at night. The sweetness is heavier than in most aquatics, so it is not one for people who want crisp and dry.',
    notes: {
      top: ['green-apple', 'bergamot', 'lemon', 'cinnamon'],
      heart: ['plum', 'orange-blossom', 'cardamom', 'marine-notes'],
      base: ['ambergris', 'musk', 'patchouli', 'driftwood'],
    },
    priceBand: 'budget',
    priceUsd: 50,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.7, fruity: 0.6, sweet: 0.4, spicy: 0.2 },
      heart: { fruity: 0.5, sweet: 0.5, fresh: 0.5, spicy: 0.3, floral: 0.2 },
      drydown: { sweet: 0.5, warm: 0.4, clean: 0.3, woody: 0.3, fresh: 0.3 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 120 },
    community: {
      tier: 'large',
      rating: 8.0,
      divisiveness: 0.3,
      scent: 8.0,
      performance: 8.7,
      value: 9.2,
      originality: 6.5,
      longevityHrs: 9,
      projection: 4,
      projectionLater: 3,
      seasons: { spring: 0.6, summer: 0.85, autumn: 0.45, winter: 0.15 },
      time: { day: 0.55, night: 0.8 },
      weather: { hot: 0.8, mild: 0.7, cold: 0.15, rain: 0.35, humid: 0.75 },
      occasions: { office: 0.35, school: 0.35, date: 0.7, formal: 0.35, casual: 0.7, nightlife: 0.8, special: 0.45, outdoors: 0.6 },
      perceived: {
        'green-apple': 0.65,
        'marine-notes': 0.6,
        plum: 0.5,
        musk: 0.45,
        ambergris: 0.4,
        cinnamon: 0.3,
        ozonic: 0.3,
        calone: 0.3,
        cardamom: 0.25,
        bergamot: 0.2,
        driftwood: 0.1,
      },
      strongestByPhase: {
        opening: ['green-apple', 'marine-notes', 'bergamot'],
        heart: ['plum', 'cinnamon', 'marine-notes'],
        drydown: ['ambergris', 'musk', 'ozonic'],
      },
    },
    bottle: {
      body: 'pebble',
      width: 1.05,
      height: 1.0,
      depth: 0.8,
      glass: 'tinted',
      glassTint: '#2E5C8A',
      glassGradient: '#1A2E4A',
      liquid: '#4A7FB0',
      fill: 0.85,
      cap: 'dome',
      capMaterial: 'silver',
      capWidth: 0.9,
      capHeight: 0.9,
      collar: 'silver',
      label: 'printed',
      labelInk: '#E3E6EA',
    },
    accent: '#3A6A8C',
  },

  // 46 ------------------------------------------------------------------------------------------
  {
    slug: 'cheirosa-62',
    name: "Cheirosa '62",
    brand: 'sol-de-janeiro',
    concentration: 'body_mist',
    releaseYear: 2018,
    status: 'current',
    marketedFor: 'unspecified',
    perfumers: [],
    style: 'Salted caramel pistachio',
    summary:
      'Toasted pistachio and almond over salted caramel and vanilla, with a soft floral heart. The scent of the brand\'s best-known body cream, as a light mist.',
    bestFor: 'Warm days, after the shower, layering',
    sources: [
      src('identity', 'Sol de Janeiro', 0.4, 'The Brazilian Crush Cheirosa \'62 hair and body mist. The Cheirosa \'62 scent dates from the 2015 Brazilian Bum Bum Cream; the mist launched later, roughly 2018. Year could not be verified.'),
      src('notes', 'Sol de Janeiro', 0.45, 'Pyramid from editor knowledge; "salted caramel" mapped to caramel.'),
      src('perfumers', 'Sol de Janeiro', 0.3, 'No perfumer credit published by the brand that could be checked; none listed.'),
      src('price', 'Authorised retailers', 0.4, 'Approximate 2025 US price for the 240 ml mist.'),
    ],
    bottleDescription:
      'A tall plastic spray bottle in warm pink and coral tones with a white cap and bold printed lettering.',
    editorial:
      'Cheirosa \'62 is the scent of Sol de Janeiro\'s Brazilian Bum Bum Cream, and this mist is the cheapest way to wear it head to toe. It smells of salted caramel and pistachio more than any particular flower, warm and beachy rather than dessert-heavy. As a body mist it fades within a couple of hours, so people reapply or layer it over the cream.',
    notes: {
      top: ['pistachio', 'almond'],
      heart: ['jasmine', 'heliotrope'],
      base: ['caramel', 'vanilla', 'sandalwood'],
    },
    priceBand: 'budget',
    priceUsd: 38,
    sizeMl: 240,
    character: {
      opening: { sweet: 0.6, creamy: 0.5, fruity: 0.1, warm: 0.3 },
      heart: { sweet: 0.6, creamy: 0.6, floral: 0.3, powdery: 0.2, warm: 0.4 },
      drydown: { sweet: 0.6, creamy: 0.5, warm: 0.5, woody: 0.2 },
    },
    phases: { heartAtMin: 10, drydownAtMin: 60 },
    community: {
      tier: 'large',
      rating: 7.8,
      divisiveness: 0.3,
      scent: 8.0,
      performance: 4.5,
      value: 8.2,
      originality: 7.0,
      longevityHrs: 3,
      projection: 3,
      projectionLater: 1,
      seasons: { spring: 0.7, summer: 0.9, autumn: 0.45, winter: 0.25 },
      time: { day: 0.9, night: 0.4 },
      weather: { hot: 0.8, mild: 0.75, cold: 0.2, rain: 0.3, humid: 0.7 },
      occasions: { office: 0.45, school: 0.7, date: 0.45, formal: 0.1, casual: 0.9, nightlife: 0.3, special: 0.15, outdoors: 0.7 },
      perceived: {
        caramel: 0.8,
        pistachio: 0.7,
        vanilla: 0.6,
        almond: 0.4,
        sunscreen: 0.35,
        coconut: 0.25,
        heliotrope: 0.2,
        'sea-salt': 0.2,
        sandalwood: 0.15,
        jasmine: 0.1,
      },
      strongestByPhase: {
        opening: ['pistachio', 'caramel', 'almond'],
        heart: ['caramel', 'pistachio', 'sunscreen'],
        drydown: ['vanilla', 'caramel', 'sunscreen'],
      },
    },
    bottle: {
      body: 'tall',
      width: 0.9,
      height: 1.35,
      depth: 0.8,
      glass: 'tinted',
      glassTint: '#E8A3A0',
      glassGradient: '#E9B98A',
      liquid: '#F2C9A8',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'white',
      capWidth: 0.9,
      capHeight: 1.0,
      collar: 'none',
      label: 'printed',
      labelInk: '#9C3B5A',
    },
    accent: '#D9967A',
  },

  // 47 ------------------------------------------------------------------------------------------
  {
    slug: 'bvlgari-black',
    name: 'Black',
    brand: 'bvlgari',
    concentration: 'edt',
    releaseYear: 1998,
    status: 'discontinued',
    marketedFor: 'shared',
    perfumers: ['annick-menardo'],
    style: 'Smoky tea, rubber and vanilla',
    summary:
      'Smoky black tea and a rubbery, tyre-like note over soft vanilla and amber. Odd on paper, oddly comforting on skin, with a gentle musky finish.',
    bestFor: 'Cool weather, city days, fans of the unusual',
    sources: [
      src('identity', 'Bvlgari', 0.55, 'Name, year and concentration from editor knowledge.'),
      src('status', 'Bvlgari', 0.35, 'Marked discontinued because it is understood to have left the house catalogue and is mostly sold through discounters; the exact year could not be verified, so discontinuedYear is left unset.'),
      src('notes', 'Bvlgari', 0.45, 'Listed as flat; notes from editor knowledge. "Lapsang souchong tea" mapped to lapsang-souchong.'),
      src('perfumers', 'Bvlgari', 0.55, 'Widely reported credit; not re-checked.'),
      src('price', 'Discount retailers', 0.3, 'Approximate street price for 75 ml after discontinuation.'),
    ],
    bottleDescription:
      'A short, wide round bottle wrapped in black rubber like a tyre, with a clear glass centre showing the pale liquid and a flat black cap.',
    editorial:
      'Annick Ménardo\'s Black was a strange idea for a jeweller in 1998: a fragrance about rubber and smoked tea, in a bottle wrapped like a tyre. It works because the vanilla and amber underneath are soft and warm, so the rubber reads as intriguing rather than industrial. It has become hard to find at regular retailers, which has only added to its reputation.',
    notes: {
      flat: ['lapsang-souchong', 'bergamot', 'jasmine', 'rubber', 'leather', 'cedarwood', 'sandalwood', 'vanilla', 'amber', 'musk'],
    },
    priceBand: 'accessible',
    priceUsd: 60,
    sizeMl: 75,
    character: {
      opening: { smoky: 0.6, fresh: 0.3, woody: 0.3, earthy: 0.2 },
      heart: { smoky: 0.5, warm: 0.4, woody: 0.4, floral: 0.2, sweet: 0.3 },
      drydown: { warm: 0.6, sweet: 0.5, creamy: 0.3, smoky: 0.3, woody: 0.3 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 120 },
    community: {
      tier: 'medium',
      rating: 8.2,
      divisiveness: 0.4,
      scent: 8.4,
      performance: 6.5,
      value: 8.0,
      originality: 9.0,
      longevityHrs: 6,
      projection: 2,
      projectionLater: 2,
      seasons: { spring: 0.45, summer: 0.15, autumn: 0.85, winter: 0.75 },
      time: { day: 0.6, night: 0.7 },
      weather: { hot: 0.1, mild: 0.7, cold: 0.8, rain: 0.7, humid: 0.15 },
      occasions: { office: 0.55, school: 0.35, date: 0.55, formal: 0.35, casual: 0.7, nightlife: 0.5, special: 0.4, outdoors: 0.3 },
      perceived: {
        rubber: 0.7,
        'lapsang-souchong': 0.6,
        vanilla: 0.6,
        leather: 0.4,
        amber: 0.35,
        musk: 0.3,
        incense: 0.2,
        cedarwood: 0.2,
        bergamot: 0.15,
        jasmine: 0.08,
      },
      strongestByPhase: {
        opening: ['lapsang-souchong', 'rubber', 'bergamot'],
        heart: ['rubber', 'leather', 'lapsang-souchong'],
        drydown: ['vanilla', 'amber', 'musk'],
      },
    },
    bottle: {
      body: 'cylinder',
      width: 1.4,
      height: 0.7,
      glass: 'smoked',
      glassTint: '#1A1A1A',
      liquid: '#C9B79A',
      fill: 0.85,
      cap: 'disc',
      capMaterial: 'black',
      capWidth: 1.1,
      capHeight: 0.6,
      collar: 'none',
      label: 'printed',
      labelInk: '#B8B8B8',
    },
    accent: '#3E3B38',
  },

  // 48 ------------------------------------------------------------------------------------------
  {
    slug: 'grey-vetiver',
    name: 'Grey Vetiver',
    brand: 'tom-ford',
    concentration: 'edp',
    releaseYear: 2009,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: ['harry-fremont'],
    style: 'Clean citrus vetiver',
    summary:
      'Grapefruit and sage over clean, slightly smoky vetiver, with a hint of iris and spice. Crisp, grey and polished, like a freshly pressed shirt.',
    bestFor: 'Office, warm days, smart-casual wear',
    sources: [
      src('identity', 'Tom Ford Beauty', 0.5, 'Signature collection, 2009, eau de parfum as roster expects; could not confirm whether other concentrations have since replaced it.'),
      src('notes', 'Tom Ford Beauty', 0.45, 'Pyramid from editor knowledge; "sage" mapped to clary-sage, "orris" to iris, "pimento" added as a note.'),
      src('perfumers', 'Tom Ford Beauty', 0.5, 'Widely reported credit; not re-checked.'),
      src('price', 'Authorised retailers', 0.4, 'Approximate 2025 US price for 100 ml.'),
    ],
    bottleDescription:
      'A squared, heavy glass bottle in smoky grey with a silver-toned cap and a metal plate bearing the name.',
    editorial:
      'Grey Vetiver is Tom Ford\'s take on the clean, well-tailored vetiver: citrus and sage up top, a dry iris and spice middle, and a smooth woody base that stays polite. It is less earthy than the classic vetivers and less sweet than most modern woods. A reliable office scent that still feels expensive.',
    notes: {
      top: ['grapefruit', 'orange-blossom', 'clary-sage'],
      heart: ['nutmeg', 'iris', 'pimento'],
      base: ['vetiver', 'oakmoss', 'amberwood'],
    },
    priceBand: 'premium',
    priceUsd: 200,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.7, clean: 0.5, green: 0.4, woody: 0.3 },
      heart: { woody: 0.5, green: 0.4, clean: 0.4, spicy: 0.3, powdery: 0.2 },
      drydown: { woody: 0.7, earthy: 0.4, clean: 0.3, smoky: 0.2, green: 0.3 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 120 },
    community: {
      tier: 'large',
      rating: 8.2,
      divisiveness: 0.2,
      scent: 8.4,
      performance: 7.2,
      value: 6.2,
      originality: 6.8,
      longevityHrs: 7,
      projection: 3,
      projectionLater: 2,
      seasons: { spring: 0.8, summer: 0.65, autumn: 0.65, winter: 0.3 },
      time: { day: 0.95, night: 0.4 },
      weather: { hot: 0.55, mild: 0.9, cold: 0.4, rain: 0.5, humid: 0.45 },
      occasions: { office: 0.95, school: 0.5, date: 0.45, formal: 0.75, casual: 0.65, nightlife: 0.3, special: 0.45, outdoors: 0.45 },
      perceived: {
        vetiver: 0.9,
        grapefruit: 0.65,
        'clary-sage': 0.35,
        soapy: 0.3,
        iris: 0.25,
        mineral: 0.25,
        nutmeg: 0.2,
        oakmoss: 0.2,
        cedarwood: 0.2,
        'orange-blossom': 0.1,
        pimento: 0.1,
      },
      strongestByPhase: {
        opening: ['grapefruit', 'vetiver', 'clary-sage'],
        heart: ['vetiver', 'iris', 'soapy'],
        drydown: ['vetiver', 'mineral', 'cedarwood'],
      },
    },
    bottle: {
      body: 'block',
      width: 1.0,
      height: 1.1,
      depth: 0.7,
      glass: 'smoked',
      glassTint: '#6E6E6E',
      liquid: '#D9CDB0',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'silver',
      capWidth: 1.0,
      capHeight: 0.8,
      collar: 'silver',
      label: 'plate',
      labelColor: '#B9B9B9',
      labelInk: '#2A2A2A',
    },
    accent: '#7D8077',
  },

  // 49 ------------------------------------------------------------------------------------------
  {
    slug: 'wood-sage-sea-salt',
    name: 'Wood Sage & Sea Salt',
    brand: 'jo-malone',
    concentration: 'cologne',
    releaseYear: 2014,
    status: 'current',
    marketedFor: 'shared',
    perfumers: ['christine-nagel'],
    style: 'Salty woody aromatic',
    summary:
      'Sea salt and sage over a dry, mineral woodiness, with a soft musky ambrette glow. Like a windy beach walk: light and a little savoury.',
    bestFor: 'Spring and summer days, weekends, the office',
    sources: [
      src('identity', 'Jo Malone London', 0.6, 'Name, year and concentration (Cologne) from editor knowledge; verify on jomalone.com.'),
      src('notes', 'Jo Malone London', 0.5, 'The house lists three key notes (ambrette seeds, sea salt, sage); "sage" mapped to clary-sage. Listed flat.'),
      src('perfumers', 'Jo Malone London', 0.55, 'Widely reported credit; not re-checked.'),
      src('price', 'Authorised retailers', 0.4, 'Approximate 2025 US price for 100 ml.'),
    ],
    bottleDescription:
      'A squared clear glass bottle with a black cap and a cream paper label with black lettering.',
    editorial:
      'Wood Sage & Sea Salt is one of Jo Malone London\'s best-known modern colognes. Christine Nagel built it from just a few ideas: ambrette for a soft musky warmth, a sea-salt accord and herbal sage. It is airy and fairly short-lived, which suits its laid-back mood but means reapplying by mid-afternoon.',
    notes: { flat: ['ambrette', 'sea-salt', 'clary-sage'] },
    priceBand: 'premium',
    priceUsd: 170,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.7, clean: 0.4, green: 0.3, earthy: 0.1 },
      heart: { fresh: 0.5, woody: 0.4, green: 0.3, clean: 0.4, earthy: 0.2 },
      drydown: { woody: 0.5, clean: 0.4, earthy: 0.3, warm: 0.2 },
    },
    phases: { heartAtMin: 10, drydownAtMin: 60 },
    community: {
      tier: 'large',
      rating: 7.9,
      divisiveness: 0.3,
      scent: 8.2,
      performance: 5.0,
      value: 6.0,
      originality: 7.6,
      longevityHrs: 4,
      projection: 2,
      projectionLater: 1,
      seasons: { spring: 0.85, summer: 0.85, autumn: 0.45, winter: 0.15 },
      time: { day: 0.95, night: 0.3 },
      weather: { hot: 0.75, mild: 0.85, cold: 0.2, rain: 0.5, humid: 0.6 },
      occasions: { office: 0.8, school: 0.6, date: 0.35, formal: 0.3, casual: 0.85, nightlife: 0.15, special: 0.2, outdoors: 0.75 },
      perceived: {
        'sea-salt': 0.8,
        'clary-sage': 0.55,
        mineral: 0.5,
        ambrette: 0.3,
        grapefruit: 0.3,
        musk: 0.3,
        seaweed: 0.25,
        ozonic: 0.2,
      },
      strongestByPhase: {
        opening: ['sea-salt', 'grapefruit', 'mineral'],
        heart: ['sea-salt', 'clary-sage', 'mineral'],
        drydown: ['ambrette', 'musk', 'clary-sage'],
      },
    },
    bottle: {
      body: 'tall',
      width: 1.0,
      height: 1.0,
      depth: 0.95,
      glass: 'clear',
      liquid: '#EDE8D8',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'black',
      capWidth: 1.0,
      capHeight: 0.7,
      collar: 'none',
      label: 'paper',
      labelColor: '#F2EEE4',
      labelInk: '#1A1A1A',
    },
    accent: '#8A9A94',
  },

  // 50 ------------------------------------------------------------------------------------------
  {
    slug: 'paradigme',
    name: 'Paradigme',
    brand: 'prada',
    concentration: 'edp',
    releaseYear: 2025,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: [],
    style: 'Woody amber',
    summary:
      'Bright bergamot and rosy geranium over a warm benzoin and amber base. Clean and modern at first, softer and more resinous as it wears.',
    bestFor: 'Everyday wear, evenings, cooler months',
    sources: [
      src('identity', 'Prada Beauty', 0.45, 'Chosen as the 2025 major-house launch from editor knowledge of Prada\'s 2025 men\'s release. Could NOT be verified online in this session; confirm name, year and concentration before publishing.'),
      src('notes', 'Prada Beauty', 0.3, 'Key notes from editor recollection of launch coverage only; treat as provisional until checked against the house page.'),
      src('perfumers', 'Prada Beauty', 0.2, 'Perfumer credit not verified; none listed.'),
      src('price', 'Authorised retailers', 0.3, 'Estimated US price for 100 ml.'),
    ],
    bottleDescription:
      'A squared clear glass bottle with a dark cap and the Prada triangle logo on the front.',
    editorial:
      'Paradigme is Prada\'s 2025 men\'s launch. Built around bergamot and geranium over a resinous benzoin and amber base, it sits in the polished, easy-to-wear woody-amber lane that most big launches aim for. It is too new for a settled reputation, so treat the community figures here as a placeholder.',
    notes: { flat: ['bergamot', 'geranium', 'benzoin', 'amber'] },
    priceBand: 'premium',
    priceUsd: 160,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.6, green: 0.2, floral: 0.3, spicy: 0.2 },
      heart: { floral: 0.3, warm: 0.4, woody: 0.4, sweet: 0.3 },
      drydown: { warm: 0.6, sweet: 0.4, woody: 0.4, creamy: 0.3 },
    },
    phases: { heartAtMin: 20, drydownAtMin: 120 },
    community: {
      tier: 'new',
      rating: 7.6,
      divisiveness: 0.35,
      scent: 7.7,
      performance: 7.4,
      value: 6.5,
      originality: 6.0,
      longevityHrs: 8,
      projection: 3,
      projectionLater: 2,
      seasons: { spring: 0.6, summer: 0.35, autumn: 0.75, winter: 0.6 },
      time: { day: 0.7, night: 0.7 },
      weather: { hot: 0.3, mild: 0.8, cold: 0.6, rain: 0.5, humid: 0.3 },
      occasions: { office: 0.65, school: 0.45, date: 0.6, formal: 0.55, casual: 0.6, nightlife: 0.5, special: 0.45, outdoors: 0.35 },
      perceived: {
        bergamot: 0.6,
        amber: 0.55,
        benzoin: 0.45,
        geranium: 0.4,
        ambroxan: 0.3,
        musk: 0.3,
        vanilla: 0.25,
        soapy: 0.15,
      },
      strongestByPhase: {
        opening: ['bergamot', 'geranium'],
        heart: ['geranium', 'amber', 'ambroxan'],
        drydown: ['amber', 'benzoin', 'musk'],
      },
    },
    bottle: {
      body: 'block',
      width: 0.95,
      height: 1.1,
      depth: 0.7,
      glass: 'clear',
      liquid: '#E8D7B0',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'black',
      capWidth: 0.9,
      capHeight: 0.8,
      collar: 'black',
      label: 'printed',
      labelInk: '#1A1A1A',
    },
    accent: '#6E6658',
  },
];
