import type { SeedFragrance } from '../types';

/**
 * Real catalogue, Group A (roster 1-17).
 *
 * RESEARCH STATUS: during this research pass every house site, authorised retailer, press site and
 * Wikipedia/Wikidata page was blocked by the research environment's network policy, and no web
 * search was available. Facts below come from widely published house information as remembered by
 * the editor, NOT from a page opened this session. Every source is therefore typed 'editorial',
 * has url null and confidence <= 0.7, and should be re-verified against the house page named in
 * `publisher`. Fragrantica, Parfumo, Basenotes and derived datasets were not used.
 *
 * Community, character and phases are demo estimates (flagged as demo in the UI).
 */

type Source = NonNullable<SeedFragrance['sources']>[number];

function unverified(field: Source['field'], publisher: string, confidence: number, note: string): Source {
  return { field, type: 'editorial', publisher, url: null, confidence, note: note.charAt(0).toUpperCase() + note.slice(1) };
}

export const FRAGRANCES_A: SeedFragrance[] = [
  // 1 ------------------------------------------------------------------ Dior Sauvage EDT (flagship)
  {
    slug: 'dior-sauvage',
    name: 'Sauvage',
    brand: 'dior',
    concentration: 'edt',
    releaseYear: 2015,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: ['francois-demachy'],
    style: 'Fresh spicy ambroxan',
    summary:
      'A blast of peppery bergamot that turns into a big, clean, slightly salty ambroxan glow. Bright, loud and very easy to like.',
    bestFor: 'Everyday wear, casual nights out',
    sources: [
      unverified('identity', 'Dior', 0.7, 'launch year, perfumer and EDT concentration are widely published by Dior.'),
      unverified('notes', 'Dior', 0.55, 'Dior headlines Calabrian bergamot, Sichuan pepper and Ambroxan; the fuller pyramid is the commonly circulated retail breakdown and was not confirmed on a house page.'),
      unverified('perfumers', 'Dior', 0.7, 'François Demachy is the credited perfumer in Dior press coverage.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US price for 100 ml.'),
    ],
    bottleDescription:
      'A heavy rectangular glass bottle that shades from clear smoky blue at the base to near black at the shoulders, with a chunky dark magnetic cap and the name printed in silver.',
    editorial:
      'You have almost certainly smelled Sauvage on a stranger this week. Demachy pairs a sharp, peppery bergamot with a heavy dose of ambroxan, and the result is clean, bright and loud enough to fill a lift. It has been one of the best-selling men\'s fragrances in the world for years, which is both its strength and its problem: it smells good and it smells everywhere.',
    notes: {
      top: ['bergamot', 'black-pepper'],
      heart: ['sichuan-pepper', 'lavender', 'pink-pepper', 'vetiver', 'patchouli', 'geranium', 'elemi'],
      base: ['ambroxan', 'cedarwood', 'labdanum'],
    },
    priceBand: 'premium',
    priceUsd: 135,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.9, spicy: 0.6, clean: 0.5, woody: 0.2 },
      heart: { fresh: 0.6, spicy: 0.5, clean: 0.6, woody: 0.4, warm: 0.3 },
      drydown: { clean: 0.6, woody: 0.5, warm: 0.5, fresh: 0.3 },
    },
    phases: { heartAtMin: 20, drydownAtMin: 150 },
    community: {
      tier: 'huge',
      rating: 7.6,
      divisiveness: 0.55,
      scent: 7.5,
      performance: 8.6,
      value: 7.4,
      originality: 5.2,
      longevityHrs: 8,
      projection: 4.3,
      projectionLater: 3.2,
      seasons: { spring: 0.85, summer: 0.7, autumn: 0.65, winter: 0.45 },
      time: { day: 0.85, night: 0.6 },
      weather: { hot: 0.6, mild: 0.9, cold: 0.5, rain: 0.45, humid: 0.45 },
      occasions: { office: 0.55, school: 0.6, date: 0.6, formal: 0.35, casual: 0.9, nightlife: 0.65, special: 0.35, outdoors: 0.6 },
      perceived: {
        ambroxan: 0.9,
        bergamot: 0.75,
        'black-pepper': 0.55,
        'sichuan-pepper': 0.35,
        lavender: 0.3,
        'sea-salt': 0.3,
        fizzy: 0.25,
        cedarwood: 0.25,
        labdanum: 0.1,
        elemi: 0.08,
      },
      strongestByPhase: {
        opening: ['bergamot', 'black-pepper', 'fizzy'],
        heart: ['ambroxan', 'sichuan-pepper', 'lavender'],
        drydown: ['ambroxan', 'sea-salt', 'cedarwood'],
      },
    },
    bottle: {
      body: 'block',
      width: 1.1,
      height: 1.4,
      depth: 0.6,
      glass: 'tinted',
      glassTint: '#5E7590',
      glassGradient: '#12161D',
      liquid: '#C3CEDA',
      fill: 0.82,
      cap: 'cube',
      capMaterial: 'black',
      capColor: '#1A202B',
      capWidth: 1.4,
      capHeight: 1.25,
      collar: 'none',
      label: 'printed',
      labelInk: '#C9CED6',
    },
    accent: '#3D5573',
    has3d: true,
  },

  // 2 ------------------------------------------------------------------ Bleu de Chanel EDP
  {
    slug: 'bleu-de-chanel-edp',
    name: 'Bleu de Chanel',
    brand: 'chanel',
    concentration: 'edp',
    releaseYear: 2014,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: ['jacques-polge'],
    style: 'Woody citrus incense',
    summary:
      'Grapefruit and a cool mint-pepper lift up front, then smooth cedar and sandalwood with a soft thread of incense. Clean, warm and quietly expensive.',
    bestFor: 'Office days, dinners, any time',
    sources: [
      unverified('identity', 'Chanel', 0.7, 'the EDP followed the 2010 EDT in 2014; widely published.'),
      unverified('notes', 'Chanel', 0.45, 'Chanel describes the EDP around citrus, cedar, sandalwood and an ambery woody trail without a full pyramid; listed as flat. Individual notes beyond citrus, cedar and sandalwood are lower confidence.'),
      unverified('perfumers', 'Chanel', 0.6, 'credited to Jacques Polge in press coverage of the launch; some sources also associate Olivier Polge with later Bleu versions.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US price for 100 ml.'),
    ],
    bottleDescription:
      'A thick rectangular bottle in deep navy glass that looks almost black, with a matching dark magnetic cap and the name printed in silver.',
    editorial:
      'Bleu de Chanel is the safe answer to "what should I wear to the interview", and it earns that by being genuinely well made. The EDP trims the EDT\'s sharper citrus edge and leans into sandalwood and a faint incense warmth. It is not daring. It is very, very good at being liked.',
    notes: {
      flat: ['grapefruit', 'lemon', 'mint', 'pink-pepper', 'ginger', 'jasmine', 'incense', 'cedarwood', 'sandalwood', 'labdanum', 'amber'],
    },
    priceBand: 'premium',
    priceUsd: 175,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.8, spicy: 0.3, clean: 0.4, woody: 0.3 },
      heart: { woody: 0.6, fresh: 0.4, clean: 0.4, warm: 0.3, spicy: 0.2 },
      drydown: { woody: 0.8, warm: 0.5, creamy: 0.3, smoky: 0.2 },
    },
    phases: { heartAtMin: 20, drydownAtMin: 180 },
    community: {
      tier: 'huge',
      rating: 8.1,
      divisiveness: 0.3,
      scent: 8.2,
      performance: 7.6,
      value: 6.8,
      originality: 5.6,
      longevityHrs: 8,
      projection: 3.4,
      projectionLater: 2.6,
      seasons: { spring: 0.85, summer: 0.6, autumn: 0.85, winter: 0.65 },
      time: { day: 0.85, night: 0.7 },
      weather: { hot: 0.5, mild: 0.95, cold: 0.65, rain: 0.55, humid: 0.45 },
      occasions: { office: 0.9, school: 0.5, date: 0.75, formal: 0.8, casual: 0.75, nightlife: 0.55, special: 0.6, outdoors: 0.45 },
      perceived: {
        grapefruit: 0.7,
        cedarwood: 0.6,
        sandalwood: 0.55,
        incense: 0.4,
        mint: 0.25,
        amber: 0.35,
        'iso-e-super': 0.25,
        ginger: 0.2,
        'pink-pepper': 0.15,
        laundry: 0.15,
      },
      strongestByPhase: {
        opening: ['grapefruit', 'mint', 'ginger'],
        heart: ['cedarwood', 'incense'],
        drydown: ['sandalwood', 'amber', 'iso-e-super'],
      },
    },
    bottle: {
      body: 'block',
      width: 1.15,
      height: 1.35,
      depth: 0.6,
      glass: 'tinted',
      glassTint: '#1B2740',
      liquid: '#2A3A5A',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'black',
      capColor: '#151A24',
      capWidth: 1.5,
      capHeight: 1.0,
      collar: 'none',
      label: 'printed',
      labelInk: '#C7CBD2',
    },
    accent: '#2B3A55',
  },

  // 3 ------------------------------------------------------------------ Acqua di Giò pour Homme EDT
  {
    slug: 'acqua-di-gio',
    name: 'Acqua di Giò',
    brand: 'giorgio-armani',
    concentration: 'edt',
    releaseYear: 1996,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: ['alberto-morillas'],
    style: 'Aquatic citrus',
    summary:
      'Squeezed lime and bergamot over a cool, watery, slightly salty sea note, settling into soft musk and a little patchouli. Smells like a clean shirt by the sea.',
    bestFor: 'Hot days, gym bag, office in summer',
    sources: [
      unverified('identity', 'Giorgio Armani Beauty', 0.7, 'the men\'s EDT (Acqua di Giò pour Homme), launched 1996; widely published.'),
      unverified('notes', 'Giorgio Armani Beauty', 0.5, 'Armani\'s current pages headline marine notes, citrus, rosemary and patchouli; the fuller pyramid is the long-circulated launch breakdown and is lower confidence.'),
      unverified('perfumers', 'Giorgio Armani Beauty / Firmenich', 0.7, 'Alberto Morillas is the widely credited perfumer.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US price for 100 ml.'),
    ],
    bottleDescription:
      'A frosted glass bottle with softly rounded edges and a slim cap, the pale aqua-green juice glowing through the frosting.',
    editorial:
      'Acqua di Giò did for 1990s bathrooms what Sauvage did for the 2010s: it became the default. Morillas built it on bright citrus and a calone-style sea note that reads as clean water rather than fish market, then softened it with musk. It feels a bit dated in the opening now, but the drydown is still a pleasant, wearable skin scent.',
    notes: {
      top: ['bergamot', 'lime', 'lemon', 'mandarin', 'neroli'],
      heart: ['marine-notes', 'calone', 'jasmine', 'rosemary'],
      base: ['patchouli', 'cedarwood', 'musk', 'oakmoss'],
    },
    priceBand: 'premium',
    priceUsd: 120,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.9, clean: 0.5, fruity: 0.2 },
      heart: { fresh: 0.7, clean: 0.6, floral: 0.2, green: 0.2 },
      drydown: { clean: 0.6, woody: 0.4, earthy: 0.2, fresh: 0.3 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 120 },
    community: {
      tier: 'huge',
      rating: 7.5,
      divisiveness: 0.35,
      scent: 7.6,
      performance: 6.4,
      value: 7.4,
      originality: 6.5,
      longevityHrs: 5,
      projection: 3.2,
      projectionLater: 2,
      seasons: { spring: 0.85, summer: 0.95, autumn: 0.35, winter: 0.15 },
      time: { day: 0.95, night: 0.3 },
      weather: { hot: 0.95, mild: 0.75, cold: 0.15, rain: 0.35, humid: 0.85 },
      occasions: { office: 0.75, school: 0.7, date: 0.35, formal: 0.3, casual: 0.9, nightlife: 0.2, special: 0.2, outdoors: 0.8 },
      perceived: {
        'marine-notes': 0.8,
        calone: 0.5,
        bergamot: 0.6,
        lime: 0.4,
        'sea-salt': 0.35,
        rosemary: 0.3,
        musk: 0.4,
        patchouli: 0.2,
        soapy: 0.25,
        oakmoss: 0.05,
      },
      strongestByPhase: {
        opening: ['bergamot', 'lime', 'marine-notes'],
        heart: ['marine-notes', 'calone', 'rosemary'],
        drydown: ['musk', 'patchouli', 'sea-salt'],
      },
    },
    bottle: {
      body: 'flask',
      width: 1.0,
      height: 1.15,
      depth: 1.4,
      glass: 'frosted',
      glassTint: '#DCE5E4',
      liquid: '#BCD6CF',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'silver',
      capWidth: 0.85,
      capHeight: 0.9,
      collar: 'none',
      label: 'printed',
      labelInk: '#3A4A4C',
    },
    accent: '#6F8F95',
  },

  // 4 ------------------------------------------------------------------ YSL Y EDP
  {
    slug: 'ysl-y-edp',
    name: 'Y',
    brand: 'yves-saint-laurent',
    concentration: 'edp',
    releaseYear: 2018,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: ['dominique-ropion'],
    style: 'Sweet fresh aromatic woods',
    summary:
      'Crisp apple and ginger over a sage-and-juniper heart, drying down to sweet tonka and a big dry ambery wood. Fresh on top, warm and dense underneath.',
    bestFor: 'Evenings out, cooler months, dates',
    sources: [
      unverified('identity', 'YSL Beauty', 0.7, 'EDP launched 2018, a year after the 2017 EDT; widely published.'),
      unverified('notes', 'YSL Beauty', 0.55, 'YSL headlines apple, ginger, sage and ambery woods; the full pyramid is the widely circulated retail breakdown. "Amberwood" mapped to our amberwood accord.'),
      unverified('perfumers', 'YSL Beauty', 0.65, 'Dominique Ropion is the widely credited perfumer of Y EDT and EDP.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US price for 100 ml.'),
    ],
    bottleDescription:
      'A tall rectangular bottle in deep blue glass with a large metal Y plaque set into the front and a dark cap.',
    editorial:
      'Y EDP is what happens when a fresh blue fragrance spends more time in the gym and the patisserie. The apple-ginger opening is bright and almost sparkling, but the real story is the drydown: tonka, sage and a very dry, very persistent woody amber. It is crowd-tested rather than adventurous, and it lasts.',
    notes: {
      top: ['green-apple', 'ginger', 'bergamot'],
      heart: ['clary-sage', 'juniper-berry', 'geranium'],
      base: ['amberwood', 'tonka-bean', 'cedarwood', 'vetiver', 'frankincense'],
    },
    priceBand: 'premium',
    priceUsd: 165,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.8, fruity: 0.5, spicy: 0.4, sweet: 0.2 },
      heart: { fresh: 0.5, green: 0.3, woody: 0.4, sweet: 0.3, spicy: 0.2 },
      drydown: { woody: 0.7, warm: 0.6, sweet: 0.5, clean: 0.2 },
    },
    phases: { heartAtMin: 20, drydownAtMin: 150 },
    community: {
      tier: 'large',
      rating: 7.9,
      divisiveness: 0.35,
      scent: 7.9,
      performance: 8.2,
      value: 7.0,
      originality: 5.5,
      longevityHrs: 9,
      projection: 3.9,
      projectionLater: 3,
      seasons: { spring: 0.65, summer: 0.35, autumn: 0.85, winter: 0.75 },
      time: { day: 0.65, night: 0.85 },
      weather: { hot: 0.3, mild: 0.85, cold: 0.8, rain: 0.55, humid: 0.3 },
      occasions: { office: 0.55, school: 0.5, date: 0.85, formal: 0.55, casual: 0.75, nightlife: 0.85, special: 0.55, outdoors: 0.35 },
      perceived: {
        'green-apple': 0.65,
        ginger: 0.4,
        'clary-sage': 0.5,
        'tonka-bean': 0.55,
        amberwood: 0.6,
        ambroxan: 0.35,
        lavender: 0.15,
        frankincense: 0.1,
        'juniper-berry': 0.08,
      },
      strongestByPhase: {
        opening: ['green-apple', 'ginger'],
        heart: ['clary-sage', 'tonka-bean'],
        drydown: ['amberwood', 'tonka-bean', 'ambroxan'],
      },
    },
    bottle: {
      body: 'tall',
      width: 1.3,
      height: 1.05,
      depth: 1.0,
      glass: 'tinted',
      glassTint: '#22304D',
      glassGradient: '#151C2E',
      liquid: '#3B4C6E',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'black',
      capColor: '#161A24',
      capWidth: 1.1,
      capHeight: 0.9,
      collar: 'silver',
      label: 'plate',
      labelColor: '#BFC3C9',
      labelInk: '#1D2433',
    },
    accent: '#4A5878',
  },

  // 5 ------------------------------------------------------------------ Terre d'Hermès EDT
  {
    slug: 'terre-d-hermes',
    name: 'Terre d\'Hermès',
    brand: 'hermes',
    concentration: 'edt',
    releaseYear: 2006,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: ['jean-claude-ellena'],
    style: 'Mineral citrus woods',
    summary:
      'Bitter orange peel and pepper over something dry and stony, like struck flint, then vetiver and cedar. Earthy, orange-tinted and quietly confident.',
    bestFor: 'Office, autumn days, smart-casual',
    sources: [
      unverified('identity', 'Hermès', 0.7, 'launched 2006 as Ellena\'s first masculine for the house; widely published.'),
      unverified('notes', 'Hermès', 0.55, 'Hermès describes orange, grapefruit, flint (mapped to our mineral descriptor), pepper, pelargonium (mapped to geranium), vetiver, cedar, patchouli and benzoin. Phase placement is ours.'),
      unverified('perfumers', 'Hermès', 0.7, 'Jean-Claude Ellena, then Hermès in-house perfumer.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US price for 100 ml.'),
    ],
    bottleDescription:
      'A heavy, squared-off clear glass bottle showing amber-orange juice, with a squat cap and the name in simple printed type.',
    editorial:
      'Terre is Ellena at his most persuasive: very few materials, each one doing a lot. The orange opening is dry and peel-bitter rather than juicy, and the flinty, peppery heart gives it the feel of sun-baked earth. It became a modern classic because it smells grown-up without smelling old.',
    notes: {
      top: ['sweet-orange', 'grapefruit'],
      heart: ['black-pepper', 'geranium', 'mineral'],
      base: ['vetiver', 'cedarwood', 'patchouli', 'benzoin'],
    },
    priceBand: 'premium',
    priceUsd: 135,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.7, fruity: 0.4, spicy: 0.4, earthy: 0.2 },
      heart: { spicy: 0.4, earthy: 0.5, woody: 0.5, fresh: 0.3, green: 0.2 },
      drydown: { woody: 0.8, earthy: 0.6, warm: 0.3, smoky: 0.1 },
    },
    phases: { heartAtMin: 25, drydownAtMin: 180 },
    community: {
      tier: 'large',
      rating: 8.2,
      divisiveness: 0.3,
      scent: 8.3,
      performance: 7.2,
      value: 7.2,
      originality: 7.6,
      longevityHrs: 7,
      projection: 3,
      projectionLater: 2.3,
      seasons: { spring: 0.75, summer: 0.55, autumn: 0.9, winter: 0.55 },
      time: { day: 0.9, night: 0.5 },
      weather: { hot: 0.45, mild: 0.95, cold: 0.6, rain: 0.6, humid: 0.4 },
      occasions: { office: 0.9, school: 0.4, date: 0.55, formal: 0.65, casual: 0.75, nightlife: 0.35, special: 0.45, outdoors: 0.55 },
      perceived: {
        'sweet-orange': 0.75,
        grapefruit: 0.35,
        mineral: 0.6,
        vetiver: 0.65,
        'black-pepper': 0.4,
        cedarwood: 0.4,
        'iso-e-super': 0.3,
        geranium: 0.2,
        benzoin: 0.1,
      },
      strongestByPhase: {
        opening: ['sweet-orange', 'grapefruit', 'black-pepper'],
        heart: ['mineral', 'sweet-orange', 'vetiver'],
        drydown: ['vetiver', 'cedarwood', 'iso-e-super'],
      },
    },
    bottle: {
      body: 'block',
      width: 1.05,
      height: 1.3,
      depth: 0.7,
      glass: 'clear',
      liquid: '#C7782E',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'silver',
      capWidth: 1.2,
      capHeight: 0.7,
      collar: 'none',
      label: 'printed',
      labelInk: '#3B2A1E',
    },
    accent: '#A0623A',
  },

  // 6 ------------------------------------------------------------------ Versace Eros EDT
  {
    slug: 'versace-eros',
    name: 'Eros',
    brand: 'versace',
    concentration: 'edt',
    releaseYear: 2012,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: ['aurelien-guichard'],
    style: 'Sweet minty vanilla',
    summary:
      'Cold mint and green apple hit first, then a sweet, creamy vanilla-tonka base that hangs around all night. Loud, sugary and built for a crowd.',
    bestFor: 'Clubs, parties, cold nights',
    sources: [
      unverified('identity', 'Versace', 0.7, 'launched 2012; widely published.'),
      unverified('notes', 'Versace', 0.6, 'Versace publishes a pyramid of mint, green apple and Italian lemon; tonka, ambroxan and geranium; Madagascar vanilla, Virginia and Atlas cedar, vetiver and oakmoss. Not re-checked on the page.'),
      unverified('perfumers', 'Versace', 0.65, 'Aurélien Guichard is the widely credited perfumer.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US price for 100 ml.'),
    ],
    bottleDescription:
      'A rectangular bottle in turquoise glass, ribbed with a Greek key pattern, with a gold Medusa head on the front and a matching turquoise cap.',
    editorial:
      'Eros is the mint-chocolate-chip ice cream of men\'s fragrance: obvious, sweet and hard to dislike once it is in front of you. The mint and apple opening is genuinely fun, and the vanilla base projects like a loudspeaker. Go easy on the trigger; two sprays is plenty.',
    notes: {
      top: ['mint', 'green-apple', 'lemon'],
      heart: ['tonka-bean', 'ambroxan', 'geranium'],
      base: ['vanilla', 'cedarwood', 'vetiver', 'oakmoss'],
    },
    priceBand: 'premium',
    priceUsd: 110,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.8, green: 0.3, fruity: 0.5, sweet: 0.4 },
      heart: { sweet: 0.7, fresh: 0.4, warm: 0.4, creamy: 0.3 },
      drydown: { sweet: 0.8, warm: 0.6, creamy: 0.5, woody: 0.3 },
    },
    phases: { heartAtMin: 20, drydownAtMin: 150 },
    community: {
      tier: 'huge',
      rating: 7.6,
      divisiveness: 0.5,
      scent: 7.6,
      performance: 8.5,
      value: 8.2,
      originality: 6.3,
      longevityHrs: 9,
      projection: 4.4,
      projectionLater: 3.4,
      seasons: { spring: 0.5, summer: 0.25, autumn: 0.8, winter: 0.85 },
      time: { day: 0.45, night: 0.95 },
      weather: { hot: 0.2, mild: 0.7, cold: 0.9, rain: 0.5, humid: 0.2 },
      occasions: { office: 0.25, school: 0.45, date: 0.8, formal: 0.3, casual: 0.6, nightlife: 0.95, special: 0.5, outdoors: 0.25 },
      perceived: {
        mint: 0.85,
        'green-apple': 0.6,
        vanilla: 0.8,
        'tonka-bean': 0.6,
        lemon: 0.25,
        ambroxan: 0.3,
        caramel: 0.25,
        geranium: 0.15,
        oakmoss: 0.05,
      },
      strongestByPhase: {
        opening: ['mint', 'green-apple', 'lemon'],
        heart: ['mint', 'tonka-bean', 'vanilla'],
        drydown: ['vanilla', 'tonka-bean', 'caramel'],
      },
    },
    bottle: {
      body: 'block',
      width: 1.05,
      height: 1.3,
      depth: 0.6,
      glass: 'tinted',
      glassTint: '#3E9C99',
      liquid: '#8CC9C2',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'resin',
      capColor: '#2F8C88',
      capWidth: 1.2,
      capHeight: 0.85,
      collar: 'gold',
      label: 'plate',
      labelColor: '#C8A35A',
      labelInk: '#3A2E14',
    },
    accent: '#3F8A86',
  },

  // 7 ------------------------------------------------------------------ Jean Paul Gaultier Le Male EDT
  {
    slug: 'le-male',
    name: 'Le Male',
    brand: 'jean-paul-gaultier',
    concentration: 'edt',
    releaseYear: 1995,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: ['francis-kurkdjian'],
    style: 'Lavender vanilla fougère',
    summary:
      'Cool mint and lavender up top, a warm hint of cinnamon and cumin, then a soft vanilla-tonka base. Barbershop meets baby powder, in a good way.',
    bestFor: 'Cool evenings, nights out, nostalgia',
    sources: [
      unverified('identity', 'Jean Paul Gaultier', 0.7, 'launched 1995; widely published.'),
      unverified('notes', 'Jean Paul Gaultier', 0.55, 'the house headlines lavender, mint and vanilla; the full pyramid (with artemisia, cardamom, cinnamon, cumin, orange blossom, tonka and woods) is the widely circulated breakdown and is lower confidence.'),
      unverified('perfumers', 'press coverage', 0.7, 'Francis Kurkdjian is widely credited as the perfumer, one of his first major launches.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US price for 125 ml.'),
    ],
    bottleDescription:
      'A glass bottle moulded as a male torso, frosted and painted with blue and white sailor stripes, with a small silver cap at the neck; it ships in a metal tin.',
    editorial:
      'Le Male took the old barbershop fougère, added a big spoonful of vanilla and a wink, and somehow made it the smell of a generation of nightclubs. Under the sweetness there is still a proper lavender-mint structure, which is why it has aged better than most of its peers. It reads warmer and softer than modern fresh masculines.',
    notes: {
      top: ['lavender', 'mint', 'cardamom', 'bergamot', 'artemisia'],
      heart: ['cinnamon', 'orange-blossom', 'cumin'],
      base: ['vanilla', 'tonka-bean', 'amber', 'sandalwood', 'cedarwood'],
    },
    priceBand: 'premium',
    priceUsd: 125,
    sizeMl: 125,
    character: {
      opening: { fresh: 0.6, clean: 0.3, spicy: 0.3, floral: 0.2 },
      heart: { sweet: 0.5, spicy: 0.4, powdery: 0.3, floral: 0.2, warm: 0.3 },
      drydown: { sweet: 0.7, warm: 0.6, powdery: 0.4, creamy: 0.3, woody: 0.2 },
    },
    phases: { heartAtMin: 20, drydownAtMin: 150 },
    community: {
      tier: 'huge',
      rating: 7.8,
      divisiveness: 0.4,
      scent: 7.9,
      performance: 7.7,
      value: 7.8,
      originality: 7.5,
      longevityHrs: 8,
      projection: 3.8,
      projectionLater: 2.9,
      seasons: { spring: 0.5, summer: 0.2, autumn: 0.85, winter: 0.85 },
      time: { day: 0.5, night: 0.9 },
      weather: { hot: 0.15, mild: 0.7, cold: 0.9, rain: 0.55, humid: 0.2 },
      occasions: { office: 0.35, school: 0.4, date: 0.85, formal: 0.4, casual: 0.65, nightlife: 0.9, special: 0.5, outdoors: 0.25 },
      perceived: {
        lavender: 0.8,
        mint: 0.6,
        vanilla: 0.8,
        'tonka-bean': 0.4,
        cinnamon: 0.3,
        powdery: 0.45,
        soapy: 0.25,
        cardamom: 0.2,
        cumin: 0.1,
        'orange-blossom': 0.15,
      },
      strongestByPhase: {
        opening: ['mint', 'lavender', 'cardamom'],
        heart: ['lavender', 'cinnamon', 'powdery'],
        drydown: ['vanilla', 'tonka-bean', 'powdery'],
      },
    },
    bottle: {
      body: 'pebble',
      width: 0.95,
      height: 1.5,
      depth: 1.0,
      glass: 'frosted',
      glassTint: '#C9D8E6',
      liquid: '#9DBAD3',
      fill: 0.9,
      cap: 'cylinder',
      capMaterial: 'silver',
      capWidth: 0.7,
      capHeight: 0.6,
      collar: 'none',
      label: 'none',
    },
    accent: '#5A7896',
  },

  // 8 ------------------------------------------------------------------ Rabanne 1 Million EDT
  {
    slug: 'one-million',
    name: '1 Million',
    brand: 'rabanne',
    concentration: 'edt',
    releaseYear: 2008,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: ['christophe-raynaud', 'olivier-pescheux', 'michel-girard'],
    style: 'Spicy amber leather',
    summary:
      'Juicy mandarin and a flash of mint, then cinnamon and rose over a sticky, sweet amber-leather base. Warm, dense and unmistakable across a room.',
    bestFor: 'Winter nights, parties',
    sources: [
      unverified('identity', 'Rabanne', 0.7, 'launched 2008 under the Paco Rabanne name; the house is now Rabanne. Widely published.'),
      unverified('notes', 'Rabanne', 0.6, 'house pyramid as widely published: blood mandarin, grapefruit, peppermint; rose, cinnamon, spice; blond leather, white wood, amber, patchouli. "Blond leather" mapped to leather, "white wood" to our white-woods accord.'),
      unverified('perfumers', 'press coverage', 0.65, 'credited to Christophe Raynaud, Olivier Pescheux and Michel Girard.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US price for 100 ml.'),
    ],
    bottleDescription:
      'A gold-coated glass bottle shaped like a gold ingot, with the name stamped on the front and a gold block cap that flips open.',
    editorial:
      '1 Million is a gold bar you can spray, and it smells about as subtle as that sounds. The cinnamon-amber-leather base is sweet and syrupy, with a slightly boozy edge that people either adore or find cloying. In cold weather and in small doses it is a lot of fun; in an office in July it is a hostile act.',
    notes: {
      top: ['blood-orange', 'grapefruit', 'mint'],
      heart: ['rose', 'cinnamon'],
      base: ['leather', 'white-woods', 'amber', 'patchouli'],
    },
    priceBand: 'premium',
    priceUsd: 110,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.5, fruity: 0.5, sweet: 0.4, spicy: 0.3 },
      heart: { spicy: 0.6, sweet: 0.6, warm: 0.5, floral: 0.2 },
      drydown: { sweet: 0.7, warm: 0.8, woody: 0.3, smoky: 0.1, earthy: 0.2 },
    },
    phases: { heartAtMin: 20, drydownAtMin: 140 },
    community: {
      tier: 'huge',
      rating: 7.2,
      divisiveness: 0.65,
      scent: 7.1,
      performance: 8.3,
      value: 7.8,
      originality: 6.8,
      longevityHrs: 9,
      projection: 4.3,
      projectionLater: 3.3,
      seasons: { spring: 0.3, summer: 0.1, autumn: 0.8, winter: 0.95 },
      time: { day: 0.3, night: 0.95 },
      weather: { hot: 0.1, mild: 0.55, cold: 0.95, rain: 0.5, humid: 0.1 },
      occasions: { office: 0.15, school: 0.3, date: 0.7, formal: 0.3, casual: 0.45, nightlife: 0.95, special: 0.5, outdoors: 0.2 },
      perceived: {
        cinnamon: 0.8,
        amber: 0.7,
        leather: 0.5,
        'blood-orange': 0.45,
        mint: 0.3,
        honey: 0.3,
        boozy: 0.35,
        rose: 0.2,
        patchouli: 0.25,
        grapefruit: 0.15,
      },
      strongestByPhase: {
        opening: ['blood-orange', 'mint', 'cinnamon'],
        heart: ['cinnamon', 'rose', 'boozy'],
        drydown: ['amber', 'leather', 'honey'],
      },
    },
    bottle: {
      body: 'block',
      width: 1.15,
      height: 1.15,
      depth: 0.6,
      glass: 'tinted',
      glassTint: '#B8963E',
      glassGradient: '#C9A75A',
      liquid: '#C4983F',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'gold',
      capWidth: 1.5,
      capHeight: 0.7,
      collar: 'none',
      label: 'printed',
      labelInk: '#5A4214',
    },
    accent: '#B08A3E',
  },

  // 9 ------------------------------------------------------------------ Dior Homme Intense EDP
  {
    slug: 'dior-homme-intense',
    name: 'Dior Homme Intense',
    brand: 'dior',
    concentration: 'edp',
    releaseYear: 2011,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: ['francois-demachy', 'olivier-polge'],
    style: 'Iris and woods',
    summary:
      'Cool, buttery iris with a touch of pear and lavender, warming into soft cedar and vetiver. Powdery, lipstick-ish and surprisingly tender.',
    bestFor: 'Evenings, formal wear, cold weather',
    sources: [
      unverified('identity', 'Dior', 0.55, 'the current EDP is the 2011 edition; an earlier Intense appeared in 2007. Year kept at 2011 per roster, lower confidence on the exact lineage.'),
      unverified('notes', 'Dior', 0.55, 'Dior headlines iris, ambrette, pear, lavender, cedar and vetiver. Phase placement is ours.'),
      unverified('perfumers', 'press coverage', 0.5, 'the Dior Homme line was originally composed by Olivier Polge; the 2011 Intense is credited to François Demachy. Both listed; uncertain split.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US price for 100 ml.'),
    ],
    bottleDescription:
      'A slim rectangular bottle in smoky grey-brown glass with a polished metal cap and the name printed down the front.',
    editorial:
      'Dior Homme Intense is the fragrance people mean when they say iris smells like expensive lipstick. It is cool and powdery at first, then turns surprisingly warm and close, with the pear and ambrette giving it a soft skin-like glow. It is among the most praised designer masculines for evening wear, and it projects less than its reputation suggests.',
    notes: {
      top: ['lavender'],
      heart: ['iris', 'ambrette', 'pear'],
      base: ['cedarwood', 'vetiver'],
    },
    priceBand: 'premium',
    priceUsd: 155,
    sizeMl: 100,
    character: {
      opening: { powdery: 0.6, floral: 0.4, fruity: 0.3, fresh: 0.3 },
      heart: { powdery: 0.8, floral: 0.5, creamy: 0.4, sweet: 0.3, earthy: 0.2 },
      drydown: { powdery: 0.5, woody: 0.6, warm: 0.5, creamy: 0.4, earthy: 0.3 },
    },
    phases: { heartAtMin: 20, drydownAtMin: 200 },
    community: {
      tier: 'large',
      rating: 8.6,
      divisiveness: 0.3,
      scent: 8.8,
      performance: 7.6,
      value: 7.0,
      originality: 7.8,
      longevityHrs: 9,
      projection: 3,
      projectionLater: 2.4,
      seasons: { spring: 0.4, summer: 0.1, autumn: 0.9, winter: 0.95 },
      time: { day: 0.45, night: 0.95 },
      weather: { hot: 0.1, mild: 0.6, cold: 0.95, rain: 0.75, humid: 0.1 },
      occasions: { office: 0.5, school: 0.2, date: 0.9, formal: 0.9, casual: 0.35, nightlife: 0.6, special: 0.8, outdoors: 0.15 },
      perceived: {
        iris: 0.9,
        powdery: 0.7,
        pear: 0.35,
        cacao: 0.3,
        ambrette: 0.25,
        lavender: 0.25,
        leather: 0.2,
        vetiver: 0.3,
        cedarwood: 0.25,
      },
      strongestByPhase: {
        opening: ['iris', 'lavender', 'pear'],
        heart: ['iris', 'powdery', 'cacao'],
        drydown: ['iris', 'vetiver', 'leather'],
      },
    },
    bottle: {
      body: 'tall',
      width: 1.25,
      height: 1.05,
      depth: 1.0,
      glass: 'smoked',
      glassTint: '#4C4643',
      liquid: '#6E5A48',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'gunmetal',
      capWidth: 1.0,
      capHeight: 0.9,
      collar: 'none',
      label: 'printed',
      labelInk: '#D8D4CC',
    },
    accent: '#6E6470',
  },

  // 10 ----------------------------------------------------------------- Prada L'Homme EDT
  {
    slug: 'prada-l-homme',
    name: 'Prada L\'Homme',
    brand: 'prada',
    concentration: 'edt',
    releaseYear: 2016,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: ['daniela-andrier'],
    style: 'Soapy iris and amber',
    summary:
      'Clean iris and neroli over a soft ambery base, with a pinch of pepper and cardamom. Smells like expensive soap on a freshly ironed shirt.',
    bestFor: 'Office, weddings, everyday polish',
    sources: [
      unverified('identity', 'Prada Beauty', 0.7, 'launched 2016; widely published.'),
      unverified('notes', 'Prada Beauty', 0.5, 'Prada headlines iris, neroli, amber and cedar; the supporting notes (geranium, violet, mate, black pepper, cardamom, patchouli) are from the widely circulated launch list and lower confidence. Phase placement is ours.'),
      unverified('perfumers', 'press coverage', 0.65, 'Daniela Andrier, Prada\'s long-time perfumer.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US price for 100 ml.'),
    ],
    bottleDescription:
      'A clean-lined rectangular bottle in clear glass with a dark cap and the Prada name across the front.',
    editorial:
      'L\'Homme is the fragrance equivalent of a perfectly plain white shirt that turns out to be very expensive. Andrier\'s iris is dry and soapy rather than lipsticky, and the amber underneath keeps it from feeling cold. It is quiet, office-proof and almost impossible to dislike, which also means it rarely starts a conversation.',
    notes: {
      top: ['neroli', 'black-pepper', 'cardamom'],
      heart: ['iris', 'violet', 'geranium', 'mate'],
      base: ['amber', 'cedarwood', 'patchouli'],
    },
    priceBand: 'premium',
    priceUsd: 125,
    sizeMl: 100,
    character: {
      opening: { clean: 0.7, fresh: 0.5, powdery: 0.3, spicy: 0.3 },
      heart: { clean: 0.7, powdery: 0.6, floral: 0.4 },
      drydown: { powdery: 0.4, clean: 0.5, warm: 0.4, woody: 0.4 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 150 },
    community: {
      tier: 'large',
      rating: 8.0,
      divisiveness: 0.25,
      scent: 8.1,
      performance: 6.8,
      value: 7.1,
      originality: 6.4,
      longevityHrs: 7,
      projection: 2.8,
      projectionLater: 2.1,
      seasons: { spring: 0.9, summer: 0.6, autumn: 0.75, winter: 0.45 },
      time: { day: 0.9, night: 0.55 },
      weather: { hot: 0.5, mild: 0.95, cold: 0.5, rain: 0.6, humid: 0.45 },
      occasions: { office: 0.95, school: 0.6, date: 0.6, formal: 0.8, casual: 0.7, nightlife: 0.3, special: 0.65, outdoors: 0.35 },
      perceived: {
        iris: 0.8,
        soapy: 0.7,
        neroli: 0.45,
        amber: 0.45,
        powdery: 0.5,
        laundry: 0.3,
        'black-pepper': 0.2,
        cardamom: 0.2,
        cedarwood: 0.2,
        mate: 0.05,
      },
      strongestByPhase: {
        opening: ['neroli', 'soapy', 'black-pepper'],
        heart: ['iris', 'soapy', 'powdery'],
        drydown: ['amber', 'iris', 'laundry'],
      },
    },
    bottle: {
      body: 'block',
      width: 1.05,
      height: 1.35,
      depth: 0.6,
      glass: 'clear',
      liquid: '#E7E0D2',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'black',
      capWidth: 1.1,
      capHeight: 0.9,
      collar: 'none',
      label: 'printed',
      labelInk: '#1C1A17',
    },
    accent: '#8A8F96',
  },

  // 11 ----------------------------------------------------------------- Davidoff Cool Water EDT
  {
    slug: 'cool-water',
    name: 'Cool Water',
    brand: 'davidoff',
    concentration: 'edt',
    releaseYear: 1988,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: ['pierre-bourdon'],
    style: 'Fresh aromatic fougère',
    summary:
      'A cold rush of mint and lavender with a green, watery edge, drying to musky woods and a faint sweetness. The blueprint for a hundred fresh blues.',
    bestFor: 'Hot days, gym, cheap everyday spray',
    sources: [
      unverified('identity', 'Davidoff', 0.7, 'launched 1988; widely published.'),
      unverified('notes', 'Davidoff', 0.5, 'Davidoff describes mint, lavender and sea-fresh notes; the full pyramid (rosemary, coriander, green notes, geranium, neroli, jasmine, sandalwood, cedar, musk, amber, oakmoss, tobacco) is the widely circulated breakdown and lower confidence. "Green notes" mapped to our green-leaves accord.'),
      unverified('perfumers', 'press coverage', 0.7, 'Pierre Bourdon is the widely credited perfumer.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US list price for 125 ml; usually discounted.'),
    ],
    bottleDescription:
      'A tall, flat bottle in light blue glass with rounded sides and white lettering, topped with a short blue cap.',
    editorial:
      'Before Cool Water, "fresh" for men mostly meant citrus cologne. Bourdon pushed mint, lavender and a synthetic watery note so hard that the whole category tilted toward it for the next decade. It is cheap and a little blunt today, but there is a reason it is still on every drugstore shelf: it does exactly what the name says.',
    notes: {
      top: ['mint', 'green-leaves', 'lavender', 'coriander', 'rosemary'],
      heart: ['geranium', 'neroli', 'jasmine', 'sandalwood'],
      base: ['cedarwood', 'musk', 'amber', 'oakmoss', 'tobacco'],
    },
    priceBand: 'accessible',
    priceUsd: 60,
    sizeMl: 125,
    character: {
      opening: { fresh: 0.9, green: 0.4, clean: 0.4 },
      heart: { fresh: 0.6, clean: 0.5, floral: 0.2, green: 0.3 },
      drydown: { clean: 0.4, woody: 0.4, warm: 0.3, earthy: 0.2 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 120 },
    community: {
      tier: 'huge',
      rating: 7.1,
      divisiveness: 0.4,
      scent: 7.0,
      performance: 7.3,
      value: 9.0,
      originality: 7.4,
      longevityHrs: 6,
      projection: 3.6,
      projectionLater: 2.4,
      seasons: { spring: 0.8, summer: 0.95, autumn: 0.35, winter: 0.15 },
      time: { day: 0.95, night: 0.35 },
      weather: { hot: 0.9, mild: 0.75, cold: 0.15, rain: 0.35, humid: 0.8 },
      occasions: { office: 0.55, school: 0.75, date: 0.3, formal: 0.15, casual: 0.9, nightlife: 0.25, special: 0.1, outdoors: 0.85 },
      perceived: {
        mint: 0.75,
        lavender: 0.65,
        ozonic: 0.5,
        'marine-notes': 0.45,
        musk: 0.35,
        rosemary: 0.25,
        soapy: 0.3,
        'green-leaves': 0.3,
        amber: 0.2,
        tobacco: 0.05,
      },
      strongestByPhase: {
        opening: ['mint', 'lavender', 'green-leaves'],
        heart: ['lavender', 'ozonic', 'marine-notes'],
        drydown: ['musk', 'amber', 'soapy'],
      },
    },
    bottle: {
      body: 'tall',
      width: 1.2,
      height: 1.15,
      depth: 0.9,
      glass: 'tinted',
      glassTint: '#5E95BF',
      liquid: '#7FAED0',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'resin',
      capColor: '#2F5E86',
      capWidth: 0.9,
      capHeight: 0.8,
      collar: 'none',
      label: 'printed',
      labelInk: '#F2F4F5',
    },
    accent: '#3E7FA6',
  },

  // 12 ----------------------------------------------------------------- Nautica Voyage EDT
  {
    slug: 'nautica-voyage',
    name: 'Nautica Voyage',
    brand: 'nautica',
    concentration: 'edt',
    releaseYear: 2006,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: [],
    style: 'Green aquatic',
    summary:
      'Crisp green apple and crushed leaves over a cool, watery floral heart, drying to light musk and woods. Simple, clean and absurdly cheap.',
    bestFor: 'Summer days, gym, blind buys',
    sources: [
      unverified('identity', 'Nautica', 0.6, 'launched 2006; widely published. Perfumer not disclosed by the house as far as we know, so left empty.'),
      unverified('notes', 'Nautica', 0.45, 'notes as commonly given on retail listings: green leaf, apple; mimosa, lotus; cedarwood, oakmoss, musk, amber. Not confirmed on a house page.'),
      unverified('price', 'US retail', 0.4, 'typical discounted US price for 100 ml; list price is higher.'),
    ],
    bottleDescription:
      'A round, flat glass bottle like a porthole or ship\'s compass, filled with pale green-blue juice and capped with a navy cap.',
    editorial:
      'Voyage is the fragrance people recommend when someone asks for "something fresh under thirty dollars", and it holds up better than the price suggests. The apple-and-leaves opening is genuinely pleasant, and the watery lotus heart keeps it light. It fades in a few hours, but at this price nobody minds respraying.',
    notes: {
      top: ['green-apple', 'green-leaves'],
      heart: ['mimosa', 'lotus'],
      base: ['cedarwood', 'oakmoss', 'musk', 'amber'],
    },
    priceBand: 'budget',
    priceUsd: 25,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.8, green: 0.6, fruity: 0.4 },
      heart: { fresh: 0.6, green: 0.4, floral: 0.3, clean: 0.4 },
      drydown: { clean: 0.5, woody: 0.3, fresh: 0.3, warm: 0.2 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 100 },
    community: {
      tier: 'large',
      rating: 7.2,
      divisiveness: 0.3,
      scent: 7.2,
      performance: 5.6,
      value: 9.3,
      originality: 5.8,
      longevityHrs: 4,
      projection: 2.9,
      projectionLater: 1.8,
      seasons: { spring: 0.85, summer: 0.95, autumn: 0.3, winter: 0.1 },
      time: { day: 0.95, night: 0.25 },
      weather: { hot: 0.9, mild: 0.75, cold: 0.1, rain: 0.35, humid: 0.85 },
      occasions: { office: 0.65, school: 0.85, date: 0.25, formal: 0.1, casual: 0.9, nightlife: 0.15, special: 0.1, outdoors: 0.85 },
      perceived: {
        'green-apple': 0.7,
        'green-leaves': 0.6,
        'marine-notes': 0.5,
        lotus: 0.35,
        musk: 0.4,
        cucumber: 0.2,
        ozonic: 0.3,
        mimosa: 0.1,
        oakmoss: 0.05,
      },
      strongestByPhase: {
        opening: ['green-apple', 'green-leaves'],
        heart: ['marine-notes', 'lotus', 'ozonic'],
        drydown: ['musk', 'marine-notes'],
      },
    },
    bottle: {
      body: 'orb',
      width: 1.05,
      height: 1.0,
      glass: 'clear',
      liquid: '#A7CFC4',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'resin',
      capColor: '#1F2F4A',
      capWidth: 0.9,
      capHeight: 0.9,
      collar: 'none',
      label: 'printed',
      labelInk: '#1F2F4A',
    },
    accent: '#5E8C7A',
  },

  // 13 ----------------------------------------------------------------- Dior Eau Sauvage EDT
  {
    slug: 'eau-sauvage',
    name: 'Eau Sauvage',
    brand: 'dior',
    concentration: 'edt',
    releaseYear: 1966,
    status: 'reformulated',
    marketedFor: 'masculine',
    perfumers: ['edmond-roudnitska'],
    style: 'Citrus aromatic chypre',
    summary:
      'Bright lemon and herbs with a soft, airy jasmine haze, settling on dry vetiver and a mossy hint. Crisp, cologne-like and very elegant.',
    bestFor: 'Warm days, office, linen suits',
    sources: [
      unverified('identity', 'Dior', 0.7, 'launched 1966; widely published. Status "reformulated": the formula has been revised over the decades, including to meet IFRA limits on oakmoss and other materials; we could not open a dated source for a specific reformulation year, so no year is given.'),
      unverified('notes', 'Dior', 0.5, 'notes as commonly described for the original: lemon, bergamot, basil, rosemary, Hedione-led jasmine, vetiver and oakmoss. Current Dior copy emphasises citrus and vetiver. Phase placement is ours.'),
      unverified('perfumers', 'Dior / perfume history', 0.7, 'Edmond Roudnitska; Eau Sauvage is widely cited as the first fine fragrance to use Hedione prominently.'),
      unverified('status', 'editorial', 0.45, 'reformulation history is widely reported but not confirmed against a primary source this session.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US price for 100 ml.'),
    ],
    bottleDescription:
      'A clear glass bottle with rounded shoulders showing pale straw-coloured juice, with a dark cap and the name printed on the glass.',
    editorial:
      'Eau Sauvage is a lesson in how much air you can put into a bottle. Roudnitska took the traditional citrus cologne, gave it a vetiver-and-moss spine and soaked it in Hedione, which makes the whole thing feel like sunlight on a terrace. Modern versions are lighter in the moss than older bottles, but the shape of the idea is intact.',
    notes: {
      top: ['lemon', 'bergamot', 'basil', 'rosemary'],
      heart: ['hedione', 'jasmine'],
      base: ['vetiver', 'oakmoss', 'musk'],
    },
    priceBand: 'premium',
    priceUsd: 125,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.9, green: 0.3, clean: 0.4 },
      heart: { fresh: 0.6, floral: 0.4, clean: 0.4, green: 0.3 },
      drydown: { woody: 0.5, earthy: 0.4, fresh: 0.3, clean: 0.3 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 100 },
    community: {
      tier: 'large',
      rating: 8.0,
      divisiveness: 0.3,
      scent: 8.3,
      performance: 5.8,
      value: 7.0,
      originality: 8.4,
      longevityHrs: 4.5,
      projection: 2.9,
      projectionLater: 1.8,
      seasons: { spring: 0.9, summer: 0.95, autumn: 0.4, winter: 0.15 },
      time: { day: 0.95, night: 0.3 },
      weather: { hot: 0.9, mild: 0.85, cold: 0.2, rain: 0.4, humid: 0.7 },
      occasions: { office: 0.85, school: 0.4, date: 0.4, formal: 0.6, casual: 0.75, nightlife: 0.15, special: 0.4, outdoors: 0.7 },
      perceived: {
        lemon: 0.8,
        bergamot: 0.5,
        hedione: 0.35,
        jasmine: 0.25,
        basil: 0.3,
        rosemary: 0.3,
        vetiver: 0.55,
        oakmoss: 0.25,
        soapy: 0.3,
        petitgrain: 0.2,
      },
      strongestByPhase: {
        opening: ['lemon', 'bergamot', 'basil'],
        heart: ['hedione', 'jasmine', 'rosemary'],
        drydown: ['vetiver', 'oakmoss', 'soapy'],
      },
    },
    bottle: {
      body: 'apothecary',
      width: 1.1,
      height: 1.15,
      glass: 'clear',
      liquid: '#E6D9A6',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'black',
      capWidth: 0.95,
      capHeight: 0.9,
      collar: 'none',
      label: 'printed',
      labelInk: '#1C1A17',
    },
    accent: '#8C9A5E',
  },

  // 14 ----------------------------------------------------------------- Chanel N°5 Parfum
  {
    slug: 'chanel-no-5',
    name: 'N°5',
    brand: 'chanel',
    concentration: 'parfum',
    releaseYear: 1921,
    status: 'current',
    marketedFor: 'feminine',
    perfumers: ['ernest-beaux'],
    style: 'Aldehydic floral',
    summary:
      'A fizzy, soapy sparkle of aldehydes over rose, jasmine and ylang, settling into creamy sandalwood, vanilla and soft musk. Abstract, powdery and unmistakable.',
    bestFor: 'Formal evenings, cold weather, classic taste',
    sources: [
      unverified('identity', 'Chanel', 0.7, 'created 1921 by Ernest Beaux; the parfum (extrait) is the original concentration. The EDP dates from 1986. Widely published.'),
      unverified('notes', 'Chanel', 0.55, 'Chanel highlights aldehydes, May rose and Grasse jasmine; the fuller structure (neroli, ylang-ylang, iris, lily of the valley, sandalwood, vetiver, vanilla, musk) is the commonly published breakdown. Phase placement is ours.'),
      unverified('perfumers', 'Chanel', 0.7, 'Ernest Beaux.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US price for the 15 ml parfum bottle.'),
    ],
    bottleDescription:
      'A clear, rectangular glass bottle with bevelled edges and a faceted, cut-glass stopper, with a plain white label printed in black.',
    editorial:
      'N°5 is the most famous perfume in the world, and the parfum is the closest you can get to the 1921 idea. The aldehydes give it that bright, almost waxy fizz, and the florals are blended so tightly you cannot pick out a single flower. Many people meet it in the brighter, more diffusive Eau de Parfum; the parfum is softer, rounder and sits closer to skin.',
    notes: {
      top: ['aldehydes', 'neroli', 'ylang-ylang'],
      heart: ['rose', 'jasmine', 'iris', 'lily-of-the-valley'],
      base: ['sandalwood', 'vetiver', 'vanilla', 'musk'],
    },
    priceBand: 'luxury',
    priceUsd: 180,
    sizeMl: 15,
    character: {
      opening: { clean: 0.6, fresh: 0.4, floral: 0.5, powdery: 0.4 },
      heart: { floral: 0.9, powdery: 0.6, clean: 0.4, sweet: 0.2 },
      drydown: { powdery: 0.6, creamy: 0.5, woody: 0.5, warm: 0.4, sweet: 0.3 },
    },
    phases: { heartAtMin: 25, drydownAtMin: 240 },
    community: {
      tier: 'huge',
      rating: 7.9,
      divisiveness: 0.6,
      scent: 8.1,
      performance: 7.8,
      value: 5.8,
      originality: 9.0,
      longevityHrs: 9,
      projection: 2.6,
      projectionLater: 2.2,
      seasons: { spring: 0.6, summer: 0.25, autumn: 0.8, winter: 0.85 },
      time: { day: 0.55, night: 0.85 },
      weather: { hot: 0.2, mild: 0.75, cold: 0.85, rain: 0.6, humid: 0.2 },
      occasions: { office: 0.45, school: 0.1, date: 0.6, formal: 0.95, casual: 0.3, nightlife: 0.5, special: 0.9, outdoors: 0.15 },
      perceived: {
        aldehydes: 0.85,
        powdery: 0.65,
        rose: 0.55,
        jasmine: 0.5,
        'ylang-ylang': 0.35,
        soapy: 0.45,
        sandalwood: 0.45,
        waxy: 0.3,
        vanilla: 0.3,
        iris: 0.2,
        'lily-of-the-valley': 0.1,
      },
      strongestByPhase: {
        opening: ['aldehydes', 'soapy', 'waxy'],
        heart: ['rose', 'jasmine', 'powdery'],
        drydown: ['sandalwood', 'vanilla', 'powdery'],
      },
    },
    bottle: {
      body: 'block',
      width: 0.85,
      height: 1.0,
      depth: 0.6,
      glass: 'clear',
      liquid: '#DDB868',
      fill: 0.85,
      cap: 'faceted',
      capMaterial: 'resin',
      capColor: '#ECE8DC',
      capWidth: 1.2,
      capHeight: 0.8,
      collar: 'black',
      label: 'paper',
      labelColor: '#F4F1EA',
      labelInk: '#141312',
    },
    accent: '#C8A96A',
  },

  // 15 ----------------------------------------------------------------- Chanel Coco Mademoiselle EDP
  {
    slug: 'coco-mademoiselle',
    name: 'Coco Mademoiselle',
    brand: 'chanel',
    concentration: 'edp',
    releaseYear: 2001,
    status: 'current',
    marketedFor: 'feminine',
    perfumers: ['jacques-polge'],
    style: 'Citrus rose patchouli',
    summary:
      'Sparkling orange and bergamot over a fresh rose and jasmine heart, drying to clean patchouli, vetiver and soft vanilla musk. Bright, polished and long-lasting.',
    bestFor: 'Office, daytime events, all year',
    sources: [
      unverified('identity', 'Chanel', 0.7, 'launched 2001; widely published.'),
      unverified('notes', 'Chanel', 0.55, 'Chanel names orange, rose, jasmine, patchouli, vetiver and vanilla; bergamot and white musk are from the commonly published breakdown. Phase placement is ours.'),
      unverified('perfumers', 'Chanel', 0.7, 'Jacques Polge.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US price for 100 ml.'),
    ],
    bottleDescription:
      'A clear rectangular glass bottle with bevelled edges showing pale pink-amber juice, with a squared cap and black printed lettering.',
    editorial:
      'Coco Mademoiselle took the patchouli chypre, scrubbed the dirt off it and added a lot of sparkle, and in doing so wrote the template for the modern "fresh oriental" feminine. The opening is all orange zest, the heart a clean rose, and the patchouli drydown is smooth enough for an office. It is everywhere for good reason, and it lasts.',
    notes: {
      top: ['sweet-orange', 'bergamot'],
      heart: ['rose', 'jasmine'],
      base: ['patchouli', 'vetiver', 'vanilla', 'musk'],
    },
    priceBand: 'premium',
    priceUsd: 175,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.8, fruity: 0.4, floral: 0.3, sweet: 0.2 },
      heart: { floral: 0.7, fresh: 0.4, clean: 0.4, sweet: 0.3 },
      drydown: { earthy: 0.5, woody: 0.4, sweet: 0.4, clean: 0.4, warm: 0.3 },
    },
    phases: { heartAtMin: 20, drydownAtMin: 180 },
    community: {
      tier: 'huge',
      rating: 8.0,
      divisiveness: 0.35,
      scent: 8.0,
      performance: 8.2,
      value: 6.6,
      originality: 6.8,
      longevityHrs: 9,
      projection: 3.6,
      projectionLater: 2.9,
      seasons: { spring: 0.9, summer: 0.55, autumn: 0.85, winter: 0.6 },
      time: { day: 0.9, night: 0.65 },
      weather: { hot: 0.45, mild: 0.95, cold: 0.6, rain: 0.55, humid: 0.4 },
      occasions: { office: 0.9, school: 0.5, date: 0.7, formal: 0.75, casual: 0.7, nightlife: 0.5, special: 0.7, outdoors: 0.35 },
      perceived: {
        'sweet-orange': 0.6,
        bergamot: 0.4,
        rose: 0.65,
        patchouli: 0.8,
        jasmine: 0.35,
        musk: 0.5,
        vanilla: 0.35,
        lychee: 0.15,
        vetiver: 0.2,
        soapy: 0.2,
      },
      strongestByPhase: {
        opening: ['sweet-orange', 'bergamot'],
        heart: ['rose', 'patchouli', 'jasmine'],
        drydown: ['patchouli', 'musk', 'vanilla'],
      },
    },
    bottle: {
      body: 'block',
      width: 1.0,
      height: 1.3,
      depth: 0.6,
      glass: 'clear',
      liquid: '#E7B9A6',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'resin',
      capColor: '#EFE9E4',
      capWidth: 1.0,
      capHeight: 0.85,
      collar: 'none',
      label: 'printed',
      labelInk: '#141312',
    },
    accent: '#B4848A',
  },

  // 16 ----------------------------------------------------------------- YSL Black Opium EDP
  {
    slug: 'black-opium',
    name: 'Black Opium',
    brand: 'yves-saint-laurent',
    concentration: 'edp',
    releaseYear: 2014,
    status: 'current',
    marketedFor: 'feminine',
    perfumers: ['nathalie-lorson', 'marie-salamagne', 'olivier-cresp', 'honorine-blanc'],
    style: 'Coffee vanilla gourmand',
    summary:
      'Pear and pink pepper for a moment, then black coffee poured over sweet vanilla and white flowers. Dark, sugary and very much a night-out scent.',
    bestFor: 'Nights out, dates, winter',
    sources: [
      unverified('identity', 'YSL Beauty', 0.7, 'launched 2014; widely published.'),
      unverified('notes', 'YSL Beauty', 0.55, 'YSL headlines black coffee, white flowers and vanilla; pear, pink pepper, orange blossom, jasmine, patchouli, cedar and cashmere wood are from the widely circulated launch pyramid. "Cashmere wood" mapped to cashmeran.'),
      unverified('perfumers', 'press coverage', 0.6, 'credited to Nathalie Lorson, Marie Salamagne, Olivier Cresp and Honorine Blanc.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US price for 90 ml.'),
    ],
    bottleDescription:
      'A curvy bottle in black glass speckled with glitter, with soft rounded sides and a dark cap.',
    editorial:
      'Black Opium shares a name with the 1977 Opium and almost nothing else. It is a coffee-vanilla gourmand built for the club rather than the salon, and it did more than most launches to make coffee a mainstream perfume note. The opening has a pleasant bitter edge, but the long drydown is mostly sweet vanilla, so it can feel cloying in heat.',
    notes: {
      top: ['pear', 'pink-pepper', 'orange-blossom'],
      heart: ['coffee', 'jasmine'],
      base: ['vanilla', 'patchouli', 'cedarwood', 'cashmeran'],
    },
    priceBand: 'premium',
    priceUsd: 155,
    sizeMl: 90,
    character: {
      opening: { fruity: 0.5, sweet: 0.5, spicy: 0.3, floral: 0.3 },
      heart: { sweet: 0.8, warm: 0.5, floral: 0.4, smoky: 0.2 },
      drydown: { sweet: 0.8, warm: 0.6, creamy: 0.4, woody: 0.3 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 150 },
    community: {
      tier: 'huge',
      rating: 7.6,
      divisiveness: 0.55,
      scent: 7.6,
      performance: 8.4,
      value: 7.0,
      originality: 6.6,
      longevityHrs: 9,
      projection: 3.9,
      projectionLater: 3.1,
      seasons: { spring: 0.4, summer: 0.15, autumn: 0.9, winter: 0.95 },
      time: { day: 0.4, night: 0.95 },
      weather: { hot: 0.1, mild: 0.6, cold: 0.95, rain: 0.6, humid: 0.15 },
      occasions: { office: 0.25, school: 0.35, date: 0.9, formal: 0.4, casual: 0.5, nightlife: 0.95, special: 0.6, outdoors: 0.15 },
      perceived: {
        coffee: 0.85,
        vanilla: 0.9,
        caramel: 0.4,
        pear: 0.3,
        'orange-blossom': 0.3,
        jasmine: 0.3,
        'pink-pepper': 0.2,
        patchouli: 0.25,
        almond: 0.2,
        cashmeran: 0.1,
      },
      strongestByPhase: {
        opening: ['pear', 'coffee', 'pink-pepper'],
        heart: ['coffee', 'vanilla', 'orange-blossom'],
        drydown: ['vanilla', 'caramel', 'patchouli'],
      },
    },
    bottle: {
      body: 'pebble',
      width: 0.95,
      height: 1.35,
      depth: 1.0,
      glass: 'tinted',
      glassTint: '#1B1719',
      glassGradient: '#2A2226',
      liquid: '#3A2A2E',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'black',
      capColor: '#151214',
      capWidth: 0.85,
      capHeight: 0.85,
      collar: 'none',
      label: 'printed',
      labelInk: '#D9A7B4',
    },
    accent: '#4A2E3A',
  },

  // 17 ----------------------------------------------------------------- Lancôme La Vie Est Belle EDP
  {
    slug: 'la-vie-est-belle',
    name: 'La Vie Est Belle',
    brand: 'lancome',
    concentration: 'edp',
    releaseYear: 2012,
    status: 'current',
    marketedFor: 'feminine',
    perfumers: ['olivier-polge', 'dominique-ropion', 'anne-flipo'],
    style: 'Iris praline gourmand',
    summary:
      'A juicy pear and blackcurrant opening melts into sweet praline and vanilla, with powdery iris and a bit of patchouli keeping it upright. Sugary and huge.',
    bestFor: 'Cold days, evenings, comfort wear',
    sources: [
      unverified('identity', 'Lancôme', 0.7, 'launched 2012; widely published.'),
      unverified('notes', 'Lancôme', 0.55, 'Lancôme headlines iris, patchouli and a gourmand praline-vanilla accord; blackcurrant, pear, jasmine, orange blossom and tonka are from the widely circulated launch pyramid. Phase placement is ours.'),
      unverified('perfumers', 'press coverage', 0.65, 'credited to Olivier Polge, Dominique Ropion and Anne Flipo.'),
      unverified('price', 'US retail', 0.4, 'approximate 2025-26 US price for 100 ml.'),
    ],
    bottleDescription:
      'A clear crystal-style bottle whose top curves upward like a smile, holding pale pink juice, with a black ribbon tied around the neck.',
    editorial:
      'La Vie Est Belle is one of the defining gourmands of the 2010s and one of the best-selling feminine fragrances of its decade. The praline-vanilla sweetness is the headline, but the iris gives it a powdery, slightly cosmetic backbone that stops it from being pure candy. It is loud and long-lasting, so it suits cold air better than a crowded summer train.',
    notes: {
      top: ['blackcurrant', 'pear'],
      heart: ['iris', 'jasmine', 'orange-blossom'],
      base: ['praline', 'vanilla', 'patchouli', 'tonka-bean'],
    },
    priceBand: 'premium',
    priceUsd: 155,
    sizeMl: 100,
    character: {
      opening: { fruity: 0.7, sweet: 0.6, fresh: 0.2 },
      heart: { sweet: 0.8, powdery: 0.5, floral: 0.4, fruity: 0.3 },
      drydown: { sweet: 0.8, warm: 0.5, creamy: 0.4, powdery: 0.4, earthy: 0.3 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 150 },
    community: {
      tier: 'huge',
      rating: 7.4,
      divisiveness: 0.6,
      scent: 7.3,
      performance: 8.7,
      value: 7.2,
      originality: 6.4,
      longevityHrs: 10,
      projection: 4.2,
      projectionLater: 3.4,
      seasons: { spring: 0.5, summer: 0.2, autumn: 0.85, winter: 0.95 },
      time: { day: 0.6, night: 0.85 },
      weather: { hot: 0.15, mild: 0.7, cold: 0.95, rain: 0.6, humid: 0.15 },
      occasions: { office: 0.35, school: 0.4, date: 0.8, formal: 0.5, casual: 0.65, nightlife: 0.8, special: 0.65, outdoors: 0.2 },
      perceived: {
        praline: 0.75,
        vanilla: 0.8,
        caramel: 0.45,
        iris: 0.4,
        pear: 0.4,
        blackcurrant: 0.3,
        patchouli: 0.35,
        powdery: 0.45,
        'orange-blossom': 0.15,
        'tonka-bean': 0.25,
      },
      strongestByPhase: {
        opening: ['pear', 'blackcurrant', 'praline'],
        heart: ['praline', 'iris', 'powdery'],
        drydown: ['vanilla', 'caramel', 'patchouli'],
      },
    },
    bottle: {
      body: 'block',
      width: 1.1,
      height: 1.1,
      depth: 0.6,
      glass: 'clear',
      liquid: '#E9BDB6',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'resin',
      capColor: '#ECE7E3',
      capWidth: 1.0,
      capHeight: 0.7,
      collar: 'black',
      label: 'printed',
      labelInk: '#141312',
    },
    accent: '#C48A94',
  },
];
