import type { SeedFragrance } from '../types';

/**
 * Group B of the real catalogue (roster items 18-34).
 *
 * PROVENANCE WARNING: web research was unavailable when this file was written. The session's
 * search quota was exhausted and the egress proxy blocked every house, retailer and reference
 * site tried (dior.com, mugler.com, guerlain.com, lelabofragrances.com, byredo.com, sephora.com,
 * notino, wikipedia, wikidata). Every fact below is recorded from prior knowledge of the houses'
 * published information, typed 'editorial' with url null and confidence <= 0.7, and should be
 * re-verified against the house pages before launch. Forbidden sources were not used.
 *
 * Community, character and phases are our editorial demo estimates (flagged as demo in the UI).
 */

type Source = NonNullable<SeedFragrance['sources']>[number];

const NO_WEB =
  'Web research unavailable in this session (search quota exhausted; house, retailer and reference sites blocked by the egress proxy). Recorded from prior knowledge of the house\'s published information; re-verify against the house page.';

function src(field: Source['field'], confidence: number, detail?: string): Source {
  return {
    field,
    type: 'editorial',
    publisher: 'Editorial research',
    url: null,
    confidence,
    note: detail ? `${detail} ${NO_WEB}` : NO_WEB,
  };
}

export const FRAGRANCES_B: SeedFragrance[] = [
  // 18 ------------------------------------------------------------------ J'adore
  {
    slug: 'jadore',
    name: "J'adore",
    brand: 'dior',
    concentration: 'edp',
    releaseYear: 1999,
    status: 'current',
    marketedFor: 'feminine',
    perfumers: ['calice-becker'],
    style: 'Bright white floral bouquet',
    summary:
      'A big, sunny bouquet of jasmine, ylang-ylang and rose with a juicy pear-and-peach glow up top, settling into soft musky flowers.',
    bestFor: 'Daytime polish, weddings, the office',
    sources: [
      src('identity', 0.7, '1999 launch and EDP concentration are long established.'),
      src(
        'notes',
        0.55,
        'Dior presents the EDP around ylang-ylang, Damascena rose and jasmine without a pyramid; fuller pyramids circulating online were not used.',
      ),
      src('perfumers', 0.65, "Calice Becker is the widely documented author of the 1999 original."),
      src('price', 0.4, 'Approximate US price for 100 ml.'),
    ],
    bottleDescription:
      'A clear amphora-shaped glass bottle with a long neck wrapped in stacked gold rings, holding golden juice.',
    editorial:
      "J'adore is the reference point for the modern golden floral: a smooth, airbrushed bouquet where jasmine and ylang-ylang do most of the talking and no single flower stands alone. It is polished rather than daring, which is exactly why it has sold for more than twenty-five years. The fruit up top is brief, and what lasts is a clean, musky floral hum that suits almost any daytime setting.",
    notes: { flat: ['ylang-ylang', 'rose', 'jasmine'] },
    priceBand: 'premium',
    priceUsd: 190,
    sizeMl: 100,
    character: {
      opening: { floral: 0.6, fruity: 0.4, fresh: 0.4, sweet: 0.3 },
      heart: { floral: 0.9, sweet: 0.3, creamy: 0.3, fruity: 0.2 },
      drydown: { floral: 0.6, creamy: 0.3, sweet: 0.3, powdery: 0.2, woody: 0.2 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 150 },
    community: {
      tier: 'huge',
      rating: 7.6,
      divisiveness: 0.25,
      scent: 7.8,
      performance: 6.9,
      value: 6.5,
      originality: 6.0,
      longevityHrs: 7,
      projection: 3,
      projectionLater: 2.5,
      seasons: { spring: 0.85, summer: 0.7, autumn: 0.45, winter: 0.3 },
      time: { day: 0.85, night: 0.45 },
      weather: { hot: 0.6, mild: 0.9, cold: 0.35, rain: 0.4, humid: 0.5 },
      occasions: { office: 0.8, school: 0.55, date: 0.6, formal: 0.75, casual: 0.65, nightlife: 0.35, special: 0.75, outdoors: 0.5 },
      perceived: { jasmine: 0.8, 'ylang-ylang': 0.55, rose: 0.35, pear: 0.35, peach: 0.3, musk: 0.45, waxy: 0.2 },
      strongestByPhase: { opening: ['pear', 'jasmine', 'peach'], heart: ['jasmine', 'ylang-ylang', 'rose'], drydown: ['musk', 'jasmine'] },
    },
    bottle: {
      body: 'apothecary',
      width: 0.85,
      height: 1.35,
      glass: 'clear',
      liquid: '#D8B45E',
      fill: 0.85,
      cap: 'tall',
      capMaterial: 'gold',
      capWidth: 0.7,
      capHeight: 1.2,
      collar: 'gold',
      label: 'printed',
      labelInk: '#A88A3E',
    },
    accent: '#B8954E',
  },

  // 19 ------------------------------------------------------------------ Angel
  {
    slug: 'angel',
    name: 'Angel',
    brand: 'mugler',
    concentration: 'edp',
    releaseYear: 1992,
    status: 'current',
    marketedFor: 'feminine',
    perfumers: ['olivier-cresp'],
    style: 'Patchouli gourmand',
    summary:
      'Caramel and red fruit candy collide with a huge, earthy patchouli. Sweet and dark at once, and it lasts all day and well into the night.',
    bestFor: 'Cold nights, when you want to be noticed',
    sources: [
      src('identity', 0.7, '1992 launch is long established.'),
      src(
        'notes',
        0.5,
        'Mugler presents Angel around patchouli, praline and vanilla; recorded as a flat list rather than a pyramid.',
      ),
      src('perfumers', 0.6, 'Olivier Cresp is the widely documented author; some accounts also credit Yves de Chirin.'),
      src('price', 0.4, 'Approximate US price for the 100 ml refillable star.'),
    ],
    bottleDescription:
      'A faceted five-pointed star of blue glass that sits on its side, filled with blue juice.',
    editorial:
      'Angel is the fragrance that made sweet-and-dark a genre: a sugary praline and fairground-caramel accord pushed straight into a wall of patchouli. It is famously divisive, and the performance is enormous, so one spray is a sensible start. Thirty years on it still smells unlike almost anything else at the counter, including most of what it inspired.',
    notes: { flat: ['patchouli', 'praline', 'vanilla'] },
    priceBand: 'premium',
    priceUsd: 170,
    sizeMl: 100,
    character: {
      opening: { sweet: 0.7, fruity: 0.4, earthy: 0.4, fresh: 0.2 },
      heart: { sweet: 0.8, earthy: 0.7, warm: 0.5, creamy: 0.3 },
      drydown: { earthy: 0.7, sweet: 0.7, warm: 0.6, woody: 0.3, creamy: 0.3 },
    },
    phases: { heartAtMin: 20, drydownAtMin: 240 },
    community: {
      tier: 'huge',
      rating: 7.3,
      divisiveness: 0.7,
      scent: 7.2,
      performance: 9.2,
      value: 7.5,
      originality: 9.5,
      longevityHrs: 12,
      projection: 4.5,
      projectionLater: 4,
      seasons: { spring: 0.25, summer: 0.1, autumn: 0.8, winter: 0.95 },
      time: { day: 0.45, night: 0.85 },
      weather: { hot: 0.1, mild: 0.5, cold: 0.95, rain: 0.55, humid: 0.1 },
      occasions: { office: 0.2, school: 0.1, date: 0.6, formal: 0.45, casual: 0.4, nightlife: 0.75, special: 0.55, outdoors: 0.2 },
      perceived: { patchouli: 0.9, caramel: 0.6, praline: 0.55, vanilla: 0.45, cacao: 0.45, honey: 0.3, raspberry: 0.25 },
      strongestByPhase: { opening: ['caramel', 'raspberry', 'patchouli'], heart: ['patchouli', 'praline', 'cacao'], drydown: ['patchouli', 'vanilla', 'caramel'] },
    },
    bottle: {
      body: 'faceted',
      width: 1.3,
      height: 0.75,
      depth: 0.6,
      glass: 'tinted',
      glassTint: '#3F5C9E',
      liquid: '#4F68B0',
      fill: 0.8,
      cap: 'faceted',
      capMaterial: 'silver',
      capWidth: 0.6,
      capHeight: 0.6,
      collar: 'silver',
      label: 'printed',
      labelInk: '#C9CED8',
    },
    accent: '#4B5A8C',
  },

  // 20 ------------------------------------------------------------------ Good Girl
  {
    slug: 'good-girl',
    name: 'Good Girl',
    brand: 'carolina-herrera',
    concentration: 'edp',
    releaseYear: 2016,
    status: 'current',
    marketedFor: 'feminine',
    perfumers: ['louise-turner'],
    style: 'Tuberose and tonka gourmand',
    summary:
      'Almond and coffee up front, then creamy tuberose and jasmine over a warm bed of tonka and cocoa. Glossy, sweet and built for evenings.',
    bestFor: 'Date nights, parties, cool evenings',
    sources: [
      src('identity', 0.65),
      src(
        'notes',
        0.5,
        'House presents jasmine sambac, tuberose, tonka bean and cacao as key notes; almond and coffee in the top as commonly listed by retailers. Pyramid placement uncertain.',
      ),
      src('perfumers', 0.6, 'Louise Turner is the widely documented author.'),
      src('price', 0.4, 'Approximate US price for 80 ml.'),
    ],
    bottleDescription:
      'A stiletto-shoe-shaped bottle in deep midnight-blue glass with a gold metal heel and cap.',
    editorial:
      'Good Girl pairs a creamy white floral with a roasted, sweet base, and the result is louder and warmer than the tuberose suggests. The almond-coffee opening is the bit people remember, while the drydown sits closer to tonka and cocoa. It sells as much on the shoe bottle as on the scent, but the scent holds up on its own.',
    notes: {
      top: ['almond', 'coffee'],
      heart: ['jasmine', 'tuberose'],
      base: ['tonka-bean', 'cacao'],
    },
    priceBand: 'premium',
    priceUsd: 150,
    sizeMl: 80,
    character: {
      opening: { sweet: 0.5, floral: 0.4, warm: 0.4, creamy: 0.3 },
      heart: { floral: 0.7, sweet: 0.6, creamy: 0.4, warm: 0.3 },
      drydown: { sweet: 0.7, warm: 0.6, creamy: 0.5, powdery: 0.2, woody: 0.2 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 180 },
    community: {
      tier: 'huge',
      rating: 7.4,
      divisiveness: 0.4,
      scent: 7.5,
      performance: 8.2,
      value: 7.0,
      originality: 7.0,
      longevityHrs: 9,
      projection: 3.8,
      projectionLater: 3.2,
      seasons: { spring: 0.4, summer: 0.2, autumn: 0.85, winter: 0.85 },
      time: { day: 0.5, night: 0.85 },
      weather: { hot: 0.15, mild: 0.7, cold: 0.85, rain: 0.5, humid: 0.2 },
      occasions: { office: 0.35, school: 0.25, date: 0.85, formal: 0.65, casual: 0.45, nightlife: 0.9, special: 0.7, outdoors: 0.2 },
      perceived: { 'tonka-bean': 0.75, tuberose: 0.7, almond: 0.55, jasmine: 0.5, vanilla: 0.45, cacao: 0.45, coffee: 0.35, powdery: 0.2 },
      strongestByPhase: { opening: ['almond', 'coffee', 'tuberose'], heart: ['tuberose', 'jasmine', 'tonka-bean'], drydown: ['tonka-bean', 'cacao', 'vanilla'] },
    },
    bottle: {
      body: 'tapered',
      width: 1.1,
      height: 1.15,
      depth: 0.7,
      glass: 'tinted',
      glassTint: '#1F2744',
      liquid: '#3A2E4C',
      fill: 0.85,
      cap: 'tall',
      capMaterial: 'gold',
      capWidth: 0.6,
      capHeight: 1.3,
      collar: 'gold',
      label: 'none',
    },
    accent: '#2E3656',
  },

  // 21 ------------------------------------------------------------------ Flowerbomb
  {
    slug: 'flowerbomb',
    name: 'Flowerbomb',
    brand: 'viktor-rolf',
    concentration: 'edp',
    releaseYear: 2005,
    status: 'current',
    marketedFor: 'feminine',
    perfumers: ['olivier-polge', 'carlos-benaim', 'domitille-bertier', 'dominique-ropion'],
    style: 'Sugared floral patchouli',
    summary:
      'A cloud of sugary jasmine, rose and freesia over a soft patchouli base. Sweet, powdery and long lasting, with a candied edge.',
    bestFor: 'Dates, dressing up, cooler evenings',
    sources: [
      src('identity', 0.65),
      src(
        'notes',
        0.45,
        'Recorded as commonly published: tea, bergamot and osmanthus top; jasmine sambac, freesia, centifolia rose and cattleya orchid heart; patchouli and musk base. Tea mapped to green-tea, which may not match the house wording.',
      ),
      src('perfumers', 0.6, 'Widely credited to four co-authors: Olivier Polge, Carlos Benaïm, Domitille Bertier and Dominique Ropion.'),
      src('price', 0.4, 'Approximate US price for 100 ml.'),
    ],
    bottleDescription:
      'A faceted, grenade-shaped bottle of pale pink-tinted glass with a silver pin-style cap.',
    editorial:
      'Flowerbomb is less a bouquet than a sweetened floral haze: the flowers blur together into something sugary and powdery, held up by a soft patchouli base. It was one of the scents that set the template for the sweet floral-patchouli wave of the 2010s. Expect it to last and to leave a trail, so go lightly in small rooms.',
    notes: {
      top: ['green-tea', 'bergamot', 'osmanthus'],
      heart: ['jasmine', 'freesia', 'rose', 'orchid'],
      base: ['patchouli', 'musk'],
    },
    priceBand: 'premium',
    priceUsd: 185,
    sizeMl: 100,
    character: {
      opening: { floral: 0.5, sweet: 0.5, fresh: 0.3, fruity: 0.2 },
      heart: { floral: 0.8, sweet: 0.7, powdery: 0.3, creamy: 0.2 },
      drydown: { sweet: 0.6, earthy: 0.4, floral: 0.4, warm: 0.4, powdery: 0.3 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 180 },
    community: {
      tier: 'large',
      rating: 7.5,
      divisiveness: 0.45,
      scent: 7.6,
      performance: 8.0,
      value: 6.4,
      originality: 6.5,
      longevityHrs: 9,
      projection: 3.8,
      projectionLater: 3,
      seasons: { spring: 0.7, summer: 0.3, autumn: 0.7, winter: 0.7 },
      time: { day: 0.6, night: 0.75 },
      weather: { hot: 0.25, mild: 0.85, cold: 0.7, rain: 0.5, humid: 0.25 },
      occasions: { office: 0.45, school: 0.3, date: 0.85, formal: 0.65, casual: 0.5, nightlife: 0.75, special: 0.75, outdoors: 0.3 },
      perceived: {
        patchouli: 0.55,
        jasmine: 0.5,
        rose: 0.45,
        powdery: 0.45,
        caramel: 0.4,
        freesia: 0.35,
        musk: 0.35,
        orchid: 0.3,
        bergamot: 0.2,
        'green-tea': 0.1,
      },
      strongestByPhase: { opening: ['bergamot', 'rose', 'caramel'], heart: ['jasmine', 'rose', 'powdery'], drydown: ['patchouli', 'caramel', 'musk'] },
    },
    bottle: {
      body: 'faceted',
      width: 1.1,
      height: 1.0,
      glass: 'tinted',
      glassTint: '#E6C4CD',
      liquid: '#E2A6B6',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'silver',
      capWidth: 0.6,
      capHeight: 0.9,
      collar: 'silver',
      label: 'printed',
      labelInk: '#8A5866',
    },
    accent: '#B07A88',
  },

  // 22 ------------------------------------------------------------------ Daisy
  {
    slug: 'daisy',
    name: 'Daisy',
    brand: 'marc-jacobs',
    concentration: 'edt',
    releaseYear: 2007,
    status: 'current',
    marketedFor: 'feminine',
    perfumers: ['alberto-morillas'],
    style: 'Light fruity floral',
    summary:
      'Strawberry and grapefruit with a green violet-leaf snap, then soft violet and gardenia drifting into clean musk and pale woods.',
    bestFor: 'Spring days, school, easy everyday wear',
    sources: [
      src('identity', 0.7),
      src(
        'notes',
        0.55,
        'Recorded pyramid: strawberry, violet leaves and ruby red grapefruit; gardenia, violet petals and jasmine; musk, vanilla and white woods.',
      ),
      src('perfumers', 0.6, 'Alberto Morillas is the widely documented author.'),
      src('price', 0.4, 'Approximate US price for 100 ml.'),
    ],
    bottleDescription:
      'A squared clear glass bottle of pale yellow juice topped with a cluster of white rubber daisies with yellow centres.',
    editorial:
      'Daisy is a light, friendly fruity floral that gets out of the way, which is a lot of its appeal. The strawberry and green violet-leaf opening is the most distinctive part; the rest is soft violet and clean musk. It fades to a skin scent in a few hours, so it suits people who prefer a gentle presence.',
    notes: {
      top: ['strawberry', 'violet-leaf', 'grapefruit'],
      heart: ['gardenia', 'violet', 'jasmine'],
      base: ['musk', 'vanilla', 'white-woods'],
    },
    priceBand: 'premium',
    priceUsd: 135,
    sizeMl: 100,
    character: {
      opening: { fruity: 0.6, fresh: 0.5, green: 0.3, sweet: 0.3 },
      heart: { floral: 0.7, fresh: 0.3, sweet: 0.3, powdery: 0.2 },
      drydown: { clean: 0.5, floral: 0.3, woody: 0.3, sweet: 0.3, creamy: 0.2 },
    },
    phases: { heartAtMin: 10, drydownAtMin: 90 },
    community: {
      tier: 'large',
      rating: 7.2,
      divisiveness: 0.3,
      scent: 7.4,
      performance: 5.6,
      value: 7.0,
      originality: 5.5,
      longevityHrs: 5,
      projection: 2.8,
      projectionLater: 2,
      seasons: { spring: 0.9, summer: 0.75, autumn: 0.3, winter: 0.15 },
      time: { day: 0.9, night: 0.3 },
      weather: { hot: 0.7, mild: 0.9, cold: 0.2, rain: 0.4, humid: 0.6 },
      occasions: { office: 0.75, school: 0.8, date: 0.5, formal: 0.3, casual: 0.85, nightlife: 0.2, special: 0.35, outdoors: 0.7 },
      perceived: {
        strawberry: 0.55,
        musk: 0.55,
        violet: 0.5,
        grapefruit: 0.4,
        'violet-leaf': 0.3,
        gardenia: 0.3,
        soapy: 0.3,
        jasmine: 0.2,
        vanilla: 0.2,
        'white-woods': 0.2,
      },
      strongestByPhase: { opening: ['strawberry', 'grapefruit', 'violet-leaf'], heart: ['violet', 'gardenia'], drydown: ['musk', 'white-woods'] },
    },
    bottle: {
      body: 'block',
      width: 1.0,
      height: 1.0,
      glass: 'clear',
      liquid: '#E6DC9E',
      fill: 0.85,
      cap: 'dome',
      capMaterial: 'white',
      capColor: '#F1EEE4',
      capWidth: 1.4,
      capHeight: 1.1,
      collar: 'gold',
      label: 'printed',
      labelInk: '#2A2A2A',
    },
    accent: '#B9A85E',
  },

  // 23 ------------------------------------------------------------------ Bombshell
  {
    slug: 'bombshell',
    name: 'Bombshell',
    brand: 'victorias-secret',
    concentration: 'edp',
    releaseYear: 2010,
    status: 'current',
    marketedFor: 'feminine',
    perfumers: [],
    style: 'Juicy fruity floral',
    summary:
      'Bright passion fruit and tropical juice over a soft peony heart, fading to a light, sweet musk. Easy, cheerful and very recognisable.',
    bestFor: 'Warm days, casual plans, going out',
    sources: [
      src('identity', 0.65),
      src(
        'notes',
        0.5,
        'The house lists purple passion fruit, Shangri-la peony and vanilla orchid without a pyramid; vanilla orchid mapped to orchid.',
      ),
      src('price', 0.4, 'Approximate US price for 100 ml in Victoria\'s Secret stores.'),
    ],
    bottleDescription:
      'A rectangular glass bottle with pink-tinted juice, vertical ribbing and a black ribbon tied at the neck.',
    editorial:
      'Bombshell is a straightforward fruity floral: passion fruit and a general tropical juiciness up front, a soft peony middle, then a light musky sweetness. It is one of the best-selling fragrances sold through a single retailer, and the familiarity is part of the point. Longevity is moderate for an EDP.',
    notes: { flat: ['passion-fruit', 'peony', 'orchid'] },
    priceBand: 'accessible',
    priceUsd: 98,
    sizeMl: 100,
    character: {
      opening: { fruity: 0.8, sweet: 0.5, fresh: 0.4 },
      heart: { floral: 0.6, fruity: 0.5, sweet: 0.5, fresh: 0.2 },
      drydown: { sweet: 0.5, clean: 0.4, floral: 0.3, woody: 0.2, creamy: 0.2 },
    },
    phases: { heartAtMin: 10, drydownAtMin: 120 },
    community: {
      tier: 'large',
      rating: 7.0,
      divisiveness: 0.4,
      scent: 7.2,
      performance: 6.5,
      value: 7.8,
      originality: 5.0,
      longevityHrs: 6,
      projection: 3.2,
      projectionLater: 2.4,
      seasons: { spring: 0.85, summer: 0.85, autumn: 0.35, winter: 0.2 },
      time: { day: 0.85, night: 0.5 },
      weather: { hot: 0.8, mild: 0.85, cold: 0.2, rain: 0.3, humid: 0.7 },
      occasions: { office: 0.55, school: 0.7, date: 0.6, formal: 0.3, casual: 0.85, nightlife: 0.55, special: 0.4, outdoors: 0.7 },
      perceived: {
        'passion-fruit': 0.6,
        peony: 0.55,
        musk: 0.45,
        pineapple: 0.35,
        grapefruit: 0.3,
        strawberry: 0.3,
        vanilla: 0.3,
        orchid: 0.2,
      },
      strongestByPhase: { opening: ['passion-fruit', 'pineapple', 'grapefruit'], heart: ['peony', 'passion-fruit'], drydown: ['musk', 'vanilla'] },
    },
    bottle: {
      body: 'tall',
      width: 1.0,
      height: 1.1,
      depth: 0.7,
      glass: 'clear',
      liquid: '#E7A9BC',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'silver',
      capWidth: 0.8,
      capHeight: 0.8,
      collar: 'black',
      label: 'printed',
      labelInk: '#2A2224',
    },
    accent: '#B66E86',
  },

  // 24 ------------------------------------------------------------------ Mitsouko
  {
    slug: 'mitsouko',
    name: 'Mitsouko',
    brand: 'guerlain',
    concentration: 'edp',
    releaseYear: 1919,
    status: 'reformulated',
    marketedFor: 'feminine',
    perfumers: ['jacques-guerlain'],
    style: 'Fruity mossy chypre',
    summary:
      'Bergamot and a soft, velvety peach over a dry, mossy, slightly spicy base. Grown-up, bittersweet and nothing like a modern fruity floral.',
    bestFor: 'Autumn days, rain, dressed-up occasions',
    sources: [
      src('identity', 0.65, 'The 1919 date is the original launch; the EDP concentration was introduced later, so releaseYear refers to the fragrance, not this concentration.'),
      src('notes', 0.45, 'Recorded as bergamot; peach, rose and jasmine; oakmoss. The house also mentions spices and woods, which are not mapped to slugs.'),
      src('perfumers', 0.7, 'Jacques Guerlain is the documented author of the 1919 original.'),
      src(
        'status',
        0.5,
        'Marked reformulated: oakmoss is restricted under IFRA standards and the EU later banned atranol and chloroatranol, its main allergens, so the current formula uses treated or reduced moss. No primary citation could be reached.',
      ),
      src('price', 0.35, 'Approximate US price for 75 ml EDP.'),
    ],
    bottleDescription:
      'A clear glass bottle with arched shoulders and a hollow heart-shaped stopper, holding amber juice.',
    editorial:
      'Mitsouko is one of the founding chypres: citrus over a damp, mossy base, with a famously soft peach note that gives it warmth and a faint melancholy. Today\'s version has had to work around restrictions on oakmoss, so it reads lighter and less inky than vintage descriptions suggest. It still rewards patience, since the drydown is where it makes sense.',
    notes: {
      top: ['bergamot'],
      heart: ['peach', 'rose', 'jasmine'],
      base: ['oakmoss'],
    },
    priceBand: 'premium',
    priceUsd: 160,
    sizeMl: 75,
    character: {
      opening: { fresh: 0.5, fruity: 0.4, earthy: 0.3, spicy: 0.2 },
      heart: { fruity: 0.5, floral: 0.5, earthy: 0.5, spicy: 0.3, woody: 0.3 },
      drydown: { earthy: 0.7, woody: 0.5, warm: 0.3, powdery: 0.2, smoky: 0.1 },
    },
    phases: { heartAtMin: 20, drydownAtMin: 180 },
    community: {
      tier: 'medium',
      rating: 8.0,
      divisiveness: 0.55,
      scent: 8.2,
      performance: 7.0,
      value: 7.5,
      originality: 9.0,
      longevityHrs: 8,
      projection: 3,
      projectionLater: 2.4,
      seasons: { spring: 0.45, summer: 0.2, autumn: 0.9, winter: 0.65 },
      time: { day: 0.7, night: 0.55 },
      weather: { hot: 0.2, mild: 0.8, cold: 0.65, rain: 0.75, humid: 0.2 },
      occasions: { office: 0.6, school: 0.2, date: 0.45, formal: 0.8, casual: 0.35, nightlife: 0.35, special: 0.65, outdoors: 0.3 },
      perceived: {
        oakmoss: 0.75,
        peach: 0.6,
        bergamot: 0.4,
        rose: 0.35,
        cinnamon: 0.3,
        vetiver: 0.25,
        powdery: 0.2,
        jasmine: 0.15,
      },
      strongestByPhase: { opening: ['bergamot', 'peach'], heart: ['peach', 'rose', 'oakmoss', 'cinnamon'], drydown: ['oakmoss', 'vetiver'] },
    },
    bottle: {
      body: 'apothecary',
      width: 1.1,
      height: 0.95,
      glass: 'clear',
      liquid: '#B9884A',
      fill: 0.85,
      cap: 'pebble',
      capMaterial: 'resin',
      capColor: '#E7E0CF',
      capWidth: 1.1,
      capHeight: 1.2,
      collar: 'gold',
      label: 'paper',
      labelColor: '#EDE3CD',
      labelInk: '#5E4429',
    },
    accent: '#8A7044',
  },

  // 25 ------------------------------------------------------------------ Shalimar
  {
    slug: 'shalimar',
    name: 'Shalimar',
    brand: 'guerlain',
    concentration: 'edp',
    releaseYear: 1925,
    status: 'current',
    marketedFor: 'feminine',
    perfumers: ['jacques-guerlain'],
    style: 'Vanilla amber classic',
    summary:
      'A blast of bergamot over smoky vanilla, soft iris and resinous amber. Powdery, a little leathery, and warm for hours.',
    bestFor: 'Winter evenings, formal nights',
    sources: [
      src('identity', 0.65, 'The 1925 date is the original launch; the EDP concentration came later.'),
      src('notes', 0.5, 'Recorded as bergamot and lemon; iris, jasmine and rose; vanilla, tonka bean, opoponax and incense.'),
      src('perfumers', 0.7, 'Jacques Guerlain is the documented author.'),
      src('price', 0.35, 'Approximate US price for 90 ml EDP.'),
    ],
    bottleDescription:
      'A clear glass urn-shaped bottle on a short foot with a large fan-shaped stopper in sapphire-blue glass.',
    editorial:
      'Shalimar is the template for the vanilla amber: a sharp bergamot opening laid over vanilla with a smoky, slightly leathery undertone. The contrast between that bright top and the dense, powdery base is the whole trick, and it still works. It is warm and fairly loud, so it belongs to cold weather and evenings.',
    notes: {
      top: ['bergamot', 'lemon'],
      heart: ['iris', 'jasmine', 'rose'],
      base: ['vanilla', 'tonka-bean', 'opoponax', 'incense'],
    },
    priceBand: 'premium',
    priceUsd: 170,
    sizeMl: 90,
    character: {
      opening: { fresh: 0.6, warm: 0.3, sweet: 0.3, smoky: 0.2 },
      heart: { sweet: 0.5, powdery: 0.5, warm: 0.5, floral: 0.4 },
      drydown: { sweet: 0.7, warm: 0.7, powdery: 0.5, smoky: 0.3, creamy: 0.3 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 180 },
    community: {
      tier: 'large',
      rating: 8.0,
      divisiveness: 0.4,
      scent: 8.1,
      performance: 8.3,
      value: 7.2,
      originality: 8.5,
      longevityHrs: 10,
      projection: 3.6,
      projectionLater: 3,
      seasons: { spring: 0.25, summer: 0.15, autumn: 0.8, winter: 0.95 },
      time: { day: 0.45, night: 0.85 },
      weather: { hot: 0.15, mild: 0.6, cold: 0.95, rain: 0.6, humid: 0.15 },
      occasions: { office: 0.35, school: 0.1, date: 0.75, formal: 0.85, casual: 0.3, nightlife: 0.65, special: 0.85, outdoors: 0.15 },
      perceived: {
        vanilla: 0.9,
        bergamot: 0.6,
        powdery: 0.55,
        incense: 0.4,
        iris: 0.35,
        leather: 0.35,
        opoponax: 0.3,
        'tonka-bean': 0.3,
        lemon: 0.15,
        jasmine: 0.15,
        rose: 0.1,
      },
      strongestByPhase: { opening: ['bergamot', 'lemon'], heart: ['vanilla', 'iris', 'powdery'], drydown: ['vanilla', 'incense', 'leather'] },
    },
    bottle: {
      body: 'apothecary',
      width: 1.3,
      height: 0.85,
      glass: 'clear',
      liquid: '#C59A4E',
      fill: 0.85,
      cap: 'disc',
      capMaterial: 'resin',
      capColor: '#2F4D8A',
      capWidth: 1.4,
      capHeight: 1.3,
      collar: 'silver',
      label: 'printed',
      labelInk: '#B8BFC9',
    },
    accent: '#3E5480',
  },

  // 26 ------------------------------------------------------------------ Aventus
  {
    slug: 'aventus',
    name: 'Aventus',
    brand: 'creed',
    concentration: 'edp',
    releaseYear: 2010,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: ['olivier-creed', 'erwin-creed'],
    style: 'Fruity smoky chypre',
    summary:
      'Juicy pineapple, blackcurrant and bergamot over a dry, smoky birch heart, settling into clean musk and soft moss. Bright, confident, versatile.',
    bestFor: 'Spring and summer days, work, dates',
    sources: [
      src('identity', 0.7),
      src(
        'notes',
        0.55,
        'Recorded pyramid: pineapple, bergamot, blackcurrant, apple; birch, patchouli, Moroccan jasmine, rose; musk, oakmoss, ambergris, vanilla. Apple mapped to green-apple.',
      ),
      src('perfumers', 0.55, 'House credits Olivier Creed and Erwin Creed.'),
      src('price', 0.4, 'Approximate US price for 100 ml.'),
    ],
    bottleDescription:
      'A tall black glass bottle with a heavy silver cap and a silver horse-and-rider emblem on the front.',
    editorial:
      'Aventus took the old fruity chypre idea and gave it a smoky birch spine and a clean musky base, and it became the most talked-about men\'s niche fragrance of the 2010s. Batches are often said to vary, mostly in how much smoke comes through. The pineapple opening is the hook; the clean, slightly mossy drydown is what keeps people wearing it.',
    notes: {
      top: ['pineapple', 'bergamot', 'blackcurrant', 'green-apple'],
      heart: ['birch', 'patchouli', 'jasmine', 'rose'],
      base: ['musk', 'oakmoss', 'ambergris', 'vanilla'],
    },
    priceBand: 'luxury',
    priceUsd: 495,
    sizeMl: 100,
    character: {
      opening: { fruity: 0.7, fresh: 0.6, sweet: 0.3, smoky: 0.2 },
      heart: { smoky: 0.5, woody: 0.5, fruity: 0.4, fresh: 0.3 },
      drydown: { woody: 0.6, clean: 0.5, smoky: 0.3, earthy: 0.2, warm: 0.2 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 150 },
    community: {
      tier: 'huge',
      rating: 8.0,
      divisiveness: 0.35,
      scent: 8.3,
      performance: 7.4,
      value: 4.5,
      originality: 7.5,
      longevityHrs: 8,
      projection: 3.5,
      projectionLater: 2.8,
      seasons: { spring: 0.85, summer: 0.75, autumn: 0.6, winter: 0.35 },
      time: { day: 0.9, night: 0.55 },
      weather: { hot: 0.65, mild: 0.9, cold: 0.45, rain: 0.45, humid: 0.5 },
      occasions: { office: 0.8, school: 0.4, date: 0.75, formal: 0.7, casual: 0.7, nightlife: 0.55, special: 0.7, outdoors: 0.6 },
      perceived: {
        pineapple: 0.85,
        birch: 0.55,
        musk: 0.5,
        blackcurrant: 0.45,
        bergamot: 0.45,
        'green-apple': 0.3,
        ambergris: 0.3,
        leather: 0.3,
        oakmoss: 0.25,
        patchouli: 0.15,
      },
      strongestByPhase: { opening: ['pineapple', 'bergamot', 'blackcurrant'], heart: ['birch', 'pineapple', 'leather'], drydown: ['musk', 'ambergris', 'oakmoss'] },
    },
    bottle: {
      body: 'tall',
      width: 0.95,
      height: 1.2,
      depth: 0.8,
      glass: 'smoked',
      glassTint: '#232323',
      liquid: '#C9C1A0',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'silver',
      capWidth: 1.1,
      capHeight: 1.1,
      collar: 'silver',
      label: 'printed',
      labelInk: '#C7C9CC',
    },
    accent: '#5C5A4A',
  },

  // 27 ------------------------------------------------------------------ Baccarat Rouge 540
  {
    slug: 'baccarat-rouge-540',
    name: 'Baccarat Rouge 540',
    brand: 'maison-francis-kurkdjian',
    concentration: 'edp',
    releaseYear: 2015,
    status: 'current',
    marketedFor: 'shared',
    perfumers: ['francis-kurkdjian'],
    style: 'Airy amber woods',
    summary:
      'Saffron and a burnt-sugar sweetness over a glowing, mineral amber and dry cedar. Light in texture, huge in reach, and very long lasting.',
    bestFor: 'Evenings out, cool weather, special plans',
    sources: [
      src('identity', 0.7, 'Created in 2014 for a Baccarat crystal project; the MFK eau de parfum launched in 2015.'),
      src('notes', 0.5, 'House lists notes without a pyramid: jasmine, saffron, amberwood/ambergris, fir resin, cedar. Amberwood mapped to ambergris.'),
      src('perfumers', 0.7, 'Francis Kurkdjian, founder of the house.'),
      src('price', 0.4, 'Approximate US price for 70 ml.'),
    ],
    bottleDescription:
      'A clear rectangular glass bottle with a squared gold cap, holding pale rosy-amber juice.',
    editorial:
      'Baccarat Rouge 540 smells sweet without being heavy: saffron and a caramelised, almost burnt-sugar effect sit on top of a bright, mineral amber woods base. Its reach is enormous, and it became one of the most recognised scents of the 2020s, which means plenty of people will know what you are wearing. Some noses find it sharp or metallic rather than warm.',
    notes: { flat: ['jasmine', 'saffron', 'ambergris', 'fir-resin', 'cedarwood'] },
    priceBand: 'luxury',
    priceUsd: 335,
    sizeMl: 70,
    character: {
      opening: { sweet: 0.5, warm: 0.5, spicy: 0.3, woody: 0.3 },
      heart: { warm: 0.6, sweet: 0.5, woody: 0.5, floral: 0.2 },
      drydown: { warm: 0.7, woody: 0.6, sweet: 0.4, clean: 0.2 },
    },
    phases: { heartAtMin: 10, drydownAtMin: 120 },
    community: {
      tier: 'huge',
      rating: 7.6,
      divisiveness: 0.6,
      scent: 7.6,
      performance: 9.0,
      value: 4.2,
      originality: 8.0,
      longevityHrs: 12,
      projection: 4,
      projectionLater: 3.6,
      seasons: { spring: 0.5, summer: 0.35, autumn: 0.85, winter: 0.8 },
      time: { day: 0.6, night: 0.8 },
      weather: { hot: 0.35, mild: 0.8, cold: 0.8, rain: 0.5, humid: 0.35 },
      occasions: { office: 0.45, school: 0.2, date: 0.85, formal: 0.75, casual: 0.5, nightlife: 0.8, special: 0.8, outdoors: 0.3 },
      perceived: {
        ambroxan: 0.7,
        saffron: 0.55,
        caramel: 0.55,
        ambergris: 0.45,
        cedarwood: 0.4,
        metallic: 0.35,
        jasmine: 0.25,
        'fir-resin': 0.15,
      },
      strongestByPhase: { opening: ['saffron', 'caramel', 'jasmine'], heart: ['ambroxan', 'caramel', 'metallic'], drydown: ['ambroxan', 'cedarwood', 'ambergris'] },
    },
    bottle: {
      body: 'block',
      width: 0.9,
      height: 1.1,
      glass: 'clear',
      liquid: '#E6B9A0',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'gold',
      capWidth: 0.9,
      capHeight: 0.8,
      collar: 'gold',
      label: 'printed',
      labelInk: '#3B2C22',
    },
    accent: '#A8634F',
  },

  // 28 ------------------------------------------------------------------ Santal 33
  {
    slug: 'santal-33',
    name: 'Santal 33',
    brand: 'le-labo',
    concentration: 'edp',
    releaseYear: 2011,
    status: 'current',
    marketedFor: 'shared',
    perfumers: ['frank-voelkl'],
    style: 'Dry leathery sandalwood',
    summary:
      'Dry sandalwood and cedar with a pinch of cardamom and a worn-leather edge. Creamy, woody and a little sour, it reads like warm skin.',
    bestFor: 'Everyday wear in cool, mild weather',
    sources: [
      src('identity', 0.7),
      src(
        'notes',
        0.55,
        'Le Labo lists notes without a pyramid: cardamom, iris, violet, ambrox, Australian sandalwood, papyrus, cedarwood, leather accord.',
      ),
      src('perfumers', 0.6, 'Frank Voelkl is the widely documented author.'),
      src('price', 0.4, 'Approximate US price for 100 ml.'),
    ],
    bottleDescription:
      'A plain clear cylindrical lab-style bottle with a black cap and a typed paper label personalised at purchase.',
    editorial:
      'Santal 33 is the sandalwood that defined a decade of niche: a dry, slightly sour, leathery wood with a cardamom lift, far from the milky sandalwood of older perfumes. It became so common in certain cities that it now reads as a social signal as much as a scent. On skin it sits close after the first hour and lasts well.',
    notes: {
      flat: ['cardamom', 'iris', 'violet', 'ambroxan', 'sandalwood', 'papyrus', 'cedarwood', 'leather'],
    },
    priceBand: 'luxury',
    priceUsd: 330,
    sizeMl: 100,
    character: {
      opening: { woody: 0.6, spicy: 0.3, earthy: 0.2, smoky: 0.2 },
      heart: { woody: 0.8, creamy: 0.4, powdery: 0.2, smoky: 0.2 },
      drydown: { woody: 0.8, creamy: 0.4, warm: 0.3, earthy: 0.2 },
    },
    phases: { heartAtMin: 10, drydownAtMin: 120 },
    community: {
      tier: 'huge',
      rating: 7.4,
      divisiveness: 0.55,
      scent: 7.4,
      performance: 8.0,
      value: 4.5,
      originality: 7.0,
      longevityHrs: 9,
      projection: 3.5,
      projectionLater: 3,
      seasons: { spring: 0.6, summer: 0.4, autumn: 0.85, winter: 0.65 },
      time: { day: 0.8, night: 0.55 },
      weather: { hot: 0.4, mild: 0.85, cold: 0.65, rain: 0.6, humid: 0.35 },
      occasions: { office: 0.75, school: 0.4, date: 0.55, formal: 0.45, casual: 0.8, nightlife: 0.45, special: 0.45, outdoors: 0.5 },
      perceived: {
        sandalwood: 0.85,
        cedarwood: 0.55,
        leather: 0.5,
        cardamom: 0.45,
        'iso-e-super': 0.3,
        papyrus: 0.25,
        ambroxan: 0.2,
        iris: 0.2,
        violet: 0.1,
      },
      strongestByPhase: { opening: ['cardamom', 'cedarwood', 'leather'], heart: ['sandalwood', 'leather'], drydown: ['sandalwood', 'cedarwood', 'iso-e-super'] },
    },
    bottle: {
      body: 'cylinder',
      width: 0.9,
      height: 1.1,
      glass: 'clear',
      liquid: '#E8DCC0',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'black',
      capWidth: 1.0,
      capHeight: 0.9,
      collar: 'black',
      label: 'paper',
      labelColor: '#F1EDE4',
      labelInk: '#222222',
    },
    accent: '#8E7356',
  },

  // 29 ------------------------------------------------------------------ Gypsy Water
  {
    slug: 'gypsy-water',
    name: 'Gypsy Water',
    brand: 'byredo',
    concentration: 'edp',
    releaseYear: 2008,
    status: 'current',
    marketedFor: 'shared',
    perfumers: ['jerome-epinette'],
    style: 'Soft woody aromatic',
    summary:
      'Bergamot, juniper and pepper over pine needles and a wisp of incense, drying down to soft vanilla and sandalwood. Calm, clean and outdoorsy.',
    bestFor: 'Relaxed days, spring and autumn walks',
    sources: [
      src('identity', 0.65),
      src(
        'notes',
        0.55,
        'Recorded pyramid: bergamot, lemon, pepper, juniper berries; incense, pine needles, orris; amber, vanilla, sandalwood. Pepper mapped to black-pepper.',
      ),
      src('perfumers', 0.45, 'Byredo does not usually credit perfumers; Jérôme Epinette is widely associated with its early catalogue.'),
      src('price', 0.4, 'Approximate US price for 100 ml.'),
    ],
    bottleDescription:
      'A simple clear cylindrical glass bottle with a chunky matte-black cap and a white paper label in plain black type.',
    editorial:
      'Gypsy Water is a quiet, soft-focus woody scent: citrus and juniper up top, then pine and a little incense, ending in a gentle vanilla-sandalwood base. It is easy to wear and rarely offends anyone. The trade-off is modest staying power for the price, so expect to reapply.',
    notes: {
      top: ['bergamot', 'lemon', 'black-pepper', 'juniper-berry'],
      heart: ['incense', 'pine', 'iris'],
      base: ['amber', 'vanilla', 'sandalwood'],
    },
    priceBand: 'luxury',
    priceUsd: 285,
    sizeMl: 100,
    character: {
      opening: { fresh: 0.6, green: 0.3, spicy: 0.3, woody: 0.3 },
      heart: { woody: 0.5, smoky: 0.3, green: 0.3, powdery: 0.2 },
      drydown: { woody: 0.5, sweet: 0.4, warm: 0.4, creamy: 0.3 },
    },
    phases: { heartAtMin: 10, drydownAtMin: 120 },
    community: {
      tier: 'large',
      rating: 7.4,
      divisiveness: 0.35,
      scent: 7.6,
      performance: 5.5,
      value: 4.8,
      originality: 7.0,
      longevityHrs: 5,
      projection: 2.6,
      projectionLater: 2,
      seasons: { spring: 0.8, summer: 0.6, autumn: 0.7, winter: 0.35 },
      time: { day: 0.85, night: 0.4 },
      weather: { hot: 0.5, mild: 0.9, cold: 0.45, rain: 0.55, humid: 0.4 },
      occasions: { office: 0.8, school: 0.5, date: 0.55, formal: 0.4, casual: 0.85, nightlife: 0.3, special: 0.4, outdoors: 0.7 },
      perceived: {
        bergamot: 0.5,
        pine: 0.5,
        vanilla: 0.5,
        sandalwood: 0.4,
        lemon: 0.35,
        'juniper-berry': 0.35,
        incense: 0.3,
        soapy: 0.3,
        amber: 0.25,
        'black-pepper': 0.2,
        iris: 0.15,
      },
      strongestByPhase: { opening: ['bergamot', 'lemon', 'juniper-berry'], heart: ['pine', 'incense', 'soapy'], drydown: ['vanilla', 'sandalwood'] },
    },
    bottle: {
      body: 'cylinder',
      width: 1.0,
      height: 1.05,
      glass: 'clear',
      liquid: '#EFE7D6',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'black',
      capWidth: 1.15,
      capHeight: 1.1,
      collar: 'none',
      label: 'paper',
      labelColor: '#F4F2EC',
      labelInk: '#1E1E1E',
    },
    accent: '#7C8466',
  },

  // 30 ------------------------------------------------------------------ Philosykos
  {
    slug: 'philosykos',
    name: 'Philosykos',
    brand: 'diptyque',
    concentration: 'edt',
    releaseYear: 1996,
    status: 'current',
    marketedFor: 'shared',
    perfumers: ['olivia-giacobetti'],
    style: 'Green milky fig',
    summary:
      'Crushed fig leaves, green and sappy, with the milky sweetness of the fruit and a dry cedar base. Like standing in the shade of a fig tree.',
    bestFor: 'Hot days, holidays, easy daytime wear',
    sources: [
      src('identity', 0.7, 'EDT from 1996; an EDP version followed years later.'),
      src(
        'notes',
        0.5,
        'Recorded as fig leaf; fig; fig tree wood and white cedar. Fig tree wood has no slug and is folded into cedarwood.',
      ),
      src('perfumers', 0.65, 'Olivia Giacobetti is the widely documented author.'),
      src('price', 0.4, 'Approximate US price for 100 ml EDT.'),
    ],
    bottleDescription:
      'A flat, clear glass bottle bearing Diptyque\'s oval black-and-white label with the name in dancing letters.',
    editorial:
      'Philosykos treats fig as a whole tree rather than a fruit: bitter green leaves, a little milky sap, then dry wood. It is sheer and naturalistic, which makes it lovely in heat and a bit faint everywhere else. It has been widely imitated, but the balance of green and creamy here is still hard to beat.',
    notes: {
      top: ['fig-leaf'],
      heart: ['fig'],
      base: ['cedarwood'],
    },
    priceBand: 'premium',
    priceUsd: 175,
    sizeMl: 100,
    character: {
      opening: { green: 0.8, fresh: 0.4, fruity: 0.2 },
      heart: { green: 0.6, creamy: 0.4, fruity: 0.4, woody: 0.3 },
      drydown: { woody: 0.6, creamy: 0.4, green: 0.3, earthy: 0.2 },
    },
    phases: { heartAtMin: 10, drydownAtMin: 90 },
    community: {
      tier: 'medium',
      rating: 7.6,
      divisiveness: 0.35,
      scent: 7.9,
      performance: 5.2,
      value: 6.2,
      originality: 7.8,
      longevityHrs: 5,
      projection: 2.4,
      projectionLater: 1.8,
      seasons: { spring: 0.8, summer: 0.85, autumn: 0.35, winter: 0.15 },
      time: { day: 0.9, night: 0.25 },
      weather: { hot: 0.8, mild: 0.85, cold: 0.15, rain: 0.4, humid: 0.6 },
      occasions: { office: 0.75, school: 0.5, date: 0.4, formal: 0.3, casual: 0.9, nightlife: 0.15, special: 0.3, outdoors: 0.75 },
      perceived: {
        'fig-leaf': 0.85,
        fig: 0.55,
        cedarwood: 0.45,
        coconut: 0.35,
        milk: 0.3,
        'cut-grass': 0.2,
      },
      strongestByPhase: { opening: ['fig-leaf', 'cut-grass'], heart: ['fig-leaf', 'fig', 'coconut'], drydown: ['cedarwood', 'milk'] },
    },
    bottle: {
      body: 'flask',
      width: 0.9,
      height: 1.1,
      depth: 0.6,
      glass: 'clear',
      liquid: '#E3E2C8',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'white',
      capWidth: 0.8,
      capHeight: 0.8,
      collar: 'none',
      label: 'paper',
      labelColor: '#F3F1EA',
      labelInk: '#151515',
    },
    accent: '#6F7F55',
  },

  // 31 ------------------------------------------------------------------ Tobacco Vanille
  {
    slug: 'tobacco-vanille',
    name: 'Tobacco Vanille',
    brand: 'tom-ford',
    concentration: 'edp',
    releaseYear: 2007,
    status: 'current',
    marketedFor: 'shared',
    perfumers: ['olivier-gillotin'],
    style: 'Sweet tobacco vanilla',
    summary:
      'Honeyed pipe tobacco and spice melt into thick vanilla, tonka, cocoa and dried fruit. Rich, boozy-sweet and very long lasting.',
    bestFor: 'Cold nights, winter evenings out',
    sources: [
      src('identity', 0.7, 'Launched with the first Private Blend collection in 2007.'),
      src(
        'notes',
        0.5,
        'Recorded as tobacco leaf and spicy notes; tonka bean, tobacco blossom, vanilla, cacao; dried fruits and woody notes. Generic spice and wood notes are not mapped to slugs.',
      ),
      src('perfumers', 0.6, 'Olivier Gillotin is the widely documented author.'),
      src('price', 0.4, 'Approximate US price for 50 ml.'),
    ],
    bottleDescription:
      'A squared, heavy glass bottle tinted deep chocolate brown, with a gold plate label and a dark brown cap.',
    editorial:
      'Tobacco Vanille is about as straightforward as luxury perfume gets: sweet, honeyed tobacco leaf and a lot of vanilla, with cocoa and dried fruit thickening the middle. It is warm, loud and lasts all evening. In cold weather it is comforting; in heat it can feel like wearing a dessert trolley.',
    notes: {
      top: ['tobacco'],
      heart: ['tonka-bean', 'vanilla', 'cacao'],
      base: ['dried-fruit'],
    },
    priceBand: 'luxury',
    priceUsd: 295,
    sizeMl: 50,
    character: {
      opening: { warm: 0.6, sweet: 0.6, spicy: 0.4, smoky: 0.3 },
      heart: { sweet: 0.8, warm: 0.7, smoky: 0.3, creamy: 0.3, fruity: 0.2 },
      drydown: { sweet: 0.8, warm: 0.8, creamy: 0.4, woody: 0.2, smoky: 0.2 },
    },
    phases: { heartAtMin: 15, drydownAtMin: 240 },
    community: {
      tier: 'large',
      rating: 8.0,
      divisiveness: 0.4,
      scent: 8.2,
      performance: 8.8,
      value: 5.0,
      originality: 7.2,
      longevityHrs: 11,
      projection: 4,
      projectionLater: 3.5,
      seasons: { spring: 0.15, summer: 0.05, autumn: 0.85, winter: 0.98 },
      time: { day: 0.4, night: 0.85 },
      weather: { hot: 0.05, mild: 0.45, cold: 0.97, rain: 0.55, humid: 0.05 },
      occasions: { office: 0.25, school: 0.1, date: 0.75, formal: 0.55, casual: 0.35, nightlife: 0.7, special: 0.65, outdoors: 0.2 },
      perceived: {
        tobacco: 0.85,
        vanilla: 0.85,
        'tonka-bean': 0.5,
        'dried-fruit': 0.5,
        cacao: 0.35,
        honey: 0.35,
        clove: 0.2,
      },
      strongestByPhase: { opening: ['tobacco', 'clove', 'honey'], heart: ['tobacco', 'vanilla', 'dried-fruit'], drydown: ['vanilla', 'tonka-bean', 'cacao'] },
    },
    bottle: {
      body: 'block',
      width: 0.9,
      height: 1.1,
      glass: 'smoked',
      glassTint: '#3A2418',
      liquid: '#6B3F22',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'resin',
      capColor: '#2C1B12',
      capWidth: 0.9,
      capHeight: 0.8,
      collar: 'gold',
      label: 'plate',
      labelColor: '#B6965A',
      labelInk: '#2C1B12',
    },
    accent: '#7A5034',
  },

  // 32 ------------------------------------------------------------------ Oud Wood
  {
    slug: 'oud-wood',
    name: 'Oud Wood',
    brand: 'tom-ford',
    concentration: 'edp',
    releaseYear: 2007,
    status: 'current',
    marketedFor: 'shared',
    perfumers: ['richard-herpin'],
    style: 'Smooth spiced oud',
    summary:
      'Cardamom and zesty pepper over a smooth, polished oud with sandalwood and vetiver, softening into warm tonka and amber. Woody, never funky.',
    bestFor: 'Office, dinners, autumn and winter',
    sources: [
      src('identity', 0.7, 'Launched with the first Private Blend collection in 2007.'),
      src(
        'notes',
        0.5,
        'Recorded pyramid: rosewood, cardamom, Chinese pepper; oud, sandalwood, vetiver; tonka bean, vanilla, amber. Chinese pepper mapped to sichuan-pepper.',
      ),
      src('perfumers', 0.6, 'Richard Herpin is the widely documented author.'),
      src('price', 0.4, 'Approximate US price for 50 ml.'),
    ],
    bottleDescription:
      'A squared, heavy glass bottle tinted dark smoky brown, with a gold plate label and a dark cap.',
    editorial:
      'Oud Wood introduced a lot of Western wearers to oud by leaving out the barnyard: what you get is a smooth, dry wood with cardamom and pepper on top and a soft amber base. It is quiet and polished, closer to a well-cut jacket than a statement. Projection is moderate, which suits offices and dinners.',
    notes: {
      top: ['rosewood', 'cardamom', 'sichuan-pepper'],
      heart: ['oud', 'sandalwood', 'vetiver'],
      base: ['tonka-bean', 'vanilla', 'amber'],
    },
    priceBand: 'luxury',
    priceUsd: 295,
    sizeMl: 50,
    character: {
      opening: { spicy: 0.5, woody: 0.5, fresh: 0.2 },
      heart: { woody: 0.8, warm: 0.4, smoky: 0.3, spicy: 0.2 },
      drydown: { woody: 0.7, warm: 0.5, sweet: 0.3, creamy: 0.3 },
    },
    phases: { heartAtMin: 10, drydownAtMin: 120 },
    community: {
      tier: 'large',
      rating: 7.9,
      divisiveness: 0.3,
      scent: 8.1,
      performance: 6.8,
      value: 5.0,
      originality: 6.5,
      longevityHrs: 7,
      projection: 3,
      projectionLater: 2.4,
      seasons: { spring: 0.45, summer: 0.25, autumn: 0.9, winter: 0.75 },
      time: { day: 0.65, night: 0.7 },
      weather: { hot: 0.2, mild: 0.8, cold: 0.75, rain: 0.65, humid: 0.2 },
      occasions: { office: 0.8, school: 0.25, date: 0.7, formal: 0.8, casual: 0.5, nightlife: 0.5, special: 0.65, outdoors: 0.25 },
      perceived: {
        oud: 0.6,
        cardamom: 0.5,
        sandalwood: 0.45,
        rosewood: 0.35,
        'tonka-bean': 0.35,
        amber: 0.35,
        vetiver: 0.3,
        leather: 0.2,
        'sichuan-pepper': 0.15,
        vanilla: 0.15,
      },
      strongestByPhase: { opening: ['cardamom', 'rosewood', 'sichuan-pepper'], heart: ['oud', 'sandalwood'], drydown: ['oud', 'amber', 'tonka-bean'] },
    },
    bottle: {
      body: 'block',
      width: 0.9,
      height: 1.1,
      glass: 'smoked',
      glassTint: '#33261D',
      liquid: '#7A5332',
      fill: 0.85,
      cap: 'cube',
      capMaterial: 'resin',
      capColor: '#221811',
      capWidth: 0.9,
      capHeight: 0.8,
      collar: 'gold',
      label: 'plate',
      labelColor: '#B6965A',
      labelInk: '#221811',
    },
    accent: '#6A5240',
  },

  // 33 ------------------------------------------------------------------ Replica Jazz Club
  {
    slug: 'jazz-club',
    name: 'Replica Jazz Club',
    brand: 'maison-margiela',
    concentration: 'edt',
    releaseYear: 2013,
    status: 'current',
    marketedFor: 'masculine',
    perfumers: ['alienor-massenet'],
    style: 'Boozy tobacco vanilla',
    summary:
      'Pink pepper and lemon give way to sweet rum and tobacco leaf, settling into a soft vanilla and styrax warmth. Cosy, boozy and mellow.',
    bestFor: 'Evenings, bars, cold-weather dates',
    sources: [
      src('identity', 0.65),
      src(
        'notes',
        0.5,
        'Recorded pyramid: pink pepper, neroli, lemon; rum, clary sage, Java vetiver oil; tobacco leaf, vanilla bean, styrax.',
      ),
      src('perfumers', 0.6, 'Alienor Massenet is the widely documented author.'),
      src('price', 0.4, 'Approximate US price for 100 ml.'),
    ],
    bottleDescription:
      'A clear, rounded rectangular glass bottle of amber juice with a white cotton label stitched on at the corners.',
    editorial:
      'Jazz Club takes the rum-and-tobacco idea and keeps it light enough for everyday evenings: a spritz of pepper and citrus, then sweet boozy tobacco and a soft vanilla finish. It is friendlier and less dense than the luxury tobacco scents it gets compared with. Longevity is decent for an EDT, though it stays fairly close after a couple of hours.',
    notes: {
      top: ['pink-pepper', 'neroli', 'lemon'],
      heart: ['rum', 'clary-sage', 'vetiver'],
      base: ['tobacco', 'vanilla', 'styrax'],
    },
    priceBand: 'premium',
    priceUsd: 165,
    sizeMl: 100,
    character: {
      opening: { spicy: 0.4, fresh: 0.4, sweet: 0.3, warm: 0.3 },
      heart: { warm: 0.6, sweet: 0.5, smoky: 0.3, woody: 0.2 },
      drydown: { sweet: 0.7, warm: 0.7, smoky: 0.3, creamy: 0.3 },
    },
    phases: { heartAtMin: 10, drydownAtMin: 120 },
    community: {
      tier: 'large',
      rating: 7.6,
      divisiveness: 0.35,
      scent: 7.8,
      performance: 6.5,
      value: 6.5,
      originality: 6.5,
      longevityHrs: 7,
      projection: 3,
      projectionLater: 2.3,
      seasons: { spring: 0.25, summer: 0.1, autumn: 0.9, winter: 0.85 },
      time: { day: 0.45, night: 0.85 },
      weather: { hot: 0.1, mild: 0.65, cold: 0.9, rain: 0.6, humid: 0.1 },
      occasions: { office: 0.45, school: 0.2, date: 0.8, formal: 0.5, casual: 0.55, nightlife: 0.8, special: 0.5, outdoors: 0.15 },
      perceived: {
        rum: 0.75,
        tobacco: 0.65,
        vanilla: 0.65,
        boozy: 0.6,
        'pink-pepper': 0.35,
        honey: 0.25,
        styrax: 0.2,
        vetiver: 0.2,
        lemon: 0.15,
        'clary-sage': 0.1,
        neroli: 0.1,
      },
      strongestByPhase: { opening: ['pink-pepper', 'boozy', 'lemon'], heart: ['rum', 'tobacco'], drydown: ['vanilla', 'tobacco'] },
    },
    bottle: {
      body: 'flask',
      width: 1.0,
      height: 1.05,
      depth: 0.7,
      glass: 'clear',
      liquid: '#C58A45',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'black',
      capWidth: 0.8,
      capHeight: 0.8,
      collar: 'none',
      label: 'paper',
      labelColor: '#F2F0EA',
      labelInk: '#2A2A2A',
    },
    accent: '#8A6038',
  },

  // 34 ------------------------------------------------------------------ Replica Lazy Sunday Morning
  {
    slug: 'lazy-sunday-morning',
    name: 'Replica Lazy Sunday Morning',
    brand: 'maison-margiela',
    concentration: 'edt',
    releaseYear: 2013,
    status: 'current',
    marketedFor: 'shared',
    perfumers: ['louise-turner'],
    style: 'Clean laundry musk',
    summary:
      'Aldehydes and a touch of pear, then lily of the valley and iris over soft, clean musk. Smells like fresh sheets and warm skin.',
    bestFor: 'Work, weekends, anyone who wants clean',
    sources: [
      src('identity', 0.65),
      src(
        'notes',
        0.45,
        'Recorded pyramid: aldehydes, pear; lily of the valley, iris, rose; white musk, ambrette, patchouli. Placement of lily of the valley and the minor notes is uncertain.',
      ),
      src('perfumers', 0.55, 'Louise Turner is the widely documented author.'),
      src('price', 0.4, 'Approximate US price for 100 ml.'),
    ],
    bottleDescription:
      'A clear, rounded rectangular glass bottle of nearly colourless juice with a white cotton label stitched on at the corners.',
    editorial:
      'Lazy Sunday Morning is a clean-laundry musk done with a light touch: a soapy, aldehydic opening, a soft floral middle, then musk that sits close to the skin. It is one of the easiest fragrances to wear around other people. If you want presence, look elsewhere; this one is for you and whoever leans in.',
    notes: {
      top: ['aldehydes', 'pear'],
      heart: ['lily-of-the-valley', 'iris', 'rose'],
      base: ['musk', 'ambrette', 'patchouli'],
    },
    priceBand: 'premium',
    priceUsd: 165,
    sizeMl: 100,
    character: {
      opening: { clean: 0.7, fresh: 0.5, fruity: 0.3 },
      heart: { clean: 0.7, floral: 0.5, powdery: 0.4 },
      drydown: { clean: 0.8, powdery: 0.4, creamy: 0.3, floral: 0.2 },
    },
    phases: { heartAtMin: 10, drydownAtMin: 90 },
    community: {
      tier: 'medium',
      rating: 7.3,
      divisiveness: 0.3,
      scent: 7.5,
      performance: 5.3,
      value: 6.5,
      originality: 6.0,
      longevityHrs: 5,
      projection: 2.4,
      projectionLater: 1.8,
      seasons: { spring: 0.9, summer: 0.7, autumn: 0.45, winter: 0.3 },
      time: { day: 0.9, night: 0.3 },
      weather: { hot: 0.6, mild: 0.9, cold: 0.3, rain: 0.5, humid: 0.5 },
      occasions: { office: 0.85, school: 0.7, date: 0.45, formal: 0.4, casual: 0.85, nightlife: 0.15, special: 0.3, outdoors: 0.5 },
      perceived: {
        musk: 0.8,
        laundry: 0.7,
        aldehydes: 0.45,
        'lily-of-the-valley': 0.4,
        pear: 0.35,
        iris: 0.35,
        ambrette: 0.2,
        rose: 0.15,
      },
      strongestByPhase: { opening: ['aldehydes', 'pear', 'laundry'], heart: ['lily-of-the-valley', 'iris', 'musk'], drydown: ['musk', 'laundry'] },
    },
    bottle: {
      body: 'flask',
      width: 1.0,
      height: 1.05,
      depth: 0.7,
      glass: 'clear',
      liquid: '#EFE9DA',
      fill: 0.85,
      cap: 'cylinder',
      capMaterial: 'black',
      capWidth: 0.8,
      capHeight: 0.8,
      collar: 'none',
      label: 'paper',
      labelColor: '#F2F0EA',
      labelInk: '#2A2A2A',
    },
    accent: '#9C9A8C',
  },
];
