import type { SeedNote } from '../types';

/**
 * Notes used by group C fragrances that have no honest match in notes.ts.
 * Written in our own words. Follows src/seed/VOICE.md.
 */
export const NOTES_EXTRA_C: SeedNote[] = [
  {
    slug: 'green-mango',
    name: 'Green mango',
    kind: 'accord',
    family: 'fruity',
    aliases: ['unripe mango', 'mango'],
    smellsLike:
      'Sour, leafy and a little resinous, like the skin of an unripe mango rather than the sweet orange flesh.',
    origin:
      'Built by the perfumer, usually from citrus, green and fruity molecules, since mango gives no usable essential oil.',
    contributes:
      'A tart, juicy green opening that reads fruity without turning tropical or sugary.',
    synthetic: true,
    volatility: 'top',
    character: { fruity: 0.6, green: 0.6, fresh: 0.5 },
    hue: '#9DAA6A',
  },
  {
    slug: 'lotus',
    name: 'Lotus',
    kind: 'accord',
    family: 'floral',
    aliases: ['lotus flower', 'water lily'],
    smellsLike:
      'A pale, watery floral with a faint powdery sweetness, closer to clean water and petals than to a heady bouquet.',
    origin:
      'An accord. Lotus extracts exist but are rare and faint, so the effect is usually recreated with aquatic and light floral molecules.',
    contributes: 'Adds a cool, transparent floral layer that keeps a composition airy.',
    synthetic: 'both',
    volatility: 'heart',
    character: { floral: 0.5, fresh: 0.5, clean: 0.4 },
    hue: '#D9C3C8',
  },
  {
    slug: 'sycamore',
    name: 'Sycamore',
    kind: 'accord',
    family: 'woody',
    aliases: ['sycamore wood', 'sycamore fig wood'],
    smellsLike: 'Dry, pale, slightly milky wood, like fresh-cut light timber.',
    origin:
      'A fantasy wood accord. Sycamore does not yield a perfume oil, so it is built from soft woody and musky materials.',
    contributes: 'A quiet, clean woody base that stays in the background.',
    synthetic: true,
    volatility: 'base',
    character: { woody: 0.6, clean: 0.3, creamy: 0.2 },
    hue: '#B9A88A',
  },
  {
    slug: 'coriander',
    name: 'Coriander',
    kind: 'material',
    family: 'spice',
    aliases: ['coriander seed'],
    smellsLike:
      'Warm, lightly spicy and a bit citrusy, like crushed coriander seeds. Not the soapy taste of the fresh leaf.',
    origin: 'Steam-distilled from the dried seeds of the coriander plant. Its main component is linalool.',
    contributes: 'Adds a soft, peppery-citrus sparkle to openings and links citrus to florals.',
    synthetic: false,
    volatility: 'top',
    character: { spicy: 0.5, fresh: 0.4, woody: 0.1 },
    hue: '#B89E6A',
  },
  {
    slug: 'marshmallow',
    name: 'Marshmallow',
    kind: 'accord',
    family: 'gourmand',
    aliases: ['guimauve'],
    smellsLike: 'Soft, powdery sugar with a hint of vanilla and orange blossom, like a bag of fresh marshmallows.',
    origin:
      'A gourmand accord built from sweet molecules such as ethyl maltol, vanillin and heliotropin, often with a floral touch.',
    contributes: 'A fluffy, sugary softness that rounds off florals and makes a base feel cosy.',
    synthetic: true,
    volatility: 'base',
    character: { sweet: 0.8, creamy: 0.5, powdery: 0.4 },
    hue: '#E6D3CF',
  },
  {
    slug: 'date',
    name: 'Date',
    kind: 'accord',
    family: 'fruity',
    aliases: ['dates', 'date fruit'],
    smellsLike: 'Dark, sticky and caramel-like, like a ripe Medjool date with a slightly winey edge.',
    origin: 'An accord built from fruity, caramelic and lactonic molecules. Date fruit gives no perfume oil.',
    contributes: 'Adds a dense, dried-fruit sweetness that pairs with spice, amber and vanilla.',
    synthetic: true,
    volatility: 'heart',
    character: { sweet: 0.7, fruity: 0.5, warm: 0.4 },
    hue: '#7A4A2E',
  },
  {
    slug: 'rubber',
    name: 'Rubber',
    kind: 'accord',
    family: 'leather',
    aliases: ['vulcanised rubber', 'tyre'],
    smellsLike:
      'Like a new bicycle inner tube or a box of rubber bands: slightly smoky, dense and a little sweet.',
    origin:
      'An accord, usually built from smoky, tarry and leathery materials such as birch tar or cade.',
    contributes: 'Gives an urban, industrial darkness and makes leather or tea notes feel unusual.',
    synthetic: true,
    volatility: 'heart',
    character: { smoky: 0.6, earthy: 0.3, warm: 0.2 },
    hue: '#3E3B38',
  },
  {
    slug: 'driftwood',
    name: 'Driftwood',
    kind: 'accord',
    family: 'woody',
    aliases: ['drift wood'],
    smellsLike: 'Sun-bleached, salty, dry wood, as if it had been lying on a beach for a summer.',
    origin: 'A fantasy accord made from dry woody molecules, often with a mineral or ambery touch.',
    contributes: 'A light, dry woody base that suits aquatic and fresh compositions.',
    synthetic: true,
    volatility: 'base',
    character: { woody: 0.6, fresh: 0.2, clean: 0.2 },
    hue: '#A89A86',
  },
  {
    slug: 'amberwood',
    name: 'Amberwood',
    kind: 'accord',
    family: 'woody',
    aliases: ['amber wood', 'ambery woods', 'ambery wood'],
    smellsLike:
      'Dry, radiant and slightly scratchy woodiness with a warm, ambery glow. Very long-lasting, sometimes sharp.',
    origin:
      'Built from modern synthetic woody-amber molecules (the family that includes materials sold under names like Ambrocenide and Norlimbanol).',
    contributes: 'Adds lift, diffusion and staying power to a base, often making a scent feel bigger than it is.',
    synthetic: true,
    volatility: 'base',
    character: { woody: 0.7, warm: 0.4, clean: 0.2 },
    hue: '#9A7A55',
  },
  {
    slug: 'pimento',
    name: 'Pimento',
    kind: 'material',
    family: 'spice',
    aliases: ['allspice', 'pimento berry'],
    smellsLike: 'Warm and clove-like with a peppery, cinnamon-ish edge, like a pinch of ground allspice.',
    origin: 'Steam-distilled from the dried berries (and sometimes leaves) of the Jamaican pimento tree.',
    contributes: 'Adds a warm, slightly medicinal spice that sits between clove and pepper.',
    synthetic: false,
    volatility: 'heart',
    character: { spicy: 0.7, warm: 0.4, woody: 0.1 },
    hue: '#8A5A3C',
  },
  {
    slug: 'akigalawood',
    name: 'Akigalawood',
    kind: 'material',
    family: 'woody',
    aliases: ['akigala wood'],
    smellsLike: 'A peppery, slightly spicy woodiness, like patchouli with the earthy, damp side taken out.',
    origin:
      'A captive material made by treating patchouli oil with enzymes, which changes its character. Only available to one fragrance supplier.',
    contributes: 'Adds a dry, spicy woody depth to warm and gourmand bases.',
    synthetic: 'both',
    volatility: 'base',
    character: { woody: 0.6, spicy: 0.3, earthy: 0.2 },
    hue: '#7E6A52',
  },
];
