import type { SeedNote } from './types';

/**
 * Reference descriptions for every slug in NOTE_VOCABULARY (vocabulary.ts).
 * Real-world materials, written in our own words. Follows src/seed/VOICE.md.
 */
export const NOTES: SeedNote[] = [
  // ---------------------------------------------------------------- citrus
  {
    slug: 'bergamot',
    name: 'Bergamot',
    kind: 'material',
    family: 'citrus',
    aliases: ['bergamot orange'],
    smellsLike:
      'Bright, slightly bitter citrus with a soft floral edge. If you know Earl Grey tea, you already know bergamot.',
    origin:
      'Cold-pressed from the peel of a bitter citrus grown mostly in Calabria, in southern Italy. Perfume grades usually have bergaptene removed, a compound that can make skin burn more easily in sunlight.',
    contributes:
      'Lifts the opening and slides smoothly into florals and woods. It turns up in more classic structures than any other citrus.',
    synthetic: false,
    volatility: 'top',
    character: { fresh: 0.9, fruity: 0.2 },
    hue: '#C9B24A',
  },
  {
    slug: 'lemon',
    name: 'Lemon',
    kind: 'material',
    family: 'citrus',
    aliases: ['lemon zest', 'lemon peel'],
    smellsLike: 'Sharp, zesty and juicy, like scratching the skin of a fresh lemon with your thumbnail.',
    origin:
      'Cold-pressed from lemon peel. The natural oil fades fast, so perfumers often prop it up with citral and other synthetic lemony molecules.',
    contributes:
      'A clean, wide-awake opening. On its own it rarely lasts much past the first fifteen minutes.',
    synthetic: false,
    volatility: 'top',
    character: { fresh: 0.9, clean: 0.3, fruity: 0.2 },
    hue: '#D4C35A',
  },
  {
    slug: 'mandarin',
    name: 'Mandarin',
    kind: 'material',
    family: 'citrus',
    aliases: ['mandarin orange', 'tangerine', 'clementine'],
    smellsLike: 'Sweet, juicy and soft, like peeling a ripe mandarin. Rounder and friendlier than lemon or grapefruit.',
    origin:
      'Cold-pressed from mandarin peel. Green mandarin comes from unripe fruit and smells sharper, while red mandarin is riper and sweeter.',
    contributes:
      'Adds a juicy, easygoing brightness to the opening and sits especially well next to florals and ambers.',
    synthetic: false,
    volatility: 'top',
    character: { fresh: 0.7, fruity: 0.4, sweet: 0.2 },
    hue: '#D39A4A',
  },
  {
    slug: 'sweet-orange',
    name: 'Sweet orange',
    kind: 'material',
    family: 'citrus',
    aliases: ['orange', 'orange peel'],
    smellsLike: 'The fine spray that hits your nose when you peel an orange: sweet, juicy and cheerful.',
    origin:
      'Cold-pressed from orange peel, largely as a by-product of the juice industry, which makes it one of the cheapest natural oils in perfumery.',
    contributes:
      'Gives a sunny, sweet start and pairs easily with spice, vanilla and amber. It is gone fairly quickly.',
    synthetic: false,
    volatility: 'top',
    character: { fresh: 0.6, fruity: 0.5, sweet: 0.3 },
    hue: '#D08A3E',
  },
  {
    slug: 'bitter-orange',
    name: 'Bitter orange',
    kind: 'material',
    family: 'citrus',
    aliases: ['bigarade', 'seville orange'],
    smellsLike:
      'Drier and sharper than sweet orange, with a bitter peel edge. Think marmalade before anyone adds the sugar.',
    origin:
      'Cold-pressed from the peel of the bitter orange tree. The same tree also gives neroli and orange blossom from its flowers and petitgrain from its leaves and twigs.',
    contributes: 'Brings a grown-up, slightly bitter brightness, common in colognes and older-style compositions.',
    synthetic: false,
    volatility: 'top',
    character: { fresh: 0.8, fruity: 0.3, green: 0.2 },
    hue: '#C27F3A',
  },
  {
    slug: 'grapefruit',
    name: 'Grapefruit',
    kind: 'material',
    family: 'citrus',
    aliases: ['pink grapefruit'],
    smellsLike:
      'Tart, juicy and a little bitter, with the faintly sulfurous pink tang that real grapefruit has. Very awake.',
    origin:
      'Partly cold-pressed from the peel, but the juicy, sulfurous character usually comes from synthetics such as nootkatone and a few extremely potent sulfur molecules.',
    contributes: 'Gives a sparkling, energetic opening and is a staple of fresh and sporty fragrances.',
    synthetic: 'both',
    volatility: 'top',
    character: { fresh: 0.9, fruity: 0.4 },
    hue: '#D08C78',
  },
  {
    slug: 'lime',
    name: 'Lime',
    kind: 'material',
    family: 'citrus',
    aliases: ['key lime'],
    smellsLike: 'Sharper and greener than lemon, like a lime wedge squeezed over a cold drink.',
    origin:
      'Cold-pressed or distilled from lime peel. Distilled lime smells candied and soda-like, while pressed lime stays greener and closer to the fruit.',
    contributes: 'Adds a zesty snap to the opening and gets along well with mint, ginger and rum notes.',
    synthetic: false,
    volatility: 'top',
    character: { fresh: 0.9, green: 0.3, fruity: 0.2 },
    hue: '#9DAF4E',
  },
  {
    slug: 'yuzu',
    name: 'Yuzu',
    kind: 'material',
    family: 'citrus',
    smellsLike:
      'A Japanese citrus that smells somewhere between grapefruit and mandarin, with a floral, almost herbal tang.',
    origin:
      'Cold-pressed from the peel of the yuzu fruit. The natural oil is scarce and pricey, so many yuzu notes are accords built from other citrus oils and synthetics.',
    contributes: 'Gives a bright, slightly unusual citrus opening that feels more delicate than lemon.',
    synthetic: 'both',
    volatility: 'top',
    character: { fresh: 0.9, fruity: 0.3, floral: 0.2 },
    hue: '#CDBB55',
  },
  {
    slug: 'petitgrain',
    name: 'Petitgrain',
    kind: 'material',
    family: 'citrus',
    aliases: ['petitgrain bigarade'],
    smellsLike: 'Green, woody citrus with a bitter leafy edge, like crushing an orange-tree leaf between your fingers.',
    origin:
      'Steam-distilled from the leaves and twigs of the bitter orange tree. The name means "little grain" and dates from when small unripe fruit went into the still.',
    contributes:
      'Adds a crisp green-citrus freshness that holds on a bit longer than peel oils. A backbone of classic colognes.',
    synthetic: false,
    volatility: 'top',
    character: { fresh: 0.7, green: 0.5, woody: 0.2 },
    hue: '#8E9A5A',
  },
  {
    slug: 'blood-orange',
    name: 'Blood orange',
    kind: 'material',
    family: 'citrus',
    aliases: ['red orange', 'sanguine orange'],
    smellsLike: 'Juicy orange with a darker, berry-like tang. Sweeter and redder than regular orange, if a smell can be red.',
    origin:
      'Blood orange oil exists but is rare, so most blood orange notes are blends of sweet orange, mandarin and fruity synthetics.',
    contributes: 'Brings a juicy, slightly tart fruitiness to the opening, often in playful or fruity-floral compositions.',
    synthetic: 'both',
    volatility: 'top',
    character: { fruity: 0.6, fresh: 0.6, sweet: 0.3 },
    hue: '#B5604A',
  },
  {
    slug: 'citron',
    name: 'Citron',
    kind: 'material',
    family: 'citrus',
    aliases: ['cedrat', 'cédrat'],
    smellsLike: 'Like a lemon with less juice and more peel: dry, clean and faintly floral.',
    origin:
      'Cold-pressed from the thick-skinned citron, an ancestor of many modern citrus fruits. Real citron oil is scarce, so the note is often rebuilt from lemon oil and citral.',
    contributes: 'Gives a dry, polished citrus lift for compositions that want freshness without sweetness.',
    synthetic: 'both',
    volatility: 'top',
    character: { fresh: 0.9, clean: 0.3 },
    hue: '#C8C06A',
  },

  // -------------------------------------------------------------- aromatic
  {
    slug: 'lavender',
    name: 'Lavender',
    kind: 'material',
    family: 'aromatic',
    aliases: ['lavandin', 'lavender absolute'],
    smellsLike:
      'Herbal, clean and a little floral, with a cool camphor edge. Think of a lavender sachet in a drawer, or old-fashioned barbershop shaving soap.',
    origin:
      'Steam-distilled from the flowering tops of lavender. Lavandin, a hardier hybrid, gives a sharper, more camphor-like oil and is used widely because it costs less.',
    contributes:
      'Brings an aromatic, clean freshness that can lean herbal or soft and sweet. It is the core of the fougère family.',
    synthetic: false,
    volatility: 'heart',
    character: { fresh: 0.5, floral: 0.4, clean: 0.4, green: 0.2 },
    hue: '#8E86A8',
  },
  {
    slug: 'rosemary',
    name: 'Rosemary',
    kind: 'material',
    family: 'aromatic',
    smellsLike: 'Resinous and herbal with a cooling camphor edge, like rosemary sprigs crushed in your palm.',
    origin: 'Steam-distilled from the leaves and flowering tops of the rosemary shrub.',
    contributes: 'Adds a brisk herbal snap to the opening. Common in colognes and fougères.',
    synthetic: false,
    volatility: 'top',
    character: { fresh: 0.6, green: 0.6 },
    hue: '#6F7F5C',
  },
  {
    slug: 'clary-sage',
    name: 'Clary sage',
    kind: 'material',
    family: 'aromatic',
    aliases: ['sage', 'salvia sclarea'],
    smellsLike:
      'Herbal and musky with hints of tea and hay, a little like warm skin. Softer and rounder than kitchen sage.',
    origin:
      'Steam-distilled from the flowering tops of clary sage. Sclareol, one of its components, is the usual starting point for making ambroxan.',
    contributes: 'Gives an aromatic, faintly ambery warmth that links a fresh opening to a woody base.',
    synthetic: false,
    volatility: 'heart',
    character: { green: 0.4, fresh: 0.3, warm: 0.3, earthy: 0.2 },
    hue: '#7D7F68',
  },
  {
    slug: 'basil',
    name: 'Basil',
    kind: 'material',
    family: 'aromatic',
    aliases: ['sweet basil'],
    smellsLike: 'Sweet, green and peppery with a hint of anise, like tearing basil leaves over a tomato salad.',
    origin: 'Steam-distilled from the leaves and flowering tops of sweet basil.',
    contributes: 'Adds a lively green, slightly spicy edge, often next to citrus or mint.',
    synthetic: false,
    volatility: 'top',
    character: { green: 0.7, fresh: 0.5, spicy: 0.2 },
    hue: '#5E7A4E',
  },
  {
    slug: 'mint',
    name: 'Mint',
    kind: 'material',
    family: 'aromatic',
    aliases: ['peppermint', 'spearmint'],
    smellsLike: 'Cool and sharp, like toothpaste or chewing gum. Spearmint is sweeter and softer; peppermint is icier.',
    origin:
      'Steam-distilled from mint leaves. Menthol and other cooling molecules are often added to push the chill further.',
    contributes: 'Gives an instant cooling effect up top. It fades fast, but it sets a crisp first impression.',
    synthetic: false,
    volatility: 'top',
    character: { fresh: 0.9, green: 0.4 },
    hue: '#7FA38A',
  },
  {
    slug: 'thyme',
    name: 'Thyme',
    kind: 'material',
    family: 'aromatic',
    smellsLike: 'Warm, dry and herbal with a slightly medicinal bite, like a herb garden baking in the sun.',
    origin: 'Steam-distilled from thyme leaves and flowers. Thymol, its main molecule, supplies the antiseptic edge.',
    contributes: 'Adds a warm, dry aromatic quality, often in herbal or Mediterranean-style compositions.',
    synthetic: false,
    volatility: 'heart',
    character: { green: 0.5, spicy: 0.3, warm: 0.3 },
    hue: '#7A7A55',
  },
  {
    slug: 'artemisia',
    name: 'Artemisia',
    kind: 'material',
    family: 'aromatic',
    aliases: ['wormwood', 'mugwort', 'armoise'],
    smellsLike: 'Bitter, green and a bit medicinal, with the herbal sharpness of a glass of absinthe.',
    origin: 'Steam-distilled from the leaves and flowering tops of various artemisia plants, including wormwood and mugwort.',
    contributes: 'Adds a bitter aromatic edge that stops sweet or floral compositions from going soft.',
    synthetic: false,
    volatility: 'top',
    character: { green: 0.7, fresh: 0.3, earthy: 0.2 },
    hue: '#7E8B6A',
  },
  {
    slug: 'juniper-berry',
    name: 'Juniper berry',
    kind: 'material',
    family: 'aromatic',
    aliases: ['juniper'],
    smellsLike: 'Piney, resinous and slightly peppery. If you have smelled gin, you have smelled juniper.',
    origin: 'Steam-distilled from the crushed, dried berries of the juniper shrub.',
    contributes: 'Brings a crisp, coniferous freshness to the opening of aromatic and woody fragrances.',
    synthetic: false,
    volatility: 'top',
    character: { fresh: 0.6, woody: 0.4, green: 0.3, spicy: 0.2 },
    hue: '#5D6C7A',
  },
  {
    slug: 'geranium',
    name: 'Geranium',
    kind: 'material',
    family: 'aromatic',
    aliases: ['rose geranium', 'pelargonium', 'geranium bourbon'],
    smellsLike:
      'Rosy and green with a minty, slightly metallic edge, like rubbing the leaves of a potted geranium.',
    origin:
      'Steam-distilled from the leaves and stems of pelargonium plants, not the flowers. It shares several molecules with rose, which is why it smells rosy.',
    contributes:
      'Adds a fresh, rosy brightness that works in fougères and florals alike. Often used to support or stretch a rose note.',
    synthetic: false,
    volatility: 'heart',
    character: { floral: 0.5, green: 0.5, fresh: 0.3 },
    hue: '#A8737A',
  },
  {
    slug: 'tarragon',
    name: 'Tarragon',
    kind: 'material',
    family: 'aromatic',
    aliases: ['estragon'],
    smellsLike: 'Green and herbal with a sweet anise twist, as if licorice grew in a herb garden.',
    origin: 'Steam-distilled from tarragon leaves. The anise character comes from a molecule called estragole.',
    contributes: 'Adds a fresh, faintly sweet herbal accent to openings, especially in aromatic and fougère styles.',
    synthetic: false,
    volatility: 'top',
    character: { green: 0.6, fresh: 0.4, sweet: 0.2 },
    hue: '#7C8C58',
  },

  // ----------------------------------------------------------------- green
  {
    slug: 'violet-leaf',
    name: 'Violet leaf',
    kind: 'material',
    family: 'green',
    aliases: ['violet leaves'],
    smellsLike:
      'Sharp, green and watery, like fresh cucumber skin mixed with crushed leaves. Nothing like the sweet violet flower note.',
    origin:
      'Solvent-extracted from violet leaves as an absolute. Its cucumber-green molecule is also made synthetically and used to stretch the natural.',
    contributes: 'Gives an intense, cool green freshness. A drop goes a long way.',
    synthetic: 'both',
    volatility: 'top',
    character: { green: 0.9, fresh: 0.5 },
    hue: '#5F7A55',
  },
  {
    slug: 'galbanum',
    name: 'Galbanum',
    kind: 'material',
    family: 'green',
    smellsLike: 'Very sharp, bitter green, like snapping a thick, sappy plant stem. Some find it piercing at first.',
    origin:
      'A gum resin tapped from a plant in the fennel family that grows in Iran and Central Asia, used as an essential oil, resinoid or absolute.',
    contributes: 'Adds a dramatic green bite to the opening. A classic in green chypres and green florals.',
    synthetic: false,
    volatility: 'top',
    character: { green: 1, fresh: 0.4, earthy: 0.2 },
    hue: '#6B7A4A',
  },
  {
    slug: 'fig-leaf',
    name: 'Fig leaf',
    kind: 'material',
    family: 'green',
    aliases: ['fig tree'],
    smellsLike: 'Green, milky and faintly coconut-like, like standing under a fig tree on a hot afternoon.',
    origin:
      'Fig leaf absolute exists but is restricted and costly, so most fig leaf notes lean on synthetics that recreate the green, milky effect.',
    contributes: 'Brings a lush, green-creamy freshness, popular in summery and Mediterranean-style scents.',
    synthetic: 'both',
    volatility: 'heart',
    character: { green: 0.7, creamy: 0.4, fresh: 0.3 },
    hue: '#6F8A5E',
  },
  {
    slug: 'tomato-leaf',
    name: 'Tomato leaf',
    kind: 'material',
    family: 'green',
    aliases: ['tomato vine'],
    smellsLike: 'Pungent, bitter green, exactly like brushing past tomato plants in a warm greenhouse.',
    origin:
      'Natural tomato leaf extracts are rare, so the note is usually built from green synthetic molecules.',
    contributes: 'Adds a vivid, realistic garden greenness that feels unusual in a composition.',
    synthetic: 'both',
    volatility: 'top',
    character: { green: 0.9, fresh: 0.3, earthy: 0.2 },
    hue: '#5A7448',
  },
  {
    slug: 'blackcurrant-bud',
    name: 'Blackcurrant bud',
    kind: 'material',
    family: 'green',
    aliases: ['cassis bud', 'bourgeon de cassis'],
    smellsLike:
      'Sharp, green and fruity with a catty, faintly sulfurous edge. It sounds odd, and it works anyway.',
    origin:
      'Solvent-extracted as an absolute from the dormant buds of the blackcurrant bush. Potent sulfur compounds give it the tang.',
    contributes: 'Gives a tart green-fruity sharpness to openings and fruity florals, more grown-up than the berry itself.',
    synthetic: false,
    volatility: 'top',
    character: { green: 0.6, fruity: 0.5 },
    hue: '#5E5A62',
  },
  {
    slug: 'rhubarb',
    name: 'Rhubarb',
    kind: 'accord',
    family: 'green',
    smellsLike: 'Tart and green with a rosy, fruity crunch, like biting a raw stick of rhubarb.',
    origin:
      'Rhubarb is not extracted for perfume. The note comes from synthetic molecules that reproduce its sour, green and rosy sides.',
    contributes: 'Adds a crisp, sour-green sparkle to openings, often alongside citrus and rose.',
    synthetic: true,
    volatility: 'top',
    character: { green: 0.6, fresh: 0.5, fruity: 0.4 },
    hue: '#B07A78',
  },
  {
    slug: 'cut-grass',
    name: 'Cut grass',
    kind: 'accord',
    family: 'green',
    aliases: ['freshly cut grass', 'grass', 'green grass'],
    smellsLike: 'A lawn that was mowed five minutes ago: bright, green and a little sharp.',
    origin:
      'An accord built mostly on cis-3-hexenol, the molecule plants release when their leaves are cut, with other green synthetics around it.',
    contributes: 'Adds a vivid, outdoorsy greenness to the opening.',
    synthetic: true,
    volatility: 'top',
    character: { green: 0.9, fresh: 0.6 },
    hue: '#6E8F4E',
  },
  {
    slug: 'bamboo',
    name: 'Bamboo',
    kind: 'accord',
    family: 'green',
    smellsLike: 'Fresh, watery and green, like a cool leafy stalk. Airy rather than sharp.',
    origin: 'An accord, since bamboo is not extracted for perfume. Usually a mix of green, watery and light woody synthetics.',
    contributes: 'Adds a clean, airy green quality, common in fresh and spa-like compositions.',
    synthetic: true,
    volatility: 'heart',
    character: { green: 0.6, fresh: 0.6, clean: 0.3 },
    hue: '#8FA27A',
  },
  {
    slug: 'cucumber',
    name: 'Cucumber',
    kind: 'accord',
    family: 'green',
    smellsLike: 'Cool, watery and green, like a cucumber slice straight from the fridge.',
    origin:
      'An accord built mainly on nonadienal and related molecules, the same compounds found in cucumber skin and violet leaf.',
    contributes: 'Gives a crisp, watery coolness to fresh fragrances.',
    synthetic: true,
    volatility: 'top',
    character: { fresh: 0.8, green: 0.6 },
    hue: '#9AB08A',
  },

  // ---------------------------------------------------------------- marine
  {
    slug: 'marine-notes',
    name: 'Marine notes',
    kind: 'accord',
    family: 'marine',
    aliases: ['sea notes', 'ocean notes', 'aquatic notes', 'water notes'],
    smellsLike:
      'A clean, breezy idea of the sea: watery, airy and slightly salty. Less real beach, more the ocean from a shampoo ad.',
    origin:
      'An accord of synthetic molecules such as calone and other watery, ozonic materials. Nobody can distill the sea.',
    contributes: 'Gives a cool, watery freshness. The defining note of the aquatic family.',
    synthetic: true,
    volatility: 'top',
    character: { fresh: 0.9, clean: 0.5 },
    hue: '#7A9AA8',
  },
  {
    slug: 'sea-salt',
    name: 'Sea salt',
    kind: 'accord',
    family: 'marine',
    aliases: ['salt', 'salty', 'sea spray'],
    smellsLike: 'Skin after a swim in the sea: mineral, warm and faintly savory.',
    origin:
      'An accord, since salt itself has no smell. Perfumers combine mineral, ambery and marine molecules (ambroxan is a frequent helper) to suggest it.',
    contributes: 'Adds a salty, skin-like texture that makes fresh or woody fragrances feel more lived-in.',
    synthetic: true,
    volatility: 'heart',
    character: { fresh: 0.5, warm: 0.3, clean: 0.3 },
    hue: '#A9B3B0',
  },
  {
    slug: 'calone',
    name: 'Calone',
    kind: 'material',
    family: 'marine',
    aliases: ['watermelon ketone'],
    smellsLike: 'Watery and breezy with an odd melon sweetness, like cut watermelon at the beach.',
    origin:
      'A synthetic molecule discovered in the 1960s that became the signature of the 1990s aquatic wave.',
    contributes:
      'A trace gives sea-spray freshness; a bit more and everything smells of melon. The backbone of many aquatic fragrances.',
    synthetic: true,
    volatility: 'top',
    character: { fresh: 0.9, fruity: 0.3 },
    hue: '#8FB0B2',
  },
  {
    slug: 'seaweed',
    name: 'Seaweed',
    kind: 'material',
    family: 'marine',
    aliases: ['algae', 'kelp', 'seaweed absolute'],
    smellsLike: 'Salty, iodine-rich and a little green, like seaweed drying on rocks at low tide.',
    origin:
      'Absolutes and extracts are made from brown seaweeds, though many seaweed notes are partly or fully synthetic.',
    contributes: 'Adds a realistic, briny shoreline character, rougher than clean marine notes.',
    synthetic: 'both',
    volatility: 'heart',
    character: { fresh: 0.4, green: 0.4, earthy: 0.4 },
    hue: '#4E6A58',
  },
  {
    slug: 'petrichor',
    name: 'Petrichor',
    kind: 'accord',
    family: 'marine',
    aliases: ['rain', 'after rain', 'wet earth'],
    smellsLike: 'Rain hitting dry ground: earthy, mineral and fresh all at once.',
    origin:
      'An accord. Part of the real smell comes from geosmin, a molecule made by soil bacteria, which perfumers use in tiny amounts with mineral and green notes.',
    contributes: 'Adds a cool, damp, earthy freshness and gives a fragrance a sense of weather.',
    synthetic: true,
    volatility: 'heart',
    character: { fresh: 0.6, earthy: 0.5, green: 0.2 },
    hue: '#7D8580',
  },

  // ---------------------------------------------------------------- floral
  {
    slug: 'rose',
    name: 'Rose',
    kind: 'material',
    family: 'floral',
    aliases: ['rose absolute', 'rose otto', 'damask rose', 'rose de mai', 'centifolia'],
    smellsLike:
      'Rich and petal-soft, slightly fruity, sometimes with a honeyed or spicy edge. Fresh roses in a vase, only deeper.',
    origin:
      'Steam-distilled into rose oil (otto) or solvent-extracted into rose absolute, mainly from Damask roses in Bulgaria and Turkey and centifolia roses in Morocco and France. Synthetic rose molecules such as phenylethyl alcohol and citronellol are used heavily too.',
    contributes:
      'Gives body and warmth to the floral heart. Depending on its neighbors it can read fresh, jammy, dark or powdery.',
    synthetic: 'both',
    volatility: 'heart',
    character: { floral: 0.9, fruity: 0.2, sweet: 0.2 },
    hue: '#A85A64',
  },
  {
    slug: 'jasmine',
    name: 'Jasmine',
    kind: 'material',
    family: 'floral',
    aliases: ['jasmin', 'jasmine sambac', 'sambac', 'jasmine grandiflorum'],
    smellsLike:
      'Lush, sweet white floral with an indolic, faintly animal undertone that makes it feel warm and skin-like.',
    origin:
      'Solvent-extracted as an absolute from jasmine flowers, mostly grandiflorum and sambac from India and Egypt. Synthetics like hedione and benzyl acetate are often used to build or stretch it.',
    contributes:
      'Adds richness and radiance to a floral heart. Hedione, a jasmine-derived synthetic, gives airy lift to all sorts of fragrances.',
    synthetic: 'both',
    volatility: 'heart',
    character: { floral: 0.9, sweet: 0.3, warm: 0.2 },
    hue: '#E2D6B0',
  },
  {
    slug: 'orange-blossom',
    name: 'Orange blossom',
    kind: 'material',
    family: 'floral',
    aliases: ['orange flower', "fleur d'oranger"],
    smellsLike:
      'Sweet, honeyed and slightly soapy white floral, warmer and more indolic than neroli. A citrus grove in bloom at dusk.',
    origin:
      'Solvent-extracted as an absolute from the flowers of the bitter orange tree. Steam-distill the same flowers and you get neroli instead.',
    contributes: 'Adds a radiant, sweet floral warmth that can come across as clean or sensual. Common in florals and ambers.',
    synthetic: false,
    volatility: 'heart',
    character: { floral: 0.8, sweet: 0.4, clean: 0.2 },
    hue: '#E8D5A8',
  },
  {
    slug: 'neroli',
    name: 'Neroli',
    kind: 'material',
    family: 'floral',
    smellsLike: 'Fresh, green-floral with a bitter citrus edge. Lighter and cleaner than orange blossom.',
    origin:
      'Steam-distilled from the flowers of the bitter orange tree. The water left over from distillation is sold as orange flower water.',
    contributes:
      'Bridges citrus top notes into the floral heart with a clean, sunny brightness. A pillar of the classic cologne.',
    synthetic: false,
    volatility: 'top',
    character: { floral: 0.6, fresh: 0.6, clean: 0.3 },
    hue: '#E0CF9A',
  },
  {
    slug: 'tuberose',
    name: 'Tuberose',
    kind: 'material',
    family: 'floral',
    aliases: ['polianthes'],
    smellsLike:
      'Creamy, buttery and intensely sweet white floral, with a rubbery, almost camphor-like edge up close. Loud, and it knows it.',
    origin:
      'Solvent-extracted as an absolute from tuberose flowers, mostly grown in India. The absolute is expensive, so synthetics often support it.',
    contributes: 'Gives a bold, creamy floral heart that tends to take over whatever it is in.',
    synthetic: 'both',
    volatility: 'heart',
    character: { floral: 0.9, creamy: 0.5, sweet: 0.4 },
    hue: '#EADCC0',
  },
  {
    slug: 'iris',
    name: 'Iris',
    kind: 'material',
    family: 'floral',
    aliases: ['orris', 'orris root', 'orris butter'],
    smellsLike:
      'Cool, powdery and soft, somewhere between lipstick, raw carrot and a clean cotton shirt. Barely floral, despite the name.',
    origin:
      'Comes from the root, not the flower. Iris rhizomes are dried and aged for about three years, then distilled into orris butter, one of the most expensive materials in perfumery. Synthetic irones and ionones help support it.',
    contributes: 'Brings a cool, refined powderiness with an earthy depth. It makes compositions feel restrained.',
    synthetic: 'both',
    volatility: 'heart',
    character: { powdery: 0.9, floral: 0.4, earthy: 0.2 },
    hue: '#9C94A8',
  },
  {
    slug: 'violet',
    name: 'Violet',
    kind: 'accord',
    family: 'floral',
    aliases: ['violets', 'parma violet', 'ionones'],
    smellsLike: 'Sweet, powdery and candy-like, like old-fashioned violet sweets or a makeup compact.',
    origin:
      'The flower is almost never extracted. Violet notes are built from ionones, synthetic molecules first made in the 1890s, often with a touch of violet leaf for green.',
    contributes: 'Adds a soft, powdery sweetness that can feel nostalgic or cosmetic. Pairs well with iris, rose and woods.',
    synthetic: true,
    volatility: 'heart',
    character: { powdery: 0.7, floral: 0.6, sweet: 0.4 },
    hue: '#7D6A92',
  },
  {
    slug: 'ylang-ylang',
    name: 'Ylang-ylang',
    kind: 'material',
    family: 'floral',
    aliases: ['ylang', 'ylang ylang'],
    smellsLike: 'Rich, creamy tropical floral with a hint of banana and a slightly medicinal edge.',
    origin:
      'Steam-distilled from the flowers of a tree native to Southeast Asia, now grown largely in the Comoros and Madagascar. The distillation is split into fractions, from the light "extra" grade to heavier ones.',
    contributes: 'Gives a sweet, sunny, creamy floral body. Common in florals and ambers.',
    synthetic: false,
    volatility: 'heart',
    character: { floral: 0.8, creamy: 0.4, sweet: 0.4, fruity: 0.2 },
    hue: '#D8C27A',
  },
  {
    slug: 'magnolia',
    name: 'Magnolia',
    kind: 'material',
    family: 'floral',
    aliases: ['champaca', 'michelia'],
    smellsLike: 'Lemony, creamy and fresh floral. Lighter and brighter than gardenia or tuberose.',
    origin:
      'Oils are produced from the flowers and leaves of michelia trees, close relatives of magnolia, but many magnolia notes are partly or fully synthetic.',
    contributes: 'Adds a fresh, slightly citrusy floral brightness to the heart.',
    synthetic: 'both',
    volatility: 'heart',
    character: { floral: 0.8, fresh: 0.4, creamy: 0.2 },
    hue: '#E3D3C2',
  },
  {
    slug: 'peony',
    name: 'Peony',
    kind: 'accord',
    family: 'floral',
    aliases: ['pivoine'],
    smellsLike: 'Fresh, rosy and lightly fruity. Airy rather than heady, like a bouquet in a cool room.',
    origin: 'An accord, since peonies yield no usable extract. Built from rosy, fruity and fresh synthetic molecules.',
    contributes: 'Adds a soft, bright pink floral tone, common in fresh and fruity florals.',
    synthetic: true,
    volatility: 'heart',
    character: { floral: 0.8, fresh: 0.4, fruity: 0.2 },
    hue: '#C8909A',
  },
  {
    slug: 'lily-of-the-valley',
    name: 'Lily of the valley',
    kind: 'accord',
    family: 'floral',
    aliases: ['muguet'],
    smellsLike: 'Clean, green and dewy white floral, like fresh laundry left out in a spring garden.',
    origin:
      'The flower gives no usable extract, so this is always an accord, mostly synthetic with some natural florals. Several of its key molecules have been restricted in recent years, so perfumers keep rebuilding it.',
    contributes:
      'Adds an airy, clean brightness to florals. It is often the reason a fragrance smells "clean" in a way you cannot pin down.',
    synthetic: 'both',
    volatility: 'heart',
    character: { floral: 0.7, clean: 0.6, green: 0.3, fresh: 0.3 },
    hue: '#D7DCC4',
  },
  {
    slug: 'gardenia',
    name: 'Gardenia',
    kind: 'accord',
    family: 'floral',
    smellsLike: 'Creamy, lush white floral with a green, slightly mushroomy edge. Richer and earthier than jasmine.',
    origin:
      'Gardenia extract is extremely rare, so the note is an accord of jasmine, tuberose and other naturals with synthetic molecules.',
    contributes: 'Gives a velvety, creamy floral heart.',
    synthetic: 'both',
    volatility: 'heart',
    character: { floral: 0.9, creamy: 0.5, green: 0.2 },
    hue: '#E8E0C8',
  },
  {
    slug: 'osmanthus',
    name: 'Osmanthus',
    kind: 'material',
    family: 'floral',
    aliases: ['sweet olive', 'tea olive'],
    smellsLike: 'Apricot, suede and tea, all from one tiny flower. Fruity, soft and faintly smoky.',
    origin:
      'Solvent-extracted as an absolute from the small flowers of a shrub native to China, where it also flavors tea and sweets.',
    contributes: 'Adds a fruity, leathery warmth that makes florals and tea notes feel rich and unusual.',
    synthetic: false,
    volatility: 'heart',
    character: { floral: 0.6, fruity: 0.6, warm: 0.2 },
    hue: '#D49A5A',
  },
  {
    slug: 'mimosa',
    name: 'Mimosa',
    kind: 'material',
    family: 'floral',
    aliases: ['acacia', 'silver wattle'],
    smellsLike:
      'Soft, honeyed and powdery with a faint green, almond-like edge, about as gentle as the fuzzy yellow flowers look.',
    origin:
      'Solvent-extracted as an absolute from the flowers and twigs of the mimosa tree, a type of acacia grown widely in the south of France.',
    contributes: 'Adds a cozy, powdery floral warmth, often alongside iris, violet and heliotrope.',
    synthetic: false,
    volatility: 'heart',
    character: { powdery: 0.6, floral: 0.6, sweet: 0.3 },
    hue: '#D4BF5E',
  },
  {
    slug: 'heliotrope',
    name: 'Heliotrope',
    kind: 'accord',
    family: 'floral',
    aliases: ['heliotropin', 'piperonal'],
    smellsLike: 'Powdery, almondy and vanilla-like, a bit like marzipan dusted with baby powder.',
    origin:
      'An accord, since the flower gives no usable extract. Built mostly on heliotropin (piperonal), plus vanillin and coumarin.',
    contributes: 'Adds a soft, powdery sweetness that bridges florals and gourmand bases.',
    synthetic: true,
    volatility: 'heart',
    character: { powdery: 0.8, sweet: 0.5, floral: 0.3 },
    hue: '#A99AB8',
  },
  {
    slug: 'carnation',
    name: 'Carnation',
    kind: 'accord',
    family: 'floral',
    aliases: ['clove pink', 'dianthus', 'oeillet'],
    smellsLike: 'Spicy floral, like a rose that swallowed a clove. Peppery, warm and a little old-fashioned.',
    origin:
      'Carnation absolute exists but is very rare today, so the note is usually an accord of eugenol (the main molecule in clove) with rose and other florals.',
    contributes: 'Adds a warm, spicy twist to a floral heart.',
    synthetic: 'both',
    volatility: 'heart',
    character: { floral: 0.6, spicy: 0.6 },
    hue: '#B8676A',
  },
  {
    slug: 'frangipani',
    name: 'Frangipani',
    kind: 'accord',
    family: 'floral',
    aliases: ['plumeria'],
    smellsLike: 'Creamy, tropical fruity-floral with hints of peach, coconut and sun lotion.',
    origin: 'An accord of other florals and synthetic molecules, since frangipani extracts are scarce.',
    contributes: 'Gives a sunny, creamy floral body, common in summery and beachy compositions.',
    synthetic: 'both',
    volatility: 'heart',
    character: { floral: 0.8, creamy: 0.4, fruity: 0.3, sweet: 0.3 },
    hue: '#E6C9A8',
  },
  {
    slug: 'honeysuckle',
    name: 'Honeysuckle',
    kind: 'accord',
    family: 'floral',
    aliases: ['woodbine'],
    smellsLike:
      'Sweet, nectar-like and green, like the flowers you pulled apart as a kid to taste the drop inside.',
    origin: 'An accord, since honeysuckle has no commercial extract. Built from sweet floral, fruity and green synthetics.',
    contributes: 'Adds a sweet, sunny floral note with a fresh green edge.',
    synthetic: true,
    volatility: 'heart',
    character: { floral: 0.7, sweet: 0.5, green: 0.3 },
    hue: '#E0CB8E',
  },

  // ---------------------------------------------------------------- fruity
  {
    slug: 'pear',
    name: 'Pear',
    kind: 'accord',
    family: 'fruity',
    smellsLike: 'Crisp, juicy and lightly sweet, like biting into a ripe pear.',
    origin: 'An accord built on fruity esters and other synthetics. Pears are not extracted for perfume.',
    contributes: 'Adds a juicy, fresh sweetness to the opening without much weight.',
    synthetic: true,
    volatility: 'top',
    character: { fruity: 0.8, fresh: 0.4, sweet: 0.3 },
    hue: '#C3C27A',
  },
  {
    slug: 'green-apple',
    name: 'Green apple',
    kind: 'accord',
    family: 'fruity',
    aliases: ['apple'],
    smellsLike: 'Tart, crunchy and juicy, like a sour green apple or apple-flavored candy.',
    origin: 'An accord of fruity esters and green synthetic molecules.',
    contributes: 'Adds a bright, crisp fruitiness to fresh and casual fragrances.',
    synthetic: true,
    volatility: 'top',
    character: { fruity: 0.7, fresh: 0.6, green: 0.3 },
    hue: '#A8B860',
  },
  {
    slug: 'blackcurrant',
    name: 'Blackcurrant',
    kind: 'accord',
    family: 'fruity',
    aliases: ['cassis', 'black currant'],
    smellsLike: 'Dark, tart and jammy berry, like blackcurrant cordial, with a green edge.',
    origin:
      'Blackcurrant bud absolute supplies the green tang and synthetic fruity molecules supply the juicy berry. Most blackcurrant notes in perfume combine the two.',
    contributes: 'Adds a tart, dark fruitiness that keeps sweet florals from getting too sugary.',
    synthetic: 'both',
    volatility: 'top',
    character: { fruity: 0.8, sweet: 0.3, green: 0.2 },
    hue: '#5A3A52',
  },
  {
    slug: 'fig',
    name: 'Fig',
    kind: 'accord',
    family: 'fruity',
    aliases: ['fig fruit'],
    smellsLike: 'Milky, sweet and soft, like the inside of a ripe fig, with a little green from the skin.',
    origin: 'An accord combining milky, lactonic and green synthetics with woods and sometimes coconut notes.',
    contributes: 'Gives a creamy, fruity-green softness, often paired with fig leaf.',
    synthetic: true,
    volatility: 'heart',
    character: { fruity: 0.6, creamy: 0.5, green: 0.3, sweet: 0.3 },
    hue: '#7E5A6A',
  },
  {
    slug: 'peach',
    name: 'Peach',
    kind: 'accord',
    family: 'fruity',
    aliases: ['apricot'],
    smellsLike: 'Soft, juicy and velvety, like the fuzzy skin of a ripe peach.',
    origin: 'An accord built mainly on lactones such as gamma-undecalactone, which give the creamy, skin-like fruit.',
    contributes: 'Adds a soft, round fruitiness that melts into florals and musks.',
    synthetic: true,
    volatility: 'heart',
    character: { fruity: 0.8, sweet: 0.4, creamy: 0.3 },
    hue: '#DDA77F',
  },
  {
    slug: 'plum',
    name: 'Plum',
    kind: 'accord',
    family: 'fruity',
    aliases: ['prune'],
    smellsLike: 'Dark, jammy and slightly boozy, like stewed plums or prunes.',
    origin: 'An accord of fruity lactones and esters, sometimes with a little natural extract for depth.',
    contributes: 'Adds a rich, dark fruitiness, common in ambers, roses and evening fragrances.',
    synthetic: true,
    volatility: 'heart',
    character: { fruity: 0.7, sweet: 0.5, warm: 0.3 },
    hue: '#6E3E52',
  },
  {
    slug: 'cherry',
    name: 'Cherry',
    kind: 'accord',
    family: 'fruity',
    aliases: ['black cherry', 'sour cherry'],
    smellsLike: 'Sweet and almondy, closer to cherry candy or cherry liqueur than a fresh cherry from the tree.',
    origin: 'An accord built around benzaldehyde, the molecule behind both almond and cherry, with fruity synthetics.',
    contributes: 'Adds a sweet, slightly boozy fruitiness, often in gourmand or playful compositions.',
    synthetic: true,
    volatility: 'heart',
    character: { fruity: 0.7, sweet: 0.7 },
    hue: '#8E3A44',
  },
  {
    slug: 'raspberry',
    name: 'Raspberry',
    kind: 'accord',
    family: 'fruity',
    smellsLike: 'Sweet, tart and jammy, like raspberry jam or a raspberry sweet.',
    origin: 'An accord built around raspberry ketone and ionones.',
    contributes: 'Adds a bright, sweet-tart fruitiness, often in fruity florals.',
    synthetic: true,
    volatility: 'top',
    character: { fruity: 0.8, sweet: 0.5 },
    hue: '#A84A5C',
  },
  {
    slug: 'pineapple',
    name: 'Pineapple',
    kind: 'accord',
    family: 'fruity',
    smellsLike: 'Juicy, sweet-tart and tropical, like fresh pineapple chunks.',
    origin: 'An accord of fruity esters, with allyl caproate often doing most of the work.',
    contributes: 'Adds a loud, juicy brightness to the opening that can read fresh or sweet.',
    synthetic: true,
    volatility: 'top',
    character: { fruity: 0.8, fresh: 0.4, sweet: 0.4 },
    hue: '#CDB04E',
  },
  {
    slug: 'coconut',
    name: 'Coconut',
    kind: 'accord',
    family: 'fruity',
    smellsLike: 'Creamy, milky and sweet, like coconut milk or a bottle of sun lotion.',
    origin: 'An accord built on lactones, especially gamma-nonalactone, the same family behind peach and milk notes.',
    contributes: 'Adds a creamy, beachy sweetness, common in summery and gourmand fragrances.',
    synthetic: true,
    volatility: 'heart',
    character: { creamy: 0.8, sweet: 0.5, fruity: 0.2 },
    hue: '#E7DCC7',
  },
  {
    slug: 'lychee',
    name: 'Lychee',
    kind: 'accord',
    family: 'fruity',
    aliases: ['litchi'],
    smellsLike: 'Juicy, rosy and sweet, like a lychee peeled fresh from the shell.',
    origin: 'An accord of fruity and rosy synthetic molecules.',
    contributes: 'Adds a juicy, slightly floral fruitiness that pairs naturally with rose.',
    synthetic: true,
    volatility: 'top',
    character: { fruity: 0.8, floral: 0.3, sweet: 0.3 },
    hue: '#D9A8A6',
  },

  // ----------------------------------------------------------------- spice
  {
    slug: 'pink-pepper',
    name: 'Pink pepper',
    kind: 'material',
    family: 'spice',
    aliases: ['pink peppercorn', 'baies roses', 'schinus'],
    smellsLike: 'Bright, fizzy and slightly fruity spice, more sparkle than heat. Pepper with a citrus twist.',
    origin:
      'Distilled or CO2-extracted from the dried berries of the Peruvian pepper tree, which is not related to black pepper.',
    contributes:
      'Adds a zesty, rosy sparkle to openings. It has become one of the most common top notes of the last twenty years.',
    synthetic: false,
    volatility: 'top',
    character: { spicy: 0.6, fresh: 0.5, fruity: 0.2 },
    hue: '#B8737A',
  },
  {
    slug: 'black-pepper',
    name: 'Black pepper',
    kind: 'material',
    family: 'spice',
    aliases: ['pepper'],
    smellsLike: 'Dry, woody and sharp, like freshly cracked peppercorns, minus the sneeze.',
    origin: 'Steam-distilled or CO2-extracted from black peppercorns.',
    contributes: 'Adds a dry, spicy kick to the opening, common in woody and fresh-spicy fragrances.',
    synthetic: false,
    volatility: 'top',
    character: { spicy: 0.8, woody: 0.3, fresh: 0.2 },
    hue: '#4E4A45',
  },
  {
    slug: 'cardamom',
    name: 'Cardamom',
    kind: 'material',
    family: 'spice',
    aliases: ['cardamon'],
    smellsLike: 'Cool, aromatic and lemony spice, like chai or a warm cardamom bun.',
    origin: 'Steam-distilled or CO2-extracted from the seeds of the cardamom plant.',
    contributes:
      'Adds an airy spice that sits between fresh and warm. Especially good with woods, iris and coffee.',
    synthetic: false,
    volatility: 'top',
    character: { spicy: 0.6, fresh: 0.5, warm: 0.2 },
    hue: '#8A9070',
  },
  {
    slug: 'cinnamon',
    name: 'Cinnamon',
    kind: 'material',
    family: 'spice',
    aliases: ['cinnamon bark', 'cassia'],
    smellsLike: 'Warm, sweet and spicy, like cinnamon sticks or a fresh cinnamon roll.',
    origin:
      'Distilled from the bark or leaves of the cinnamon tree. Bark oil and its main molecule are tightly limited as skin sensitizers, so perfumers often build cinnamon accords instead.',
    contributes: 'Adds a warm, sweet spice that makes ambers and gourmands feel cozier.',
    synthetic: 'both',
    volatility: 'heart',
    character: { spicy: 0.8, warm: 0.6, sweet: 0.3 },
    hue: '#9A5A36',
  },
  {
    slug: 'clove',
    name: 'Clove',
    kind: 'material',
    family: 'spice',
    aliases: ['clove bud'],
    smellsLike: 'Hot, sweet and medicinal spice, somewhere between mulled wine and a dentist’s office.',
    origin:
      'Distilled from clove buds, leaves or stems. Eugenol, its main molecule, is also the heart of the carnation note.',
    contributes: 'Adds a strong, warm spiciness. A little reads cozy; a lot reads dental.',
    synthetic: false,
    volatility: 'heart',
    character: { spicy: 0.9, warm: 0.5 },
    hue: '#6A4A3A',
  },
  {
    slug: 'nutmeg',
    name: 'Nutmeg',
    kind: 'material',
    family: 'spice',
    aliases: ['mace'],
    smellsLike: 'Warm, woody and lightly sweet, like nutmeg grated over eggnog.',
    origin: 'Steam-distilled from the seed of the nutmeg tree. Mace comes from the lacy coating around the same seed.',
    contributes: 'Adds a soft, woody spice that warms up aromatic and woody fragrances.',
    synthetic: false,
    volatility: 'heart',
    character: { spicy: 0.7, warm: 0.4, woody: 0.3 },
    hue: '#8A6A4E',
  },
  {
    slug: 'saffron',
    name: 'Saffron',
    kind: 'material',
    family: 'spice',
    aliases: ['safran', 'safraleine'],
    smellsLike: 'Leathery, honeyed and a little metallic, like a warm spice rubbed into suede.',
    origin:
      'Real saffron extract is precious and rarely used. Saffron notes usually rely on synthetic molecules such as safraleine.',
    contributes: 'Adds a warm, leathery spice that pairs especially well with rose, oud and amber.',
    synthetic: true,
    volatility: 'heart',
    character: { spicy: 0.6, warm: 0.5, sweet: 0.2 },
    hue: '#B5743E',
  },
  {
    slug: 'ginger',
    name: 'Ginger',
    kind: 'material',
    family: 'spice',
    aliases: ['ginger root'],
    smellsLike: 'Fresh, zingy and lemony with a warm bite, like freshly grated ginger root.',
    origin: 'Steam-distilled or CO2-extracted from the dried root of the ginger plant.',
    contributes: 'Adds a fresh, spicy fizz to the opening that works in both fresh and warm fragrances.',
    synthetic: false,
    volatility: 'top',
    character: { spicy: 0.6, fresh: 0.6, warm: 0.2 },
    hue: '#C1A066',
  },
  {
    slug: 'cumin',
    name: 'Cumin',
    kind: 'material',
    family: 'spice',
    smellsLike:
      'Warm, earthy and sweaty, like cumin seeds in a hot pan. Overdosed, it reads as body odor, which is sometimes the point.',
    origin: 'Steam-distilled from cumin seeds.',
    contributes: 'Adds a warm, animalic, skin-like spice. Divisive in larger doses.',
    synthetic: false,
    volatility: 'heart',
    character: { spicy: 0.8, earthy: 0.4, warm: 0.4 },
    hue: '#8A6A3A',
  },

  // -------------------------------------------------------------- gourmand
  {
    slug: 'vanilla',
    name: 'Vanilla',
    kind: 'material',
    family: 'gourmand',
    aliases: ['vanilla bean', 'vanilla absolute', 'vanillin', 'bourbon vanilla'],
    smellsLike:
      'Sweet, creamy and warm, like vanilla ice cream. Real vanilla pods are also a bit smoky and boozy.',
    origin:
      'Natural vanilla comes from cured vanilla pods, extracted as an absolute or CO2 extract. Most vanilla notes lean heavily on synthetic vanillin and ethyl vanillin, which are cheaper and more consistent.',
    contributes: 'Adds sweetness, comfort and staying power. One of the most loved base notes in modern perfumery.',
    synthetic: 'both',
    volatility: 'base',
    character: { sweet: 0.9, warm: 0.5, creamy: 0.3 },
    hue: '#D2B48A',
  },
  {
    slug: 'tonka-bean',
    name: 'Tonka bean',
    kind: 'material',
    family: 'gourmand',
    aliases: ['tonka', 'tonka absolute'],
    smellsLike: 'Sweet, warm and almondy, like vanilla mixed with fresh hay and a hint of pipe tobacco.',
    origin:
      'Solvent-extracted from the seeds of a South American tree. Its main molecule, coumarin, was one of the first synthetics used in perfume and is still used widely on its own.',
    contributes:
      'Adds a warm, sweet depth that sits between vanilla and hay. Essential to fougères and many gourmands.',
    synthetic: 'both',
    volatility: 'base',
    character: { sweet: 0.7, warm: 0.6, powdery: 0.2 },
    hue: '#9A7A58',
  },
  {
    slug: 'caramel',
    name: 'Caramel',
    kind: 'accord',
    family: 'gourmand',
    aliases: ['toffee', 'burnt sugar'],
    smellsLike: 'Sweet, buttery and slightly burnt, like caramel sauce or toffee.',
    origin: 'An accord built around synthetics such as ethyl maltol, often with vanilla and buttery notes.',
    contributes: 'Adds a sticky, dessert-like sweetness that lasts a long time.',
    synthetic: true,
    volatility: 'base',
    character: { sweet: 0.9, warm: 0.4 },
    hue: '#A86F3A',
  },
  {
    slug: 'praline',
    name: 'Praline',
    kind: 'accord',
    family: 'gourmand',
    aliases: ['hazelnut praline', 'nougat'],
    smellsLike: 'Toasted nuts in caramel, like the sugared nuts sold at a winter fair.',
    origin: 'An accord combining caramel, vanilla and nutty synthetic molecules.',
    contributes: 'Adds a rich, nutty sweetness to gourmand and amber bases.',
    synthetic: true,
    volatility: 'base',
    character: { sweet: 0.9, warm: 0.4, creamy: 0.2 },
    hue: '#9A6A45',
  },
  {
    slug: 'cacao',
    name: 'Cacao',
    kind: 'material',
    family: 'gourmand',
    aliases: ['cocoa', 'chocolate', 'dark chocolate'],
    smellsLike: 'Dark, bitter and powdery, more like cocoa powder than a milk chocolate bar.',
    origin:
      'Extracted from roasted cocoa beans as an absolute or CO2 extract, often reinforced with synthetic notes.',
    contributes: 'Adds a dark, bittersweet depth that keeps gourmands from tipping into pure sugar.',
    synthetic: 'both',
    volatility: 'base',
    character: { sweet: 0.5, earthy: 0.4, warm: 0.4, powdery: 0.2 },
    hue: '#5A3A2E',
  },
  {
    slug: 'coffee',
    name: 'Coffee',
    kind: 'material',
    family: 'gourmand',
    aliases: ['coffee bean', 'espresso'],
    smellsLike: 'Roasted, bitter and warm, like freshly ground beans.',
    origin: 'CO2-extracted from roasted coffee beans, often supported by synthetic roasted notes.',
    contributes: 'Adds a dark, roasted bitterness that pairs well with vanilla, cardamom and woods.',
    synthetic: 'both',
    volatility: 'heart',
    character: { warm: 0.6, earthy: 0.4, sweet: 0.2, smoky: 0.2 },
    hue: '#4E3A2E',
  },
  {
    slug: 'honey',
    name: 'Honey',
    kind: 'accord',
    family: 'gourmand',
    aliases: ['beeswax'],
    smellsLike:
      'Sweet, warm and waxy with a faintly animal edge. Overdone, it can smell a bit like urine, which perfumers occasionally use on purpose.',
    origin:
      'Beeswax absolute brings a natural honey character, while synthetics such as phenylacetic acid add the sticky sweetness.',
    contributes: 'Adds a golden, slightly animalic sweetness to florals, tobaccos and ambers.',
    synthetic: 'both',
    volatility: 'base',
    character: { sweet: 0.8, warm: 0.5, floral: 0.2 },
    hue: '#C1913E',
  },
  {
    slug: 'almond',
    name: 'Almond',
    kind: 'accord',
    family: 'gourmand',
    aliases: ['bitter almond', 'marzipan'],
    smellsLike: 'Sweet, nutty and cherry-like, like marzipan or almond extract in a cake.',
    origin:
      'Built around benzaldehyde, the molecule that gives bitter almond and cherry their shared smell. Natural bitter almond oil is rarely used because it must first be stripped of toxic compounds.',
    contributes: 'Adds a soft, nutty sweetness that sits well with heliotrope, tonka and cherry.',
    synthetic: true,
    volatility: 'heart',
    character: { sweet: 0.6, creamy: 0.3, powdery: 0.2 },
    hue: '#D8C2A0',
  },
  {
    slug: 'pistachio',
    name: 'Pistachio',
    kind: 'accord',
    family: 'gourmand',
    smellsLike: 'Creamy, nutty and buttery, like pistachio gelato.',
    origin: 'An accord of nutty, milky and creamy synthetic molecules.',
    contributes: 'Adds a soft, savory-sweet creaminess that is less sugary than most gourmand notes.',
    synthetic: true,
    volatility: 'base',
    character: { creamy: 0.6, sweet: 0.5, green: 0.2 },
    hue: '#A8B07A',
  },
  {
    slug: 'rum',
    name: 'Rum',
    kind: 'accord',
    family: 'gourmand',
    aliases: ['rhum', 'dark rum'],
    smellsLike: 'Boozy, sweet and warm, like a glass of dark rum with a hint of molasses.',
    origin: 'An accord, sometimes including rum absolute or rum ethers, combined with sweet and woody synthetics.',
    contributes: 'Adds a boozy warmth that pairs well with tobacco, vanilla and spice.',
    synthetic: 'both',
    volatility: 'heart',
    character: { warm: 0.6, sweet: 0.5 },
    hue: '#7A4A2E',
  },
  {
    slug: 'milk',
    name: 'Milk',
    kind: 'accord',
    family: 'gourmand',
    aliases: ['milky', 'lactonic', 'steamed milk'],
    smellsLike: 'Soft, creamy and comforting, like warm milk or the smell of a baby’s head.',
    origin: 'An accord built on lactones, the same family of molecules behind peach and coconut notes.',
    contributes: 'Adds a gentle, creamy softness to gourmands, florals and woods.',
    synthetic: true,
    volatility: 'base',
    character: { creamy: 0.8, sweet: 0.3, clean: 0.2 },
    hue: '#EAE2D2',
  },

  // ----------------------------------------------------------------- woody
  {
    slug: 'cedarwood',
    name: 'Cedarwood',
    kind: 'material',
    family: 'woody',
    aliases: ['cedar', 'virginia cedar', 'atlas cedar'],
    smellsLike: 'Dry, clean and woody, like pencil shavings or the inside of a cedar chest.',
    origin:
      'Steam-distilled from cedar wood. Virginia and Texas cedar smell like pencils, while Atlas cedar from Morocco is softer and more balsamic.',
    contributes: 'Gives structure, dryness and staying power. One of the most common base notes in perfumery.',
    synthetic: false,
    volatility: 'base',
    character: { woody: 0.9, clean: 0.2 },
    hue: '#9A7A58',
  },
  {
    slug: 'sandalwood',
    name: 'Sandalwood',
    kind: 'material',
    family: 'woody',
    aliases: ['santal', 'mysore sandalwood', 'santalum'],
    smellsLike: 'Creamy, smooth and milky wood. Soft and warm rather than dry.',
    origin:
      'Steam-distilled from the heartwood of sandalwood trees. Indian sandalwood was badly overharvested, so most of it now comes from Australian plantations or is rebuilt with synthetics.',
    contributes: 'Adds a creamy, soft woodiness that rounds out a fragrance and lingers for hours.',
    synthetic: 'both',
    volatility: 'base',
    character: { woody: 0.7, creamy: 0.7, warm: 0.3 },
    hue: '#B8956A',
  },
  {
    slug: 'vetiver',
    name: 'Vetiver',
    kind: 'material',
    family: 'woody',
    aliases: ['khus', 'khus khus', 'vetyver'],
    smellsLike: 'Earthy, woody and a little smoky, with a grassy, rooty edge like wet soil around tree roots.',
    origin:
      'Steam-distilled from the roots of a tropical grass grown mostly in Haiti, Java and India. Each origin differs, from clean and grapefruit-like to dark and smoky.',
    contributes: 'Adds a dry, earthy polish and is the backbone of many fresh woody fragrances.',
    synthetic: false,
    volatility: 'base',
    character: { woody: 0.7, earthy: 0.6, green: 0.3, smoky: 0.2 },
    hue: '#6B6A45',
  },
  {
    slug: 'guaiac-wood',
    name: 'Guaiac wood',
    kind: 'material',
    family: 'woody',
    aliases: ['guaiacwood', 'gaiac'],
    smellsLike: 'Smoky, faintly rosy wood with a hint of tar, like a campfire built from good furniture.',
    origin: 'Steam-distilled from the wood of a tree that grows in the dry Gran Chaco region of Paraguay and Argentina.',
    contributes: 'Adds a smooth, smoky woodiness that sits well with rose, oud and leather.',
    synthetic: false,
    volatility: 'base',
    character: { woody: 0.7, smoky: 0.5, warm: 0.3 },
    hue: '#7A5A45',
  },
  {
    slug: 'hinoki',
    name: 'Hinoki',
    kind: 'material',
    family: 'woody',
    aliases: ['japanese cypress', 'hinoki cypress'],
    smellsLike: 'Clean, lemony and resinous wood, like a Japanese wooden bathtub or a freshly planed board.',
    origin: 'Steam-distilled from the wood of the Japanese cypress tree.',
    contributes: 'Adds a bright, clean woodiness, popular in calm, minimal compositions.',
    synthetic: false,
    volatility: 'base',
    character: { woody: 0.7, fresh: 0.4, clean: 0.3 },
    hue: '#C2A880',
  },
  {
    slug: 'cypress',
    name: 'Cypress',
    kind: 'material',
    family: 'woody',
    smellsLike: 'Green, resinous and dry, like pine needles but softer and more herbal.',
    origin: 'Steam-distilled from the needles and twigs of the Mediterranean cypress.',
    contributes: 'Adds a dry, green woodiness that bridges aromatic openings and woody bases.',
    synthetic: false,
    volatility: 'heart',
    character: { woody: 0.6, green: 0.5, fresh: 0.3 },
    hue: '#5E6E55',
  },
  {
    slug: 'pine',
    name: 'Pine',
    kind: 'material',
    family: 'woody',
    aliases: ['pine needle', 'pine needles', 'fir needle'],
    smellsLike: 'Sharp, resinous and green, like a walk through a pine forest or the corner where the tree stands in December.',
    origin: 'Steam-distilled from pine needles and twigs. Fir and other conifer oils are often used alongside it.',
    contributes: 'Adds a cold, outdoorsy freshness to aromatic and woody fragrances.',
    synthetic: false,
    volatility: 'top',
    character: { woody: 0.6, fresh: 0.6, green: 0.4 },
    hue: '#4E6A4E',
  },
  {
    slug: 'papyrus',
    name: 'Papyrus',
    kind: 'material',
    family: 'woody',
    aliases: ['cypriol', 'nagarmotha'],
    smellsLike: 'Dry, smoky and slightly leathery wood with an earthy edge.',
    origin:
      'True papyrus oil is rare. Many papyrus notes use cypriol, the root oil of a related sedge from India, along with woody synthetics.',
    contributes: 'Adds a dry, smoky texture to woods and leathers.',
    synthetic: 'both',
    volatility: 'base',
    character: { woody: 0.7, smoky: 0.4, earthy: 0.3 },
    hue: '#8A7A5E',
  },
  {
    slug: 'cashmeran',
    name: 'Cashmeran',
    kind: 'material',
    family: 'woody',
    aliases: ['cashmere wood', 'blonde woods'],
    smellsLike: 'Soft, musky and woody, like a warm cashmere sweater. A little spicy, a little fluffy.',
    origin:
      'A synthetic molecule first made in the 1970s. Despite the name, it has nothing to do with cashmere wool.',
    contributes: 'Adds a cozy, diffusive warmth that makes woods and musks feel soft and touchable.',
    synthetic: true,
    volatility: 'base',
    character: { woody: 0.5, warm: 0.5, powdery: 0.3 },
    hue: '#B5A08A',
  },
  {
    slug: 'iso-e-super',
    name: 'Iso E Super',
    kind: 'material',
    family: 'woody',
    aliases: ['iso e', 'ise'],
    smellsLike:
      'Soft, velvety woods with a faint cedar and amber glow. Some people find it radiant; others can barely smell it.',
    origin:
      'A synthetic woody-amber molecule from the 1970s. It is used everywhere, from tiny traces to huge doses, and is one of the most common materials in modern perfumery.',
    contributes: 'Adds a smooth, airy woodiness and makes everything around it feel bigger and more diffusive.',
    synthetic: true,
    volatility: 'base',
    character: { woody: 0.7, warm: 0.4, clean: 0.2 },
    hue: '#B3A58A',
  },
  {
    slug: 'oud',
    name: 'Oud',
    kind: 'material',
    family: 'woody',
    aliases: ['agarwood', 'oudh', 'aoud', 'oud oil', 'agar'],
    smellsLike:
      'Dark, rich wood with medicinal, smoky and sometimes barnyard sides. Real oud can be very different from the oud notes in most fragrances.',
    origin:
      'Forms in the heartwood of agar trees infected with a mold, and is distilled from that resin-soaked wood. Natural oud is rare and costly, so most perfumes use accords built from woods, leather notes and synthetics.',
    contributes: 'Adds depth, darkness and a slightly animalic woodiness. Pairs classically with rose and saffron.',
    synthetic: 'both',
    volatility: 'base',
    character: { woody: 0.8, smoky: 0.4, earthy: 0.3, warm: 0.3 },
    hue: '#4A3A30',
  },
  {
    slug: 'birch',
    name: 'Birch',
    kind: 'material',
    family: 'woody',
    aliases: ['birch wood', 'birch leaf'],
    smellsLike: 'Pale, fresh wood with a faint leathery, smoky edge, like birch logs stacked by a fireplace.',
    origin:
      'Birch leaf and bud oils exist, but most birch notes are blends of light woods with a little birch tar.',
    contributes: 'Adds a cool, slightly smoky woodiness that leans toward leather.',
    synthetic: 'both',
    volatility: 'base',
    character: { woody: 0.7, smoky: 0.3, fresh: 0.2 },
    hue: '#C3B8A0',
  },

  // ---------------------------------------------------------------- earthy
  {
    slug: 'patchouli',
    name: 'Patchouli',
    kind: 'material',
    family: 'earthy',
    aliases: ['patchouly', 'pachouli'],
    smellsLike:
      'Earthy, dark and woody with a sweet, almost chocolatey depth. Damp forest floor meets an old leather-bound book.',
    origin:
      'Steam-distilled from dried, lightly fermented patchouli leaves, mostly from Indonesia. Modern fractions remove the earthiest parts for a cleaner, woodier patchouli.',
    contributes: 'Gives depth, earthiness and long-lasting structure. A pillar of chypres and many ambers.',
    synthetic: false,
    volatility: 'base',
    character: { earthy: 0.8, woody: 0.5, warm: 0.3, sweet: 0.2 },
    hue: '#5A4A3A',
  },
  {
    slug: 'oakmoss',
    name: 'Oakmoss',
    kind: 'material',
    family: 'earthy',
    aliases: ['oak moss', 'mousse de chene', 'treemoss'],
    smellsLike: 'Damp, mossy and inky, like a forest floor after rain, with a slightly salty, leathery undertone.',
    origin:
      'Extracted from a lichen that grows on oak trees. Safety rules now limit it heavily, so modern oakmoss is usually treated to remove allergens or replaced with synthetics.',
    contributes: 'Gives a dark, bitter, earthy depth. The backbone of chypres and classic fougères.',
    synthetic: 'both',
    volatility: 'base',
    character: { earthy: 0.8, green: 0.4, woody: 0.3 },
    hue: '#5E6A4E',
  },
  {
    slug: 'hay',
    name: 'Hay',
    kind: 'accord',
    family: 'earthy',
    aliases: ['dried grass', 'hay absolute'],
    smellsLike: 'Warm, dry and sweet, like a barn full of dried grass at the end of summer.',
    origin:
      'An accord built around coumarin, sometimes with hay absolute, which is extracted from dried grasses.',
    contributes: 'Adds a sunny, sweet dryness that softens aromatic and tobacco compositions.',
    synthetic: 'both',
    volatility: 'heart',
    character: { earthy: 0.4, sweet: 0.4, warm: 0.4, green: 0.2 },
    hue: '#BFA46A',
  },

  // ------------------------------------------------------ resinous / amber
  {
    slug: 'amber',
    name: 'Amber',
    kind: 'accord',
    family: 'resinous',
    aliases: ['ambre', 'amber accord'],
    smellsLike:
      'Warm, sweet and resinous, a golden glow of vanilla, resins and a little powder. Nothing to do with the fossil resin in jewelry.',
    origin:
      'A fantasy accord with no single natural source, usually built from labdanum, benzoin and vanilla, plus other resins or synthetics.',
    contributes: 'Gives warmth, sweetness and long-lasting depth. The core of the amber family.',
    synthetic: 'both',
    volatility: 'base',
    character: { warm: 0.9, sweet: 0.5, powdery: 0.2 },
    hue: '#B07A3A',
  },
  {
    slug: 'labdanum',
    name: 'Labdanum',
    kind: 'material',
    family: 'resinous',
    aliases: ['cistus', 'rockrose', 'ciste'],
    smellsLike: 'Rich, leathery and ambery, with a slightly animalic, honeyed depth.',
    origin:
      'A sticky resin from the rockrose shrub of the Mediterranean, used as a resinoid, absolute or oil. Shepherds once combed it out of the beards of goats that grazed on the plants.',
    contributes:
      'The heart of most amber accords and a key part of chypres. Adds warmth and depth with a slight leathery edge.',
    synthetic: false,
    volatility: 'base',
    character: { warm: 0.8, sweet: 0.3, earthy: 0.2, smoky: 0.2 },
    hue: '#7A4E30',
  },
  {
    slug: 'benzoin',
    name: 'Benzoin',
    kind: 'material',
    family: 'resinous',
    aliases: ['siam benzoin', 'sumatra benzoin', 'gum benjamin'],
    smellsLike: 'Sweet, warm and vanilla-like with a soft balsamic edge. Cozy and a little powdery.',
    origin:
      'A resin tapped from trees in Southeast Asia, usually used as a resinoid. Siam benzoin is sweeter and more vanilla-like than the Sumatra type.',
    contributes: 'Adds a sweet, balsamic warmth to amber and gourmand bases.',
    synthetic: false,
    volatility: 'base',
    character: { sweet: 0.7, warm: 0.7, powdery: 0.3 },
    hue: '#B08A5A',
  },
  {
    slug: 'frankincense',
    name: 'Frankincense',
    kind: 'material',
    family: 'resinous',
    aliases: ['olibanum', 'boswellia'],
    smellsLike: 'Fresh, lemony and peppery resin with a cool, smoky smoothness. Brighter than most people expect.',
    origin:
      'A resin tapped from boswellia trees in Oman, Somalia and nearby regions, steam-distilled into an oil or extracted as a resinoid.',
    contributes: 'Adds a cool, airy smokiness, the backbone of most incense accords.',
    synthetic: false,
    volatility: 'base',
    character: { smoky: 0.5, fresh: 0.4, woody: 0.3, spicy: 0.2 },
    hue: '#A89F84',
  },
  {
    slug: 'myrrh',
    name: 'Myrrh',
    kind: 'material',
    family: 'resinous',
    smellsLike: 'Bitter, resinous and earthy, with a mushroomy, slightly medicinal sweetness.',
    origin: 'A resin from commiphora trees in the Horn of Africa and Arabia, used as an oil, resinoid or absolute.',
    contributes: 'Adds a dark, bittersweet resinous depth to incense, amber and rose compositions.',
    synthetic: false,
    volatility: 'base',
    character: { warm: 0.5, earthy: 0.4, smoky: 0.3, spicy: 0.2 },
    hue: '#8A5E3E',
  },
  {
    slug: 'opoponax',
    name: 'Opoponax',
    kind: 'material',
    family: 'resinous',
    aliases: ['opopanax', 'sweet myrrh'],
    smellsLike: 'Sweet, warm and balsamic, like a softer, honeyed myrrh.',
    origin: 'A resin from a tree closely related to myrrh, used as a resinoid or oil.',
    contributes: 'Adds a rich, sweet resinous warmth, common in amber bases.',
    synthetic: false,
    volatility: 'base',
    character: { warm: 0.7, sweet: 0.5, powdery: 0.2 },
    hue: '#9A6E45',
  },
  {
    slug: 'ambroxan',
    name: 'Ambroxan',
    kind: 'material',
    family: 'resinous',
    aliases: ['ambrox', 'ambroxide'],
    smellsLike:
      'Clean, warm and slightly salty, like skin after a day at the beach. Some people barely smell it; others find it loud.',
    origin:
      'A synthetic molecule usually made from sclareol, a component of clary sage, created to reproduce one facet of natural ambergris.',
    contributes:
      'Adds a radiant, long-lasting warmth with a mineral glow. A defining note of many modern fresh woody fragrances.',
    synthetic: true,
    volatility: 'base',
    character: { warm: 0.5, clean: 0.5, woody: 0.4 },
    hue: '#C2B49A',
  },
  {
    slug: 'ambergris',
    name: 'Ambergris',
    kind: 'accord',
    family: 'resinous',
    aliases: ['ambre gris', 'grey amber'],
    smellsLike:
      'Salty, musky and warm with a faint marine, tobacco-like sweetness. Hard to describe, easy to like.',
    origin:
      'Natural ambergris forms in the gut of sperm whales and ages for years at sea. It is rare and restricted in many countries, so perfume ambergris is almost always an accord built on ambroxan and related molecules.',
    contributes: 'Adds a glowing, salty warmth that makes a fragrance feel like skin.',
    synthetic: 'both',
    volatility: 'base',
    character: { warm: 0.6, clean: 0.3, fresh: 0.2, woody: 0.2 },
    hue: '#B8AE98',
  },
  {
    slug: 'elemi',
    name: 'Elemi',
    kind: 'material',
    family: 'resinous',
    smellsLike: 'Fresh, lemony and peppery resin, like frankincense with extra citrus.',
    origin: 'A resin from a tree native to the Philippines, steam-distilled into an oil.',
    contributes: 'Adds a bright, resinous sparkle to openings, a clean bridge into incense and woods.',
    synthetic: false,
    volatility: 'top',
    character: { fresh: 0.6, spicy: 0.3, woody: 0.2 },
    hue: '#C4B98A',
  },
  {
    slug: 'styrax',
    name: 'Styrax',
    kind: 'material',
    family: 'resinous',
    aliases: ['storax', 'liquidambar'],
    smellsLike: 'Balsamic, smoky and leathery with a hint of cinnamon, like an old leather armchair near a fire.',
    origin: 'A balsam from sweetgum trees, used as a resinoid or oil.',
    contributes: 'Adds a smoky, leathery sweetness to amber and leather bases.',
    synthetic: false,
    volatility: 'base',
    character: { warm: 0.6, smoky: 0.4, sweet: 0.3 },
    hue: '#6E4E3A',
  },

  // ------------------------------------------------------------------ musk
  {
    slug: 'musk',
    name: 'Musk',
    kind: 'material',
    family: 'musk',
    aliases: ['white musk', 'clean musk', 'musks'],
    smellsLike:
      'Soft, clean and skin-like, like fresh laundry or warm skin. Some people cannot smell certain musks at all.',
    origin:
      'Musk once came from the musk deer, but it was replaced by synthetic musks for ethical and legal reasons. A few plant materials, such as ambrette seed, also smell musky.',
    contributes: 'Adds softness, diffusion and staying power, and makes other notes feel smoother.',
    synthetic: 'both',
    volatility: 'base',
    character: { clean: 0.6, warm: 0.4, powdery: 0.3 },
    hue: '#D7CEC2',
  },
  {
    slug: 'ambrette',
    name: 'Ambrette',
    kind: 'material',
    family: 'musk',
    aliases: ['ambrette seed', 'musk mallow'],
    smellsLike: 'Soft and musky with a faint pear-like fruitiness and a warm, skin-like quality.',
    origin:
      'Steam-distilled or CO2-extracted from the seeds of a plant in the hibiscus family, one of the few natural musks from plants.',
    contributes: 'Adds a natural, velvety muskiness that softens florals and woods.',
    synthetic: false,
    volatility: 'base',
    character: { warm: 0.5, fruity: 0.3, clean: 0.3, powdery: 0.2 },
    hue: '#C7B79A',
  },
  {
    slug: 'aldehydes',
    name: 'Aldehydes',
    kind: 'material',
    family: 'musk',
    aliases: ['aldehyde', 'fatty aldehydes'],
    smellsLike:
      'Bright, soapy and fizzy, like crisp linen or a snuffed candle. Some people smell champagne bubbles, others smell an iron.',
    origin:
      'A family of synthetic molecules, some also found in nature in citrus peel and other plants. Fatty aldehydes became famous in early twentieth-century florals.',
    contributes: 'Adds lift, sparkle and a clean, soapy brightness to the opening.',
    synthetic: true,
    volatility: 'top',
    character: { clean: 0.8, fresh: 0.5, powdery: 0.2 },
    hue: '#E2E0D2',
  },

  // --------------------------------------------------------------- leather
  {
    slug: 'leather',
    name: 'Leather',
    kind: 'accord',
    family: 'leather',
    aliases: ['cuir'],
    smellsLike: 'Smoky, dry and slightly animalic, like a well-worn leather jacket or a saddle.',
    origin:
      'An accord, since leather itself is not extracted. Built from birch tar, quinolines, saffron-like molecules and other synthetics.',
    contributes: 'Adds a dark, textured warmth to woody, floral and smoky compositions.',
    synthetic: 'both',
    volatility: 'base',
    character: { smoky: 0.5, warm: 0.4, earthy: 0.3, woody: 0.2 },
    hue: '#6A4A3A',
  },
  {
    slug: 'suede',
    name: 'Suede',
    kind: 'accord',
    family: 'leather',
    aliases: ['daim'],
    smellsLike: 'Soft, powdery and gentle leather, like the inside of a suede glove.',
    origin: 'An accord of soft leathery synthetics, often with iris, musks and saffron notes.',
    contributes: 'Adds a velvety, skin-close leather without the smoke.',
    synthetic: true,
    volatility: 'base',
    character: { powdery: 0.5, warm: 0.4, smoky: 0.2 },
    hue: '#A8896A',
  },
  {
    slug: 'birch-tar',
    name: 'Birch tar',
    kind: 'material',
    family: 'leather',
    aliases: ['rectified birch tar'],
    smellsLike: 'Intensely smoky and tarry, like a campfire or a road being resurfaced.',
    origin: 'Made by dry distillation of birch bark, then purified for perfume use.',
    contributes: 'The classic source of smoky leather. A small amount adds a lot of character.',
    synthetic: false,
    volatility: 'base',
    character: { smoky: 0.9, woody: 0.3 },
    hue: '#3E322C',
  },

  // ---------------------------------------------------------------- smoky
  {
    slug: 'tobacco',
    name: 'Tobacco',
    kind: 'material',
    family: 'smoky',
    aliases: ['tobacco leaf', 'pipe tobacco', 'tobacco absolute'],
    smellsLike: 'Sweet, dry and honeyed, like an unlit pouch of pipe tobacco rather than a lit cigarette.',
    origin: 'Tobacco absolute is extracted from cured tobacco leaves and is often supported by synthetic notes.',
    contributes: 'Adds a warm, sweet, slightly smoky depth, often alongside vanilla, rum and honey.',
    synthetic: 'both',
    volatility: 'base',
    character: { warm: 0.6, sweet: 0.4, earthy: 0.3, smoky: 0.3 },
    hue: '#8A5E3A',
  },
  {
    slug: 'incense',
    name: 'Incense',
    kind: 'accord',
    family: 'smoky',
    aliases: ['church incense', 'temple incense'],
    smellsLike: 'Smoky, resinous and cool, like a stone church after a service.',
    origin: 'An accord built around frankincense, myrrh and other resins, often with smoky and mineral synthetics.',
    contributes: 'Adds a cool, contemplative smokiness to woods, ambers and florals.',
    synthetic: 'both',
    volatility: 'base',
    character: { smoky: 0.8, woody: 0.4, fresh: 0.2 },
    hue: '#7A7470',
  },
  {
    slug: 'cade',
    name: 'Cade',
    kind: 'material',
    family: 'smoky',
    aliases: ['cade oil', 'juniper tar'],
    smellsLike: 'Dark, smoky and tarry, like a smoldering campfire or smoked meat.',
    origin: 'Made by dry distillation of the wood of a juniper shrub that grows around the Mediterranean.',
    contributes: 'Adds a raw, smoky darkness to leathers and woods.',
    synthetic: false,
    volatility: 'base',
    character: { smoky: 0.9, woody: 0.4 },
    hue: '#4A3E36',
  },

  // ------------------------------------------------------------------- tea
  {
    slug: 'black-tea',
    name: 'Black tea',
    kind: 'accord',
    family: 'tea',
    aliases: ['tea', 'darjeeling'],
    smellsLike: 'Dry, slightly smoky and bitter, like a freshly brewed cup of strong black tea.',
    origin:
      'An accord of tea-like synthetics, sometimes with tea absolute, which is extracted from dried leaves but rarely used.',
    contributes: 'Adds a dry, slightly tannic warmth that grounds citrus and florals.',
    synthetic: 'both',
    volatility: 'heart',
    character: { woody: 0.3, earthy: 0.3, warm: 0.3, smoky: 0.2 },
    hue: '#6A4E3A',
  },
  {
    slug: 'green-tea',
    name: 'Green tea',
    kind: 'accord',
    family: 'tea',
    smellsLike: 'Light, fresh and slightly bitter, like steam rising from a cup of green tea.',
    origin: 'An accord built mostly from hedione and other fresh, green synthetic molecules.',
    contributes: 'Adds a calm, transparent freshness, popular in light summer fragrances.',
    synthetic: true,
    volatility: 'heart',
    character: { fresh: 0.6, green: 0.5, clean: 0.3 },
    hue: '#9AA77A',
  },
  {
    slug: 'matcha',
    name: 'Matcha',
    kind: 'accord',
    family: 'tea',
    aliases: ['matcha tea'],
    smellsLike: 'Rich, creamy and grassy, like a freshly whisked bowl of matcha.',
    origin: 'An accord combining green tea notes with milky, powdery and grassy synthetics.',
    contributes: 'Adds a soft, creamy greenness that sits between fresh and gourmand.',
    synthetic: true,
    volatility: 'heart',
    character: { green: 0.7, creamy: 0.4, earthy: 0.2 },
    hue: '#7E9A5A',
  },
  {
    slug: 'lapsang-souchong',
    name: 'Lapsang souchong',
    kind: 'accord',
    family: 'tea',
    aliases: ['lapsang', 'smoked tea'],
    smellsLike: 'Smoky, resinous tea, like a cup brewed over a pine campfire.',
    origin: 'An accord of black tea notes with smoky materials such as birch tar, cade or guaiacol.',
    contributes: 'Adds a dry, smoky warmth that links tea, leather and wood notes.',
    synthetic: 'both',
    volatility: 'heart',
    character: { smoky: 0.7, woody: 0.4, warm: 0.3 },
    hue: '#5A4A3E',
  },
  {
    slug: 'mate',
    name: 'Maté',
    kind: 'material',
    family: 'tea',
    aliases: ['mate', 'yerba mate'],
    smellsLike: 'Grassy, slightly smoky and bitter, like the South American herbal tea brewed in a gourd.',
    origin: 'Maté absolute is extracted from the dried leaves of the yerba mate plant and used in small amounts.',
    contributes: 'Adds a green, hay-like bitterness to aromatic and woody compositions.',
    synthetic: false,
    volatility: 'heart',
    character: { green: 0.6, earthy: 0.4, smoky: 0.2 },
    hue: '#7A7A4E',
  },

  // ----------------------------------------------------------- descriptors
  {
    slug: 'soapy',
    name: 'Soapy',
    kind: 'descriptor',
    family: 'musk',
    aliases: ['soap', 'clean soap'],
    smellsLike: 'Clean, waxy and bubbly, like a fresh bar of white soap.',
    origin:
      'Usually perceived from aldehydes, clean musks and floral molecules from the orange blossom and lily of the valley families. Many of these also scent real soap, so the link is partly learned.',
    contributes: 'Makes a fragrance read as clean, freshly washed and well-groomed.',
    synthetic: 'both',
    volatility: 'heart',
    character: { clean: 0.9, fresh: 0.3, powdery: 0.2 },
    hue: '#E4E1D6',
  },
  {
    slug: 'laundry',
    name: 'Laundry',
    kind: 'descriptor',
    family: 'musk',
    aliases: ['clean laundry', 'fresh laundry', 'detergent'],
    smellsLike: 'Freshly washed sheets, or a towel straight out of the dryer.',
    origin:
      'Mostly white musks, aldehydes and fresh floral molecules, many of which are the same ones used to scent detergents and fabric softeners.',
    contributes: 'Gives a comforting, close-to-skin cleanliness that many people find easy to wear.',
    synthetic: 'both',
    volatility: 'base',
    character: { clean: 0.9, fresh: 0.4, powdery: 0.2 },
    hue: '#DDE0DA',
  },
  {
    slug: 'metallic',
    name: 'Metallic',
    kind: 'descriptor',
    family: 'mineral',
    aliases: ['metal', 'coin', 'steel'],
    smellsLike: 'Cold, sharp and coin-like, like a handful of keys or a cold railing.',
    origin:
      'People often read aldehydes, some ozonic and green synthetics, and the rosy side of rose and geranium as metallic.',
    contributes: 'Adds a cool, modern edge that keeps sweet or floral compositions from feeling too soft.',
    synthetic: 'both',
    volatility: 'heart',
    character: { fresh: 0.5, clean: 0.3 },
    hue: '#9AA0A3',
  },
  {
    slug: 'mineral',
    name: 'Mineral',
    kind: 'descriptor',
    family: 'mineral',
    aliases: ['stone', 'wet stone', 'flint'],
    smellsLike: 'Cool and stony, like wet rocks or a pebble beach.',
    origin:
      'Usually perceived from ambroxan, geosmin, ozonic and salty notes, and certain smoky molecules that suggest struck flint.',
    contributes: 'Adds a cool, dry texture that makes fresh fragrances feel less sweet and more natural.',
    synthetic: 'both',
    volatility: 'heart',
    character: { fresh: 0.5, earthy: 0.3, clean: 0.3 },
    hue: '#A3A6A0',
  },
  {
    slug: 'ink',
    name: 'Ink',
    kind: 'descriptor',
    family: 'mineral',
    aliases: ['inky'],
    smellsLike: 'Slightly bitter, metallic and powdery, like fountain pen ink or a fresh newspaper.',
    origin:
      'Usually perceived from combinations of iris, oakmoss, saffron, cumin, smoky woods and aldehydes.',
    contributes: 'Adds a dark, intellectual dryness that reads as unusual and a little moody.',
    synthetic: 'both',
    volatility: 'heart',
    character: { earthy: 0.4, smoky: 0.3, powdery: 0.2 },
    hue: '#4A5060',
  },
  {
    slug: 'ozonic',
    name: 'Ozonic',
    kind: 'descriptor',
    family: 'marine',
    aliases: ['ozone', 'airy', 'fresh air'],
    smellsLike: 'The cool, electric air before a storm, or sheets dried outside on a windy day.',
    origin: 'Usually perceived from ozonic synthetics such as helional, along with calone and certain aldehydes.',
    contributes: 'Adds a bright, airy sense of space to fresh compositions.',
    synthetic: 'both',
    volatility: 'top',
    character: { fresh: 0.8, clean: 0.5 },
    hue: '#B8C8CC',
  },
  {
    slug: 'boozy',
    name: 'Boozy',
    kind: 'descriptor',
    family: 'gourmand',
    aliases: ['alcoholic', 'liqueur', 'cognac', 'whisky'],
    smellsLike: 'Sweet and warm, like a dessert soaked in rum or a glass of cognac.',
    origin:
      'Usually perceived from rum, cognac or whisky accords, fruity esters, and some resins and tonka-vanilla blends.',
    contributes: 'Adds a warm, slightly decadent glow, especially in evening fragrances.',
    synthetic: 'both',
    volatility: 'heart',
    character: { warm: 0.6, sweet: 0.5 },
    hue: '#8A5A3A',
  },
  {
    slug: 'animalic',
    name: 'Animalic',
    kind: 'descriptor',
    family: 'leather',
    aliases: ['dirty', 'skanky'],
    smellsLike: 'Warm, intimate and a bit dirty, like skin, sweat, fur or a horse stable.',
    origin:
      'Usually perceived from indolic florals like jasmine and orange blossom, synthetic stand-ins for civet and castoreum, cumin, labdanum, or musks that suggest the body.',
    contributes: 'Adds warmth, sensuality and a lived-in realism. In larger doses it divides opinion fast.',
    synthetic: 'both',
    volatility: 'base',
    character: { warm: 0.6, earthy: 0.4 },
    hue: '#6A5048',
  },
  {
    slug: 'waxy',
    name: 'Waxy',
    kind: 'descriptor',
    family: 'floral',
    aliases: ['candle wax', 'candle'],
    smellsLike: 'Smooth and dense, like a candle or the thick petals of a white flower.',
    origin: 'Often perceived from aldehydes, tuberose, gardenia, orris or beeswax absolute, which all share a candle-like texture.',
    contributes: 'Adds body and a smooth, almost tactile texture to florals.',
    synthetic: 'both',
    volatility: 'heart',
    character: { creamy: 0.4, clean: 0.3, floral: 0.3 },
    hue: '#E2D8BC',
  },
  {
    slug: 'fizzy',
    name: 'Fizzy',
    kind: 'descriptor',
    family: 'citrus',
    aliases: ['sparkling', 'effervescent', 'soda'],
    smellsLike: 'Bright and bubbly, like cracking open a can of soda.',
    origin: 'Usually perceived from citrus oils, pink pepper, ginger and some aldehydes in the opening.',
    contributes: 'Makes an opening feel lively and carbonated. It rarely outlasts the first half hour.',
    synthetic: 'both',
    volatility: 'top',
    character: { fresh: 0.8, fruity: 0.2 },
    hue: '#D6CF8E',
  },
  {
    slug: 'sunscreen',
    name: 'Sunscreen',
    kind: 'descriptor',
    family: 'marine',
    aliases: ['sun lotion', 'suntan lotion', 'sun cream', 'beachy'],
    smellsLike: 'Creamy, sweet and slightly floral, like sun lotion warming on skin.',
    origin:
      'Usually perceived from salicylates (once common in sunscreens), coconut lactones, frangipani and ylang-ylang.',
    contributes: 'Adds a holiday-like, creamy warmth that many people find instantly nostalgic.',
    synthetic: 'both',
    volatility: 'heart',
    character: { creamy: 0.6, sweet: 0.3, floral: 0.3, warm: 0.2 },
    hue: '#E6D4B0',
  },
  {
    slug: 'powdery',
    name: 'Powdery',
    kind: 'descriptor',
    family: 'floral',
    aliases: ['powder', 'talc', 'baby powder', 'makeup'],
    smellsLike: 'Soft and dry, like baby powder or a makeup compact.',
    origin:
      'Usually perceived from iris, violet, heliotrope, musks, vanillin and coumarin, which are also common in cosmetics, so the link is partly learned.',
    contributes: 'Adds softness and a gentle, old-fashioned elegance. Some people love it; others call it "grandma".',
    synthetic: 'both',
    volatility: 'base',
    character: { powdery: 0.9, sweet: 0.3, floral: 0.2 },
    hue: '#D8CDD0',
  },
];
