import type { SeedUser } from './types';

/**
 * Demo community members. All people, handles and bios are fictional.
 * Collections reference fragrance slugs from ROSTER.md.
 */
export const USERS: SeedUser[] = [
  {
    handle: 'demo',
    displayName: 'Demo Account',
    experience: 'learning',
    bio: 'The account you are poking around in. It owns a few bottles and has opinions about them, so feel free to edit both.',
    location: 'Leeds',
    owns: [
      'dior-sauvage',
      'not-a-perfume',
      'khamrah',
      'santal-33',
      'terre-d-hermes',
      'tobacco-vanille',
      'wood-sage-sea-salt',
      'philosykos',
      'bleu-de-chanel-edp',
      'lazy-sunday-morning',
    ],
    had: ['acqua-di-gio', 'one-million'],
    wants: ['un-jardin-sur-le-nil', 'gypsy-water', 'love-dont-be-shy', 'aventus'],
    favorites: ['dior-sauvage', 'santal-33'],
  },
  {
    handle: 'vetiverandrain',
    displayName: 'Priya S.',
    experience: 'enthusiast',
    bio: 'Monsoon person. If it smells like wet stone, crushed leaves or an umbrella drying in the hallway, I want to try it.',
    location: 'Bengaluru',
    owns: [
      'dior-sauvage',
      'un-jardin-sur-le-nil',
      'gypsy-water',
      'portrait-of-a-lady',
      'santal-33',
      'terre-d-hermes',
      'wood-sage-sea-salt',
      'grey-vetiver',
    ],
    had: ['nautica-voyage'],
    wants: ['lazy-sunday-morning', 'ysl-y-edp'],
    favorites: ['gypsy-water', 'portrait-of-a-lady'],
  },
  {
    handle: 'm.okonkwo',
    displayName: 'Chidi O.',
    experience: 'collector',
    bio: 'Architect. I collect ambers, leathers and anything with smoke in it, and I keep a spreadsheet my wife pretends not to know about.',
    location: 'Lagos',
    owns: [
      'dior-sauvage',
      'dior-homme-intense',
      'one-million',
      'black-opium',
      'oud-wood',
      'shalimar',
      'tobacco-vanille',
      'jazz-club',
      'love-dont-be-shy',
      'aventus',
      'hawas',
      'chergui',
      'club-de-nuit-intense-man',
      'bvlgari-black',
      'un-jardin-sur-le-nil',
      'baccarat-rouge-540',
    ],
    had: ['acqua-di-gio', 'nautica-voyage'],
    wants: ['jadore', 'ysl-y-edp'],
    favorites: ['tobacco-vanille', 'aventus', 'dior-homme-intense'],
  },
  {
    handle: 'hollis_k',
    displayName: 'Hollis K.',
    experience: 'professional',
    bio: 'Fragrance evaluator by day, which mostly means smelling forty versions of the same shampoo. Off the clock I wear the strange stuff.',
    location: 'Rotterdam',
    owns: [
      'dior-sauvage',
      'mitsouko',
      'bvlgari-black',
      'layton',
      'aventus',
      'chergui',
      'cool-water',
      'eau-sauvage',
      'chanel-no-5',
      'wood-sage-sea-salt',
    ],
    wants: ['jadore'],
    favorites: ['bvlgari-black', 'mitsouko'],
  },
  {
    handle: 'nightshiftnora',
    displayName: 'Nora',
    experience: 'learning',
    bio: 'Night-shift nurse. I wear one spray of something quiet at work and save anything louder for my days off.',
    location: 'Glasgow',
    owns: ['molecule-01', 'baccarat-rouge-540', 'love-dont-be-shy'],
    had: ['cheirosa-62'],
    wants: ['gypsy-water'],
    favorites: ['baccarat-rouge-540'],
  },
  {
    handle: 'tobi.sprays',
    displayName: 'Tobi A.',
    experience: 'new',
    bio: 'Second-year engineering student. Got into this because a guy in my lab always smelled good and would not tell me what it was.',
    location: 'Toronto',
    owns: ['club-de-nuit-intense-man', 'acqua-di-gio'],
    wants: ['dior-sauvage', 'tobacco-vanille'],
    favorites: ['club-de-nuit-intense-man'],
  },
  {
    handle: 'lena.wirth',
    displayName: 'Lena W.',
    experience: 'collector',
    bio: 'Forty years of chypres, aldehydes and the occasional mistake. I keep my vintage bottles in a wine fridge and I am not sorry.',
    location: 'Vienna',
    owns: [
      'mitsouko',
      'chanel-no-5',
      'cool-water',
      'portrait-of-a-lady',
      'eau-sauvage',
      'gypsy-water',
      'coco-mademoiselle',
      'baccarat-rouge-540',
      'un-jardin-sur-le-nil',
      'ysl-y-edp',
      'chergui',
      'aventus',
      'wood-sage-sea-salt',
      'terre-d-hermes',
    ],
    had: ['layton'],
    favorites: ['mitsouko', 'chanel-no-5'],
  },
  {
    handle: 'sunil_dxb',
    displayName: 'Sunil R.',
    experience: 'enthusiast',
    bio: 'Logistics manager. Big ambers in winter, something blue for the office, and I will always tell you what I paid.',
    location: 'Dubai',
    owns: ['dior-sauvage', 'one-million', 'oud-wood', 'shalimar', 'club-de-nuit-intense-man', 'tobacco-vanille'],
    wants: ['chergui', 'black-opium'],
    favorites: ['oud-wood', 'shalimar'],
  },
  {
    handle: 'cozykat',
    displayName: 'Kat',
    experience: 'learning',
    bio: 'Bakery smells forever. I started with body mists and I am slowly working my way up to things that last past lunch.',
    location: 'Austin',
    owns: ['la-vie-est-belle', 'cheirosa-62', 'good-girl', 'shalimar', 'love-dont-be-shy', 'angel'],
    wants: ['black-opium', 'philosykos'],
    favorites: ['love-dont-be-shy'],
  },
  {
    handle: 'yuki.tsuno',
    displayName: 'Yuki T.',
    experience: 'enthusiast',
    bio: 'Tea shop on weekdays, temple walks on weekends. I like scents that sit close and do not ask for attention.',
    location: 'Osaka',
    owns: ['grey-vetiver', 'chergui', 'lazy-sunday-morning', 'daisy', 'un-jardin-sur-le-nil', 'molecule-01'],
    wants: ['ysl-y-edp'],
    favorites: ['lazy-sunday-morning', 'chergui'],
  },
  {
    handle: 'fernhollow',
    displayName: 'Wren',
    experience: 'enthusiast',
    bio: 'Trail crew in summer, woodworking in winter. Most of what I wear smells like one of those two jobs.',
    location: 'Vancouver',
    owns: ['jazz-club', 'santal-33', 'khamrah', 'philosykos', 'terre-d-hermes', 'bleu-de-chanel-edp'],
    wants: ['ysl-y-edp', 'portrait-of-a-lady'],
    favorites: ['santal-33'],
  },
  {
    handle: 'gabriel.mtz',
    displayName: 'Gabriel M.',
    experience: 'enthusiast',
    bio: 'It is summer here most of the year, so I hunt for fresh scents that are not the same blue bottle everyone in my office wears.',
    location: 'Mexico City',
    owns: ['acqua-di-gio', 'bleu-de-chanel-edp', 'nautica-voyage', 'prada-l-homme', 'eau-sauvage', 'bombshell'],
    wants: ['wood-sage-sea-salt', 'grey-vetiver'],
    favorites: ['prada-l-homme', 'bleu-de-chanel-edp'],
  },
  {
    handle: 'aunt_bea',
    displayName: 'Bea',
    experience: 'learning',
    bio: 'Retired librarian. My daughter gave me a sample set for my seventieth and now there is a shelf where the cookbooks used to be.',
    location: 'Melbourne',
    owns: ['gypsy-water', 'daisy', 'not-a-perfume', 'coco-mademoiselle'],
    had: ['chanel-no-5'],
    wants: ['love-dont-be-shy'],
    favorites: ['gypsy-water'],
  },
  {
    handle: 'quietpip',
    displayName: 'Pip',
    experience: 'new',
    bio: 'Mostly here to work out what my partner wears. No bottles of my own yet.',
    location: 'Wellington',
  },
  {
    handle: 'jonas.e',
    displayName: 'Jonas E.',
    experience: 'enthusiast',
    bio: 'Cyclist and cologne loyalist. I splash, I do not spray, and I reapply at lunch without shame.',
    location: 'Hamburg',
    owns: ['eau-sauvage', 'hawas', 'cool-water', 'dior-sauvage', 'wood-sage-sea-salt', 'ysl-y-edp'],
    had: ['nautica-voyage'],
    wants: ['jadore', 'bleu-de-chanel-edp'],
    favorites: ['eau-sauvage', 'hawas'],
  },
  {
    handle: 'delphine.r',
    displayName: 'Delphine R.',
    experience: 'professional',
    bio: 'Eleven years on a department store fragrance counter. I have sprayed a thousand blotters and I still get excited about a good musk.',
    location: 'Lyon',
    owns: [
      'dior-sauvage',
      'un-jardin-sur-le-nil',
      'la-vie-est-belle',
      'flowerbomb',
      'mitsouko',
      'baccarat-rouge-540',
      'love-dont-be-shy',
      'coco-mademoiselle',
      'angel',
    ],
    wants: ['black-opium'],
    favorites: ['baccarat-rouge-540', 'mitsouko'],
  },
  {
    handle: 'thebluebottleguy',
    displayName: 'Marcus',
    experience: 'enthusiast',
    bio: 'Sales rep, lots of handshakes. I chase compliments and I am honest about it.',
    location: 'Atlanta',
    owns: ['dior-sauvage', 'acqua-di-gio', 'one-million', 'oud-wood', 'club-de-nuit-intense-man', 'tobacco-vanille'],
    had: ['nautica-voyage'],
    wants: ['dior-homme-intense', 'black-opium'],
    favorites: ['one-million', 'oud-wood'],
  },
  {
    handle: 'ana.lucia',
    displayName: 'Ana L.',
    experience: 'learning',
    bio: 'Dentist, mother of two, lover of white flowers. English is my second language so be kind with my reviews.',
    location: 'São Paulo',
    owns: ['flowerbomb', 'good-girl', 'la-vie-est-belle', 'bombshell'],
    had: ['cheirosa-62'],
    wants: ['black-opium', 'dior-sauvage'],
    favorites: ['flowerbomb'],
  },
  {
    handle: 'sofie.lund',
    displayName: 'Sofie L.',
    experience: 'collector',
    bio: 'Graphic designer with a small flat and a big shelf. Mostly pale, cold, quiet things. I own one sweet perfume and I am working on it.',
    location: 'Copenhagen',
    owns: [
      'dior-sauvage',
      'un-jardin-sur-le-nil',
      'wood-sage-sea-salt',
      'terre-d-hermes',
      'molecule-01',
      'bleu-de-chanel-edp',
      'ysl-y-edp',
      'grey-vetiver',
      'lazy-sunday-morning',
      'baccarat-rouge-540',
      'gypsy-water',
      'daisy',
    ],
    had: ['acqua-di-gio'],
    wants: ['santal-33', 'portrait-of-a-lady'],
    favorites: ['molecule-01', 'ysl-y-edp', 'wood-sage-sea-salt'],
  },
  {
    handle: 'oudhound',
    displayName: 'Faisal A.',
    experience: 'collector',
    bio: 'Grew up with my grandfather burning resin on Fridays. I compare everything to that smell and most things lose.',
    location: 'Riyadh',
    owns: [
      'dior-sauvage',
      'dior-homme-intense',
      'oud-wood',
      'shalimar',
      'tobacco-vanille',
      'chergui',
      'aventus',
      'jazz-club',
      'hawas',
      'love-dont-be-shy',
      'black-opium',
      'mitsouko',
    ],
    wants: ['jadore'],
    favorites: ['chergui', 'oud-wood'],
  },
  {
    handle: 'budgetbasil',
    displayName: 'Basil',
    experience: 'enthusiast',
    bio: 'Teacher on a teacher salary. I test the expensive ones so you know whether the cheap one is close enough.',
    location: 'Manchester',
    owns: ['club-de-nuit-intense-man', 'shalimar', 'not-a-perfume', 'good-girl', 'eau-sauvage', 'cool-water', 'nautica-voyage'],
    had: ['acqua-di-gio'],
    wants: ['dior-sauvage', 'tobacco-vanille'],
    favorites: ['club-de-nuit-intense-man', 'cool-water'],
  },
  {
    handle: 'mei.lin',
    displayName: 'Mei L.',
    experience: 'new',
    bio: 'Accountant. It is 32 degrees and humid here every day, so I mostly want to smell like a clean towel.',
    location: 'Singapore',
    owns: ['not-a-perfume', 'cheirosa-62', 'prada-l-homme'],
    wants: ['bombshell'],
    favorites: ['not-a-perfume'],
  },
  {
    handle: 'inkblot.ivy',
    displayName: 'Ivy',
    experience: 'enthusiast',
    bio: 'Printmaker. I like perfumes that smell like a workshop: ink, solvent, hot metal, burnt wood. Vanilla people, I respect you from a distance.',
    location: 'Edinburgh',
    owns: ['bvlgari-black', 'jazz-club', 'aventus', 'layton', 'terre-d-hermes', 'santal-33'],
    wants: ['chergui'],
    favorites: ['bvlgari-black', 'layton'],
  },
  {
    handle: 'coachdre',
    displayName: 'Dre',
    experience: 'learning',
    bio: 'High school PE teacher and assistant basketball coach. Three bottles, all of them blue.',
    location: 'Chicago',
    isPrivate: true,
    owns: ['acqua-di-gio', 'club-de-nuit-intense-man', 'nautica-voyage'],
    wants: ['one-million'],
    favorites: ['club-de-nuit-intense-man'],
  },
];
