import type { NoteFamily, NoteKind } from './types';

/**
 * The controlled note vocabulary for the seed catalogue.
 * Every slug referenced by a fragrance (official notes or perceived notes) must exist here.
 * Full descriptions live in notes.ts.
 */
export const NOTE_VOCABULARY: Record<string, { family: NoteFamily; kind: NoteKind }> = {
  // citrus
  bergamot: { family: 'citrus', kind: 'material' },
  lemon: { family: 'citrus', kind: 'material' },
  mandarin: { family: 'citrus', kind: 'material' },
  'sweet-orange': { family: 'citrus', kind: 'material' },
  'bitter-orange': { family: 'citrus', kind: 'material' },
  grapefruit: { family: 'citrus', kind: 'material' },
  lime: { family: 'citrus', kind: 'material' },
  yuzu: { family: 'citrus', kind: 'material' },
  petitgrain: { family: 'citrus', kind: 'material' },
  'blood-orange': { family: 'citrus', kind: 'material' },
  citron: { family: 'citrus', kind: 'material' },
  // aromatic
  lavender: { family: 'aromatic', kind: 'material' },
  rosemary: { family: 'aromatic', kind: 'material' },
  'clary-sage': { family: 'aromatic', kind: 'material' },
  basil: { family: 'aromatic', kind: 'material' },
  mint: { family: 'aromatic', kind: 'material' },
  thyme: { family: 'aromatic', kind: 'material' },
  artemisia: { family: 'aromatic', kind: 'material' },
  'juniper-berry': { family: 'aromatic', kind: 'material' },
  geranium: { family: 'aromatic', kind: 'material' },
  tarragon: { family: 'aromatic', kind: 'material' },
  // green
  'violet-leaf': { family: 'green', kind: 'material' },
  galbanum: { family: 'green', kind: 'material' },
  'fig-leaf': { family: 'green', kind: 'material' },
  'tomato-leaf': { family: 'green', kind: 'material' },
  'blackcurrant-bud': { family: 'green', kind: 'material' },
  rhubarb: { family: 'green', kind: 'accord' },
  'cut-grass': { family: 'green', kind: 'accord' },
  bamboo: { family: 'green', kind: 'accord' },
  cucumber: { family: 'green', kind: 'accord' },
  // marine
  'marine-notes': { family: 'marine', kind: 'accord' },
  'sea-salt': { family: 'marine', kind: 'accord' },
  calone: { family: 'marine', kind: 'material' },
  seaweed: { family: 'marine', kind: 'material' },
  petrichor: { family: 'marine', kind: 'accord' },
  // floral
  rose: { family: 'floral', kind: 'material' },
  jasmine: { family: 'floral', kind: 'material' },
  'orange-blossom': { family: 'floral', kind: 'material' },
  neroli: { family: 'floral', kind: 'material' },
  tuberose: { family: 'floral', kind: 'material' },
  iris: { family: 'floral', kind: 'material' },
  violet: { family: 'floral', kind: 'accord' },
  'ylang-ylang': { family: 'floral', kind: 'material' },
  magnolia: { family: 'floral', kind: 'material' },
  peony: { family: 'floral', kind: 'accord' },
  'lily-of-the-valley': { family: 'floral', kind: 'accord' },
  gardenia: { family: 'floral', kind: 'accord' },
  osmanthus: { family: 'floral', kind: 'material' },
  mimosa: { family: 'floral', kind: 'material' },
  heliotrope: { family: 'floral', kind: 'accord' },
  carnation: { family: 'floral', kind: 'accord' },
  frangipani: { family: 'floral', kind: 'accord' },
  honeysuckle: { family: 'floral', kind: 'accord' },
  // fruity
  pear: { family: 'fruity', kind: 'accord' },
  'green-apple': { family: 'fruity', kind: 'accord' },
  blackcurrant: { family: 'fruity', kind: 'accord' },
  fig: { family: 'fruity', kind: 'accord' },
  peach: { family: 'fruity', kind: 'accord' },
  plum: { family: 'fruity', kind: 'accord' },
  cherry: { family: 'fruity', kind: 'accord' },
  raspberry: { family: 'fruity', kind: 'accord' },
  pineapple: { family: 'fruity', kind: 'accord' },
  coconut: { family: 'fruity', kind: 'accord' },
  lychee: { family: 'fruity', kind: 'accord' },
  // spice
  'pink-pepper': { family: 'spice', kind: 'material' },
  'black-pepper': { family: 'spice', kind: 'material' },
  cardamom: { family: 'spice', kind: 'material' },
  cinnamon: { family: 'spice', kind: 'material' },
  clove: { family: 'spice', kind: 'material' },
  nutmeg: { family: 'spice', kind: 'material' },
  saffron: { family: 'spice', kind: 'material' },
  ginger: { family: 'spice', kind: 'material' },
  cumin: { family: 'spice', kind: 'material' },
  // gourmand
  vanilla: { family: 'gourmand', kind: 'material' },
  'tonka-bean': { family: 'gourmand', kind: 'material' },
  caramel: { family: 'gourmand', kind: 'accord' },
  praline: { family: 'gourmand', kind: 'accord' },
  cacao: { family: 'gourmand', kind: 'material' },
  coffee: { family: 'gourmand', kind: 'material' },
  honey: { family: 'gourmand', kind: 'accord' },
  almond: { family: 'gourmand', kind: 'accord' },
  pistachio: { family: 'gourmand', kind: 'accord' },
  rum: { family: 'gourmand', kind: 'accord' },
  milk: { family: 'gourmand', kind: 'accord' },
  // woody
  cedarwood: { family: 'woody', kind: 'material' },
  sandalwood: { family: 'woody', kind: 'material' },
  vetiver: { family: 'woody', kind: 'material' },
  'guaiac-wood': { family: 'woody', kind: 'material' },
  hinoki: { family: 'woody', kind: 'material' },
  cypress: { family: 'woody', kind: 'material' },
  pine: { family: 'woody', kind: 'material' },
  papyrus: { family: 'woody', kind: 'material' },
  cashmeran: { family: 'woody', kind: 'material' },
  'iso-e-super': { family: 'woody', kind: 'material' },
  oud: { family: 'woody', kind: 'material' },
  birch: { family: 'woody', kind: 'material' },
  // earthy
  patchouli: { family: 'earthy', kind: 'material' },
  oakmoss: { family: 'earthy', kind: 'material' },
  hay: { family: 'earthy', kind: 'accord' },
  // resinous / amber
  amber: { family: 'resinous', kind: 'accord' },
  labdanum: { family: 'resinous', kind: 'material' },
  benzoin: { family: 'resinous', kind: 'material' },
  frankincense: { family: 'resinous', kind: 'material' },
  myrrh: { family: 'resinous', kind: 'material' },
  opoponax: { family: 'resinous', kind: 'material' },
  ambroxan: { family: 'resinous', kind: 'material' },
  ambergris: { family: 'resinous', kind: 'accord' },
  elemi: { family: 'resinous', kind: 'material' },
  styrax: { family: 'resinous', kind: 'material' },
  // musk
  musk: { family: 'musk', kind: 'material' },
  ambrette: { family: 'musk', kind: 'material' },
  aldehydes: { family: 'musk', kind: 'material' },
  // leather
  leather: { family: 'leather', kind: 'accord' },
  suede: { family: 'leather', kind: 'accord' },
  'birch-tar': { family: 'leather', kind: 'material' },
  // smoky
  tobacco: { family: 'smoky', kind: 'material' },
  incense: { family: 'smoky', kind: 'accord' },
  cade: { family: 'smoky', kind: 'material' },
  // tea
  'black-tea': { family: 'tea', kind: 'accord' },
  'green-tea': { family: 'tea', kind: 'accord' },
  matcha: { family: 'tea', kind: 'accord' },
  'lapsang-souchong': { family: 'tea', kind: 'accord' },
  mate: { family: 'tea', kind: 'material' },
  // descriptors: how people describe what they smell
  soapy: { family: 'musk', kind: 'descriptor' },
  laundry: { family: 'musk', kind: 'descriptor' },
  metallic: { family: 'mineral', kind: 'descriptor' },
  mineral: { family: 'mineral', kind: 'descriptor' },
  ink: { family: 'mineral', kind: 'descriptor' },
  ozonic: { family: 'marine', kind: 'descriptor' },
  boozy: { family: 'gourmand', kind: 'descriptor' },
  animalic: { family: 'leather', kind: 'descriptor' },
  waxy: { family: 'floral', kind: 'descriptor' },
  fizzy: { family: 'citrus', kind: 'descriptor' },
  sunscreen: { family: 'marine', kind: 'descriptor' },
  powdery: { family: 'floral', kind: 'descriptor' },
};

export const NOTE_SLUGS = Object.keys(NOTE_VOCABULARY);
